libp2p/js-libp2p

- .gitignore
- .travis.yml
- examples/level1-swarm/node-1.js
- examples/level1-swarm/node-2.js
- package.json
- src/index.js
- test/index.spec.js
Ref https://github.com/dignifiedquire/dignified.js/issues/1
> Use dignified.js

- README.md
- src/index.js
Work tracker: https://github.com/libp2p/js-libp2p-dht/pull/1
> [WIP] Awesome DHT

- src/index.js
Switched to "start" and "stop" events. Also, replaced .isOn() with .isStarted().
> State: events and query changes

- examples/discovery-mechanisms/1.js
- examples/discovery-mechanisms/2.js
- examples/discovery-mechanisms/README.md
> docs(examples): Peer Discovery Mechanisms 1, 2 and 3

- examples/pubsub/1.js
- examples/pubsub/README.md
> Tutorial: Publish Subscribe

- examples/peer-and-content-routing/1.js
- examples/peer-and-content-routing/2.js
Related to #126.
Increase the added delay to let the peer establish connections from `100 ms` to `300 ms`.
> docs(examples): fix peer-content routing example scripts

- src/index.js
When issuing a `node.stop()`, some asynchronous actions may still be happening, which sometimes originates random "The libp2p node is not started yet" errors.
This prevents that by assuming the node is only stopped after the stopping process is complete.
> fix: prevent "The libp2p node is not started yet" when stopping

- examples/libp2p-in-the-browser/1/src/create-node.js
According to https://github.com/libp2p/js-libp2p-webrtc-star/issues/134 and my own fiddling with this example.
> tcp/443 on webrtc-star example.

- examples/libp2p-in-the-browser/1/src/create-node.js
Fixes this error when trying to run `libp2p-in-the-browser`
```
bundle.js:26971 Uncaught Error: invalid multiaddr: /dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star/ipfs/QmRyD2DLGSMryhoXTc7HBGbesSi9fSCmEnWUq4y6W3PjCL
at cleanUrlSIO (bundle.js:26971)
```
> Update to new URL format

- pdd/package.json
- pdd/pdd-transport--story-1--peer-a.js
- pdd/pdd-transport--story-1--peer-b.js
- pdd/pdd-transport--story-2--peer-a.js
- pdd/pdd-transport--story-2--peer-b.js
Original pr: url for interop pkg was pointing to non-existing branch causing this error
```
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout pdd
npm ERR! error: pathspec 'pdd' did not match any file(s) known to git.
npm ERR! 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maciej/.npm/_logs/2018-01-09T18_00_00_382Z-debug.log
```
also fixes #139
> Various pdd fixes

- src/index.js
I think there was a typo that would have ignored passed options and fallback to defaults for DHT datastore.
> Looks like a typo in DHT setup

- README.md
- examples/chat/src/dialer.js
- examples/echo/src/dialer.js
- examples/encrypted-communications/1.js
- examples/protocol-and-stream-muxing/1.js
- examples/protocol-and-stream-muxing/2.js
- examples/protocol-and-stream-muxing/README.md
- examples/transports/2.js
- examples/transports/3.js
- examples/transports/README.md
- src/content-routing.js
- src/dht.js
- src/get-peer-info.js
- src/index.js
- src/peer-routing.js
- test/circuit-relay.node.js
- test/stream-muxing.node.js
- test/transports.browser.js
- test/transports.node.js
- test/utils/try-echo.js
> dialProtocol

- examples/discovery-mechanisms/README.md
Enable missing syntax highlighting for example code in `discovery-mechanisms/README.md`.
> enable missing syntax highlighting

- examples/README.md
> docs: typo in examples readme.md

- .travis.yml
- circle.yml
- package.json
> Latest wrtc is breaking support in Node.js

- examples/transports/README.md
- Fixes typos
- Adds instructions
- Fixes some markdown syntax highlights
> docs: Minor fixes in Transport example readme

- package.json
This PR just updates libp2p-switch when we are able to get switch all the way to IPFS we will support `create-react-app` out-of-box.
Related PR and Issues: 
- https://github.com/libp2p/js-libp2p-switch/pull/259
- https://github.com/ipfs/js-ipfs/issues/1321#issuecomment-393085880
> chore: update libp2p-switch

- package.json
- src/index.js
> feat: set and hook up libp2p-connection-manager

- README.md
- examples/transports/1.js
- examples/transports/2.js
- examples/transports/3.js
- examples/transports/README.md
- package.json
- src/index.js
- test/utils/bundle-browser.js
- test/utils/bundle-nodejs.js
This includes updates to the already changed examples.
This leverages `@nodeutils/defaults-deep` instead of `lodash.defaultsdeep`. This ensures that cloning of objects does not happen. This will also make sure that an array passed within options, will not be stomped on by defaults. Passed arrays win over defaults.
Example:
```js
const options = {
modules: {
peerDiscovery: [Bootstrap, wsStar.discovery]
}
}
const defaults = {
modules: {
peerDiscovery: [MulticastDNS]
}
}
return defaultsDeep(options, defaults)
```
will result in a returned object deeply equivalent to the options.
* Clarifies some nested callback naming
* Removes redundant looping over transports
> refactor: use different defaultsDeep and clean up some code

- src/config.js
- src/index.js
- test/config.spec.js
- test/peer-discovery.node.js
This PR will enable any provided peer discovery modules by default if no configuration for the module is supplied/needed.
As before, modules can be explicitly disabled or enabled by passing config.
**This enables pre-configured modules (instances) to be passed and enabled without them having to have a `tag` and an unused config section.**
> feat: enable peer discovery modules by default

- OKR.md
**libp2p:**
- [Spreadsheet for 2018 2018 Q3](https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=1241853194)
- [PR for 2018 Q2 for reference](https://github.com/ipfs/js-ipfs/pull/1281)
> docs: 2018 Q3 OKRs

- README.md
- package.json
- src/index.js
- test/create.spec.js
- test/utils/bundle-browser.js
Resolves #224 
This will start the connection manager on `libp2p.start` and stop it on `libp2p.stop`. Previously users would need to start and stop it themselves.
> fix: start and stop connection manager with libp2p

- README.md
- src/config.js
- src/index.js
- test/node.js
- test/pnet.node.js
This adds the ability to specify a connection protector (private networking) via the new libp2p configuration.  Once https://github.com/libp2p/js-libp2p-pnet/pull/1 is released, we will be able to add that as a protector, such as through js-ipfs.
This will require an update to the libp2p-switch version once [js-libp2p-switch#266](https://github.com/libp2p/js-libp2p-switch/pull/266) is released.
> Add ability to pass a connection protector for private networking

- src/get-peer-info.js
- test/get-peer-info.spec.js
1. `multiaddr(input)` can throw, so put a try/catch around this
2. Do not throw, but callback with error for multiaddr which is not a peer info multiaddr
> fix: callback with error for invalid or non-peer multiaddr

- README.md
The JSON in the example was missing some commas.
> docs: fix example in README

- README.md
The example in the README can now be used with simply copy & pasting,
no errors will be thrown.
Fixes #234.
> docs: make example from README copy & pastable

- package.json
- src/dht.js
- test/dht.node.js
Changed `dht.get` and `dht.getMany` `maxTimeout` parameter to an `options` parameter with the `maxTimeout` property as discussed [here](https://github.com/libp2p/js-libp2p/pull/248#pullrequestreview-156962993).
In spite of not breaking the tests here, we should wait for the merging and release of the following PR:
> fix: dht get options

- OKR.md
Ref: https://github.com/ipfs/pm/issues/698
- [2018 Q3 Retrospective Document](https://docs.google.com/document/d/1ITVW5yysj0bZiluEKasQ57edpNwOZ-P5GQGgoclwQno/edit#heading=h.906pmio05dzr). Please complete this ASAP.
- [Previous OKR Planning for reference](https://github.com/libp2p/js-libp2p/pull/207)
- [2018 Q4 OKR Spreadsheet](https://docs.google.com/spreadsheets/d/1BYwmbVicgo6_tOHAbgiUXWge8Ej0qR1M_gAUulazmrg/edit#gid=1241853194)
@vasco-santos, @jacobheun et al, you know the drill :)
> 2018 Q4 OKRs Planning

- README.md
- package.json
- src/config.js
- src/index.js
- test/create.spec.js
- test/utils/bundle-browser.js
- test/utils/bundle-nodejs.js
Currently the DHT's `randomWalk` was not being started. Accordingly, a peer did not find other peers in the network unless we connect them manually.
Needs:
> fix: start kad dht random walk

- README.md
- src/config.js
- test/config.spec.js
This change enables circuit relay by default, hop is still disabled, to help improve default connectivity.
Resolves https://github.com/libp2p/js-libp2p/issues/253
> feat: enable relay by default (no hop)

- package.json
- src/config.js
- src/index.js
- test/dht.node.js
In the context of the awesome endeavour for enabling the DHT by default in `js-ipfs`, `libp2p` must receive an option with a `datastore` to be used [js-ipfs#856#issuecomment-434601550](https://github.com/ipfs/js-ipfs/pull/856#issuecomment-434601550)
> feat: add datastore to config

- src/content-routing.js
- src/peer-routing.js
- test/content-routing.node.js
- test/peer-routing.node.js
It was possible for `callback` to be called in the peer and content routers before its type was properly checked. This adds tests and fixes the issue.
> fix: dont call callback before it's properly set

- README.md
- package.json
- src/content-routing.js
- test/content-routing.node.js
In the context of [libp2p/js-libp2p-kad-dht#54](https://github.com/libp2p/js-libp2p-kad-dht/issues/54). 
Needs:
> chore: add maxNumProviders to findprovs

- src/config.js
- src/index.js
- test/config.spec.js
- test/transports.node.js
Allow configurable validators and selectors. Users of `libp2p` with `libp2p-kad-dht` must be able to set their own validators and selectors. 
For instance, this is important for `js-ipfs` to use `/ipns/` namespaces in the DHT
> feat: allow configurable validators and selectors to the dht

- src/index.js
Fixes #291 
constructor.name will gets modified by minifiers. Symbol.toStringTag does not, let's use that.  All transports are using `class-is` and are setting their class names to support this change.
> fix: use symbol instead of constructor name

- package.json
- src/index.js
- test/fsm.spec.js
- test/stream-muxing.node.js
- test/transports.browser.js
- test/transports.node.js
- test/turbolence.node.js
This does a few things:
* Update deps
* Updates to the latest switch and fixes test usage due to the update 
* Removes transports from the switch, after it stops, instead of before
* Passes not started errors to the callbacks rather than throwing assertion errors
depends on https://github.com/libp2p/js-libp2p-switch/pull/291
related to https://github.com/ipfs/js-ipfs/issues/1761
> fix not started yet

- OKR.md
Q1 is around the corner! OKR presentations are scheduled for the 20th, so we need to get our list together before then.
* [2018 Q4 Retrospective Document](https://docs.google.com/document/d/1z6_eTW_8pI5VUj5UMq4K_Gpofofd7ENwzLdEBCuNULI/edit).
* [Previous OKR Planning for reference](https://github.com/libp2p/js-libp2p/pull/247)
* [2019 Q1 OKR Spreadsheet](https://docs.google.com/spreadsheets/d/11GKG1DBRIIAiQnHvLD7_IqWxDGsVdaZFpxJM6NWtXe8/edit#gid=1271182838)
cc: @mgoelzer
> 2019 Q1 OKRs Planning

- README.md
- src/config.js
- src/index.js
- test/config.spec.js
- test/content-routing.node.js
- test/create.spec.js
- test/dht.node.js
- test/fsm.spec.js
- test/peer-routing.node.js
- test/pnet.node.js
- test/stats.js
- test/utils/bundle-browser.js
- test/utils/bundle-nodejs.js
Enable dht by default for `node` in libp2p
Needed in the context of https://github.com/ipfs/js-ipfs/pull/856
> chore: enable dht by default

- package.json
- src/index.js
- src/util/index.js
- test/fsm.spec.js
This fixes an issue where, if an error occurred during starting or stopping the node, the callback would not be called. This was introduced during the recent change to state machine.
`start` and `stop` will now call `callback` as soon as either an error occurs, or their respective state is emitted, instead of only the latter.
ref: https://github.com/ipfs/js-ipfs/issues/1806#issuecomment-456109308
> fix: start and stop error callback

- RELEASE.md
Resolves https://github.com/libp2p/js-libp2p/issues/296
Also:
- Adds prerelease commands
- link updates
- checklist item for copying release notes to the github release
> chore: update the release template

- src/index.js
`_isStarted` is an outdated property and shouldn't exist in the code anymore. The state machine handles start logic and the `isStarted` computed property pulls from there. The code comments around dht and pubsub are also no longer valid, so they were deleted.
> chore: remove _isStarted as it's no longer used

- package.json
- src/index.js
- test/peer-discovery.node.js
> fix: emit peer discovery for dht discovery

- examples/chat/src/dialer.js
- examples/chat/src/listener.js
- examples/delegated-routing/src/App.js
- examples/discovery-mechanisms/1.js
- examples/discovery-mechanisms/README.md
- examples/echo/src/dialer.js
- examples/echo/src/listener.js
- examples/libp2p-in-the-browser/1/package.json
- examples/libp2p-in-the-browser/1/src/browser-bundle.js
- examples/libp2p-in-the-browser/1/src/create-node.js
- examples/peer-and-content-routing/README.md
- examples/protocol-and-stream-muxing/README.md
- examples/transports/README.md
- pdd/pdd-the-ipfs-bundle--story-1--peer-a.js
- pdd/pdd-the-ipfs-bundle--story-1--peer-b.js
- pdd/pdd-transport--story-1--peer-a.js
- pdd/pdd-transport--story-2--peer-a.js
- pdd/pdd-transport--story-3--peer-a.js
- pdd/pdd-transport--story-3--peer-b.js
- src/index.js
- test/circuit-relay.node.js
- test/content-routing.node.js
- test/transports.browser.js
- test/turbolence.node.js
https://github.com/multiformats/js-multiaddr/pull/76 changed the default protocol from ipfs to p2p.
js-multiaddr is a transitive dependency of peer-info, so in order to get this change, we had to bump the version of peer-info.
> Change from ipfs to p2p protocol

- package.json
- test/stream-muxing.node.js
- test/transports.browser.js
- test/utils/bundle-browser.js
- test/utils/bundle-nodejs.js
This adds `pull-mplex` to the test suite, namely the stream muxing tests to verify interoperability.
> test: add pull-mplex to test suite

- src/pubsub.js
- test/pubsub.node.js
Hi :-)  
following up on an issue in [interface-js-ipfs-core](https://github.com/ipfs/interface-js-ipfs-core/issues/436) I'm creating this PR. 
Also created PR in [js-ipfs-http-client](https://github.com/ipfs/js-ipfs-http-client/pull/940) accordingly. 
This would help in cases like mine where my implementation is not able to support references to a handler function.
I will add the final url in the README to the method documentation once I merge the final PR `to interface-js-ipfs-core` since its pointing nowhere now. 
**Edit:** 
Opened a [PR](https://github.com/ipfs/interface-js-ipfs-core/pull/437) on `interface-js-ipfs-core`
> PUBSUB: unsubscribe without handler reference

- package.json
- src/config.js
Testing the 0.25 release candidate against js-ipfs, the test suite [errored](https://travis-ci.com/ipfs/js-ipfs/jobs/179820871) due to the config being too restrictive. I've simplified the config which has also allowed us to remove `kind-of`.
> fix: make the config less restrictive

- .aegir.js
- test/browser.js
- test/circuit-relay.browser.js
- test/transports.browser.js
- test/utils/constants.js
- test/utils/echo.js
Browser tests weren't being run for circuit relay. This adds a basic echo test for two browser nodes over a nodejs node to give us better visibility to potential issues.
> test: add circuit browser test

- src/dht.js
- src/error-messages.js
- src/errors.js
- src/pubsub.js
- test/dht.node.js
- test/pubsub.node.js
Added error codes to the dht and pubsub errors, as well as replaced `setImmediate` by `nextTick`.
In the context of [ipfs/js-ipfs#1879](https://github.com/ipfs/js-ipfs/pull/1879)
> chore: add error codes to dht and pubsub errors

- src/config.js
- test/config.spec.js
Currently `js-ipfs` was having a bad time with CPU usage. 
In this context, we decided to go with a temporary change on `dht.put`, as well as disabling the `random-walk` discovery. We will benefit from discovery through the queries that we will be running for now. 
With this, we will get `js-libp2p` stable, as well as have the DHT available and have time to implement a proper solution to solve this issue.
More details about the problem and discussion of the solution:
- [libp2p/js-libp2p-kad-dht#86](https://github.com/libp2p/js-libp2p-kad-dht/issues/86)
> chore: disable dht discovery

- src/config.js
- test/config.spec.js
Turning the dht off by default exposed an issue where the modules.transport.length wasn't being properly validated. This also fixes that.
required by https://github.com/libp2p/js-libp2p/issues/338
> fix: disable dht by default #338

- .aegir.js
- package.json
- src/index.js
- test/circuit-relay.node.js
- test/peer-discovery.node.js
With https://github.com/libp2p/js-libp2p-kad-dht/pull/92 the dht test for peer discovery was out of date. I fixed it and updated the other tests to use lower intervals so we dont have to wait 10seconds for discovery to happen.
The circuit tests were also inaccurate so those were fixed.
Switch had a significant number of code added recently, so the bundle size threshold needed to be increased slightly.
> fix: remove unneeded peerbook puts

- README.md
In the context of [libp2p/libp2p#74](https://github.com/libp2p/libp2p/issues/74), the badge for [discuss.libp2p.io](http://discuss.libp2p.io) was added
> chore: add discourse badge

- .aegir.js
- PEER_DISCOVERY.md
- README.md
- package.json
- src/config.js
- src/index.js
- test/config.spec.js
- test/peer-discovery.node.js
- test/transports.browser.js
- test/transports.node.js
- test/utils/bundle-browser.js
- test/utils/bundle-nodejs.js
This PR leverages the strategies detailed at https://github.com/libp2p/js-libp2p/pull/349#issuecomment-480256157 to implement auto dial in libp2p. This should improve our ability to maintain an appropriate level of connections based on the min and max peers configured for the `ConnectionManager`. 
Applications leveraging libp2p should ensure they are not dialing discovered peers when using this update. Applications that do wish to handle all dialing can disable `autoDial` in the config.
Depends on https://github.com/libp2p/js-libp2p-switch/pull/325
> feat: auto dial discovered peers

- src/config.js
- test/config.spec.js
Attempting to configure the switch would throw a config validation error. This corrects that, so the switch can be configured.
> fix: allow switch to be configured

- README.md
- src/config.js
dht config option `enabledDiscovery` is no longer an option and instead discovery is configured via `randomWalk`.
This PR removes the bad references. I did a repo search to make sure there were no more instances of `enabledDiscovery`
> docs: fix incorrect references for enabling dht discovery

- src/config.js
- test/config.spec.js
Right now the dht config is pretty restrictive. `superstruct` doesn't allow for non defined properties to exist. This makes it annoying to add new config options to the dht. For example, if a new option was added to the DHT, `myNewDHTConfigProperty`, and js-ipfs wanted to use that, libp2p would have to be updated to support that config option.
Modules should take care of their own config validation, not libp2p. Libp2p should really only be concerned with validating the things it needs to run.
> fix: dht config

- package.json
- src/pubsub.js
- test/peer-discovery.node.js
This upgrades floodsub so that all messages published are signed
Requires https://github.com/libp2p/js-libp2p-floodsub/pull/78
I ran libp2p/interop against this branch to verify it's passing, https://github.com/libp2p/interop/runs/119819194
> feat: sign pubsub messages

- src/index.js
As discussed [here](https://github.com/libp2p/js-libp2p/issues/361#issuecomment-491229478), transports could benefit from having a reference to the libp2p node on creation (in case the transport depends on perior connections, e.g. webrtc, relay).
As far as I can tell, this change is backwards compatible.
> Instantiate transports with a reference to node

- src/index.js
- test/create.spec.js
`createLibp2p` is a new exported helper function that allows users to create a libp2p instance without worrying about creating a PeerInfo instance first.
Now instead of needing to do this:
```js
const PeerInfo = require('peer-info')
const Libp2p = require('libp2p')
PeerInfo.create((err, peerInfo) => {
const libp2p = new Libp2p({
...options,
peerInfo
}) 
// Use libp2p
})
```
you can just do:
```js
const { createLibp2p } = require('libp2p')
createLibp2p(options, (err, libp2p) => {
// Use libp2p
}) 
```
While the code change is not significant, it removes the need to know about `PeerInfo` creation prior to creating a libp2p instance. This should hopefully help reduce the barrier to entry by a small degree.
I also changed `Node` to `Libp2p` because the naming is unnecessarily confusing and …
> feat: add createLibp2p to generate a PeerInfo instance

- package.json
- test/create.spec.js
I noticed the only keyword being used in package.json was IPFS, so I added some more libp2p specific keywords and also updated the description. The homepage also now points to libp2p.io.
I also reordered a couple other fields in package.json to group them a bit better.
> chore: update keywords and description

- README.md
- package.json
- src/content-routing.js
- src/dht.js
- src/get-peer-info.js
- src/index.js
- src/peer-routing.js
- src/pubsub.js
- test/content-routing.node.js
- test/fsm.spec.js
- test/pubsub.node.js
This is a stop-gap until the full async/await migration can be completed.  It means we can refactor tests of other modules that depend on this module without having to mix async flow control strategies.
N.b. some methods that were previously callable without callbacks (e.g. `node.start()`, `node.stop()`, etc) now require callbacks otherwise a promise is returned which, if rejected, can cause `unhandledPromiseRejection` events and lead to memory leaks where exceptions are thrown and resources are not cleaned up.
> feat: promisify all api methods that accept callbacks

- src/pubsub.js
- test/pubsub.node.js
BREAKING CHANGE: The ipfs interface specified that options
should be provided after the handler, not before.
https://github.com/ipfs/interface-js-ipfs-core/blob/v0.109.0/SPEC/PUBSUB.md#pubsubsubscribe
This corrects the order of parameters. See the jsdocs examples
for subscribe to see how it should be used.
-----
Looking to include this breaking change update in the next libp2p minor release, since we're already making breaking changes to the pubsub api.
> fix: make subscribe comply with ipfs interface

- examples/libp2p-in-the-browser/1/package.json
- examples/libp2p-in-the-browser/1/src/browser-bundle.js
- examples/libp2p-in-the-browser/1/src/create-node.js
- examples/libp2p-in-the-browser/1/src/index.js
- examples/libp2p-in-the-browser/README.md
This cleans up the browser example a bit and also adds the websocket star server as a listening address.
> docs: libp2p in browser example

- package.json
- src/index.js
- test/circuit-relay.node.js
- test/config.spec.js
- test/content-routing.node.js
- test/create.spec.js
- test/fsm.spec.js
- test/peer-discovery.node.js
- test/peer-routing.node.js
- test/pnet.node.js
- test/stream-muxing.node.js
- test/transports.browser.js
https://github.com/libp2p/js-libp2p-kad-dht/pull/137 fixed a bug with how providers were being returned. 
This corrects a test for findProviders to return an error when no providers can be found, rather than just the empty array.
* updates Aegir and fixes linting
> test(fix): correct findProviders test for missing provider

- src/pubsub.js
With #381 and #365 , the gossipsub PR got in after and we did not promisify `start` and `stop`. This PR solves that
> chore: promisify pubsub start and stop

- examples/libp2p-in-the-browser/1/package.json
- examples/libp2p-in-the-browser/1/src/browser-bundle.js
- examples/pubsub/1.js
- src/config.js
- test/config.spec.js
* Also fixes examples for the latest release
The pubsub config was defaulting to `enabled=false`. This makes things a bit annoying since you now have to provide the desired pubsub module in configuration. If we provide the module we shouldn't need to enable it also, it should be enabled by default. If users for some reason want to provide the module but disable it, that should be the override behavior.
> fix: pubsub default config

- src/index.js
Promisify was being run on the libp2p instance methods in the constructor. A side effect of this, is that if you extend libp2p the instance methods are modified. This can create problems for anyone extending libp2p. This corrects that problem by promisifying the class instead of individual instances.
Ref: https://github.com/libp2p/js-libp2p-daemon/pull/19#issuecomment-516868601
> fix: dont override methods of created instance

- package.json
- test/config.spec.js
BREAKING CHANGE: switch configuration has changed.
'blacklistTTL' is now 'denyTTL' and 'blackListAttempts' is now 'denyAttempts'
Aiming to include this in the 0.26 release along with the other breaking changes.
> chore: update switch

- README.md
In the context of `js-libp2p` being a skeleton project, when a new user tries to use this there is a probability of hitting problems, as a consequence of the on going efforts to migrate the codebase to `async`. For instance, if we try to install `libp2p-bootstrap` to use in the bundle, it will use the newest version by default, which is already migrated, taking problems to `js-libp2p`, which still expects callbacks.
This PR adds a note to new users in the README
> docs: async migration

- README.md
- examples/pubsub/1.js
- examples/pubsub/README.md
- src/config.js
- src/index.js
- src/pubsub.js
- test/config.spec.js
- test/pubsub.node.js
This PR fixes issue #401 and adds the following new `pubsub` configuration options:
- `emitSelf` (boolean)
- `signMessages` (boolean)
- `strictSigning` (boolean)
@jacobheun I wasn't sure if I should add tests for this bug fix because it seemed to me that this repository isn't testing if configuration is correctly passed to the Modules. Should I add some tests?
Thanks!
> fix: pubsub configuration

- src/config.js
- test/content-routing.node.js
This applies to the 0.25.x line. I will also create a PR to apply this to the 0.26 line
* Avoids using the superstruct `interface` method, as their recent release of 0.6.2 breaks how we're doing validation. The config is now a bit looser with how it's checking things now. We will migrate away from superstruct in a future PR, https://github.com/libp2p/js-libp2p/issues/406.
* Test updates for content routing were back ported from 0.26 as tests break in 0.25 with their latest releases.
> fix: config validation

- src/get-peer-info.js
- test/get-peer-info.spec.js
The get peer info util consolidation from #400 exposed an issue
with how bad values are being handled. Throwing the error can cause
issues when promises are being used. Rejecting resolves this.
I added a test case to validate the change.
> fix: reject rather than throw in get peer info

- package.json
So as to only pull in libp2p-crypto version with updated `node-forge` dep
> chore: update required libp2p-crypto version

- src/switch/stats/stat.js
Array.shift seems to be very slow, perhaps linear, on some engines, resulting in  _update consuming a lot of CPU.
I transferred a large payload of 2.4GB between two machines running Node 12 on a local network and attached a Chrome profiler which showed a hotspot on the target machine of about 15s in this single line of code (the shift operation). The total transfer time was about 45s.
The CPU consumption was so high that the target machine was not able to consume the stream as new data was received, resulting in the TCP window filling up and causing network congestion. This was at speeds around 60MB/s on a high end MBP.
After this change, the time for the loop was down to about 1s. This might sound like a big improvement but 1s is still a lot for stats that are not important to all …
> fix: performance bottleneck in stat.js

- doc/STREAMING_ITERABLES.md
docs: add iterable types from alanshaw's gist
This adds a new, and the first, example for streaming iterables. I was working on the crypto interface and needed to do this, so sharing it here.
I also pulled over snippets of the iterables types from @alanshaw's gist to avoid being reliant on that always existing, but I made sure to link to it to credit his work.
> docs: add stream wrapping example

- examples/delegated-routing/src/App.js
`ipfs.files.cat` is incorrect. the correct function is `ipfs.cat`
> Fix ipfs cat in delegated routing example 

- src/get-peer-info.js
- src/index.js
- src/transport-manager.js
- src/util/index.js
- test/dialing/direct.node.js
- test/dialing/direct.spec.js
- test/peer-discovery/index.spec.js
This cleans up a few things in the main libp2p file for async.
* Removed the state machine as we really don't need it
* Removed promisify usage
* Ping is currently disabled, that will be refactored in a followup PR
* Autodial is now working with the async code
* `hangUp` now correctly interacts with the registrar to close connections
* `hangUp` now only accepts a PeerId to simplify the api
* Fixed an issue with TransportManager for dial only nodes
> refactor: core async

- README.md
- examples/README.md
- examples/delegated-routing/src/App.js
- examples/echo/src/dialer.js
- examples/echo/src/libp2p-bundle.js
- examples/echo/src/listener.js
- examples/pnet-ipfs/index.js
- examples/pnet-ipfs/libp2p-bundle.js
- examples/pnet-ipfs/package.json
- src/pnet/README.md
- src/switch/stats/stat.js
Note: depends on
- ~fixing [this line](https://github.com/libp2p/js-libp2p/blob/master/src/get-peer-info.js#L41) which is coming in https://github.com/libp2p/js-libp2p/pull/480~
- ~Latest release of [js-libp2p-secio](https://github.com/libp2p/js-libp2p-secio) being deployed to npm~
> async await version of examples/echo

- README.md
- examples/README.md
- examples/chat/src/dialer.js
- examples/chat/src/libp2p-bundle.js
- examples/chat/src/listener.js
- examples/chat/src/stream.js
- examples/delegated-routing/src/App.js
- examples/pnet-ipfs/index.js
- examples/pnet-ipfs/libp2p-bundle.js
- examples/pnet-ipfs/package.json
- src/pnet/README.md
- src/switch/stats/stat.js
Note: depends on
- ~fixing [this line](https://github.com/libp2p/js-libp2p/blob/master/src/get-peer-info.js#L41) which is coming in https://github.com/libp2p/js-libp2p/pull/480~
- ~Latest release of [js-libp2p-secio](https://github.com/libp2p/js-libp2p-secio) being deployed to npm~
> async await version of examples/chat

- src/peer-store/index.js
- test/peer-store/peer-store.spec.js
Aiming to support `base32` peer identifiers as a default in the future, we should support `peer-store` operations with the `peer-id` instance instead of its string representation.
For now I did not deprecate the string representation since we have several modules using it. However, I will create an issue to deprecate it in the future
> feat: peer store operations has, get and remove should support peer id instances

- src/identify/index.js
- src/index.js
- src/peer-store/index.js
- test/dialing/direct.spec.js
- test/identify/index.spec.js
- test/peer-discovery/index.node.js
- test/peer-store/peer-store.spec.js
- test/registrar/registrar.spec.js
* `peerStore.update` no longer replaces existing protocols and multiaddrs, this is inline with PeerBook.
* Identify will now call `peerStore.replace()` instead of `peerStore.update()`. As we are talking directly with the target peer, we should consider them the source of truth. With Multiaddr confidence in the future and PeerStore v2, this may may change.
* All PeerDiscovery `peer` events will now be directed to the peerStore directly.
* `peer:discovery` events are now being Proxied from the PeerStore. This also ensures we won't discover a peer twice.
* `PeerStore.replace()` will always trigger `change:multiaddrs` and `change:protocols` events. This is an oversimplification and may not indicate an actual change, but this is probably better reserved for PeerStore v2 work.
> fix: clean up peer discovery flow

- doc/CONFIGURATION.md
- package.json
- src/index.js
- src/transport-manager.js
- test/peer-discovery/index.spec.js
Discovery modules within Transports automatically added to discovery if enabled
> feat: discovery modules from transports should be added

- doc/API.md
- doc/DIALER.md
- src/circuit/index.js
- src/circuit/listener.js
- src/dialer/dial-request.js
- src/dialer/index.js
- src/index.js
- src/peer-store/index.js
- src/registrar.js
- src/upgrader.js
- test/dialing/direct.node.js
- test/dialing/direct.spec.js
- test/dialing/relay.node.js
- test/identify/index.spec.js
- test/peer-store/peer-store.spec.js
* Parallel dials to the same peer / multiaddr will now settle at the same time with the same result
* Removed `connectToMultiaddr`, all dials now go directly through `connectToPeer`
* Fixed an issue with closed inbound connections not getting removed from tracking
* `PeerStore.put` now allows you to update a peer without firing the `peer` event. This helps prevent duplicate dialing when dialing a new multiaddr directly. (For example: `ipfs swarm connect [addr]`)
> feat: coalescing dial support

- src/upgrader.js
- test/upgrading/upgrader.spec.js
With the current codebase, having a `streamMuxer` is mandatory, which was not the case before. This PR allows a connection to be upgraded just with crypto.
Note: the `connection` properties regarding multiplexers are throwing an error now.
> fix: upgrader should not need muxers

- doc/API.md
- doc/CONFIGURATION.md
- src/config.js
- src/constants.js
- src/index.js
- test/dialing/direct.spec.js
docs: update configuration and api docs
This exposes the Dialer configuration options. A few of the other config options were missing from the API doc so I've added them as well
> fix: make dialer configurable

- doc/API.md
- src/index.js
- test/dialing/direct.node.js
- test/registrar/registrar.node.js
* Adds `libp2p.connections` getter to allow users to more easily get existing connections.
* Fixes `libp2p.hangUp(peer)` to take arguments that the API doc specifies.
> feat: add libp2p.connections getter

- examples/pubsub/1.js
- examples/pubsub/README.md
This PR refactors the `pubsub` example to the refactored async `js-libp2p`.
Needs:
> refactor: examples pubsub

- examples/peer-and-content-routing/1.js
- examples/peer-and-content-routing/2.js
- examples/peer-and-content-routing/README.md
This PR refactors the `peer-and-content-routing` example to the refactored async `js-libp2p`.
Needs:
> refactor: examples/peer-and-content-routing

- doc/GETTING_STARTED.md
This PR is to supplement review of #514
> docs: review getting started

- doc/CONFIGURATION.md
- src/config.js
- src/index.js
- src/transport-manager.js
- test/transports/transport-manager.spec.js
This allows custom options to be passed along to transport creation, in addition to `libp2p` and an `Upgrader` being passed. This is needed for things like passing a custom WebRTC instance to the WebRTC based transports.
I also added the check for the enabled relay before adding the Circuit transport.
> feat: allow transport options to be passed on creation

- examples/protocol-and-stream-muxing/1.js
- examples/protocol-and-stream-muxing/2.js
- examples/protocol-and-stream-muxing/3.js
- examples/protocol-and-stream-muxing/README.md
This PR refactors the `protocol-and-stream-muxing` example to the refactored async `js-libp2p`.
Needs:
> refactor: examples/protocol-and-stream-muxing

- package.json
- src/connection-manager/index.js
Fixes the case when options are passed with `maxConnections` and/or `minConnections` set to `undefined`:
```js
{
defaultOptions: {
maxConnections: Infinity,
minConnections: 0,
maxData: Infinity,
maxSentData: Infinity,
maxReceivedData: Infinity,
maxEventLoopDelay: Infinity,
pollInterval: 2000,
movingAverageInterval: 60000,
defaultPeerValue: 1
},
options: {
minPeers: 25,
maxConnections: undefined,
minConnections: undefined
}
}
// These are the values this._options ends up with:
{ maxConnections: undefined, minConnections: undefined }
```
```console
1) "before all" hook in "custom config"
(node:67176) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Connection Manager maxConnections must be greater than minConnections
at new ConnectionManager …
```
> fix: conn mngr min/max connection values

- examples/discovery-mechanisms/1.js
- examples/discovery-mechanisms/2.js
- examples/discovery-mechanisms/README.md
This PR refactors the `discovery-mechanisms` example to the refactored async `js-libp2p`.
Needs:
> refactor: examples/discovery-mechanisms

- examples/transports/1.js
- examples/transports/2.js
- examples/transports/3.js
- examples/transports/README.md
This PR refactors the `transports` example to the refactored async `js-libp2p`.
Needs:
> refactor: examples transports

- src/registrar.js
- test/registrar/registrar.spec.js
- test/registrar/utils.js
Noticed this bug on interop tests after #518 got merged. Connections were being lost and pubsub tests were hanging
> fix: registrar should filter the disconnected conn

- package.json
- src/connection-manager/index.js
- src/dialer/index.js
- src/identify/index.js
- src/index.js
- src/metrics/index.js
- src/registrar.js
- src/upgrader.js
- test/connection-manager/index.spec.js
- test/dialing/direct.node.js
- test/dialing/relay.node.js
- test/identify/index.spec.js
- test/metrics/index.spec.js
- test/registrar/registrar.spec.js
We will be doing a full switch over to base32 PeerId strings at a later date. This PR updates everything in the async refactor to use Base58 PeerId strings until we perform that migration.
* I also bumped a couple dependencies
Resolves https://github.com/libp2p/js-libp2p/issues/536
> fix: use toB58String everywhere to be consistent

- README.md
- doc/API.md
- doc/CONFIGURATION.md
- doc/GETTING_STARTED.md
This getting started doc aims to be the entry point for new users of `js-libp2p` since it goes deeper in detail within each concept.
For more advanced users, we expect that they consult the API and CONFIG docs mostly, as they are more straightforward documents
> docs: getting started

- doc/API.md
Fixes a few broken links and inconsistent use of backticks
> docs: fix api link formatting

- doc/migrations/v0.26-v0.27.md
This adds a basic migration guide from 0.26.x to 0.27.
> docs: add migration guide from 0.26 to 0.27

- src/ping/index.js
- test/core/ping.node.js
When connecting to go-IPFS from a webworker, the stream opened by the ping protocol is never closed.
The change here uses `take` to only receive one buffer from the remote node before closing the stream.
> fix: stop stream after first pong received

- src/identify/index.js
- src/upgrader.js
- test/identify/index.spec.js
- Identify streams were not being closed properly. They were either being only read from or written to, which would lave them half open. This adds tests to check for open streams after identify runs and fixes it for both identify and identify push.
- `connection.addStream()` wasn't being called properly in the Upgrader. This resulted in protocols being tracked as `undefined`. It was also tracking the multistream selected stream, instead of the MuxedStream. The call now matches the connection interface https://github.com/libp2p/js-interfaces/tree/master/src/connection#add-stream-metadata.
> fix: ensure identify streams are closed

- ISSUE_TEMPLATE.md
The issue template is currently mentioning ipfs instead of libp2p
> chore: issue template mentioning js-libp2p

- test/peer-discovery/index.node.js
The test previously had each of the 3 peers running random walk, and started the local libp2p node after the connections were made.
This isolates the random walking to only the local node to ensure it is the only node performing active discovery.
Resolves https://github.com/libp2p/js-libp2p/issues/560
> fix(test): improve flakey random walk discovery test

- examples/delegated-routing/README.md
The `delegated-routing` is currently not functional. Aiming to not make `js-libp2p` users try to run it and spend time trying to figure out what is going on, I created this PR.
This adds a notice on the `delegated-routing` as it is still not working with the new version. I linked the PR where it is being worked on [libp2p/js-libp2p#507](https://github.com/libp2p/js-libp2p/pull/507)
> chore: add outdated notice on wip delegated-routing-example

- src/index.js
Fixes #595 
Multiple export statements can cause issues with downstream modules, this resolves that by extending create from Libp2p and only exporting Libp2p.
cc: @svdo
> fix: only use a single export

- src/index.js
- src/peer-store/index.js
- test/peer-store/peer-store.spec.js
This adds support for passing libp2p to discovery services when creating them which makes it easier for discovery services to extend the behavior of other libp2p systems. This is value for discovery systems that may wish to use systems such as pubsub.
**Additional fix**
There was also an issue where a peers relay addresses were not being properly returned. This was due to the fact that `PeerStore.multiaddrsForPeer` was not checking the PeerId contained in the address. When we are listening on a relay we will have the PeerId of that relay in the address, so we should check to verify that the peerid in the multiaddr is not ours before returning.
> fix: pass libp2p to discovery services

- src/index.js
`_setupPeerDiscovery` returns a `Promise` that resolves after all discovery modules are started.
Because we are not awaiting `_setupPeerDiscovery` in the call to `libp2p.start`, we run into a situation where underlying discovery modules have not been started until after the top-level `start` has resolved.
This can lead to unintended behavior where discovery modules may be started after the libp2p instance has been stopped.
eg:
```typescript
async function startStopNode() {
const node = createLibp2pWithDiscoveryModules();
await node.start();
// after ^ statement, the libp2p instance has started
// but the discovery modules haven't, the `d.start()` calls are in a promise that hasn't been executed yet
await node.stop();
// after ^ statement, the libp2p instance has stopped
// and each …
```
> fix: await peer discovery start in libp2p start

- src/index.js
- test/peer-discovery/index.spec.js
Fixes a browser test issue exposed by https://github.com/libp2p/js-libp2p/pull/600.
Also makes `_setupPeerDiscovery` consistent with other methods by making it async instead of returning the promise.
> test: dont use mdns in browser tests

- doc/API.md
- src/dialer/index.js
- src/get-peer-info.js
- src/identify/index.js
- src/index.js
- src/peer-store/README.md
- src/peer-store/address-book.js
- src/peer-store/book.js
- src/peer-store/index.js
- src/peer-store/proto-book.js
- src/ping/index.js
- src/registrar.js
- src/upgrader.js
- test/content-routing/dht/operation.node.js
- test/dialing/direct.node.js
- test/dialing/direct.spec.js
- test/dialing/relay.node.js
- test/identify/index.spec.js
- test/peer-discovery/index.spec.js
- test/peer-store/address-book.spec.js
- test/peer-store/peer-store.spec.js
- test/peer-store/proto-book.spec.js
- test/registrar/registrar.spec.js
This is the initial milestone regarding `js-libp2p` PeerStore improvements described on [libp2p/js-libp2p#582](https://github.com/libp2p/js-libp2p/issues/582)
This PR restructures the initial version of `peerStore`, where we simply had a record of PeerInfos into data structures with different concerns and own logic.
We will start by introducing the `AddressBook` and `ProtoBook` since this was the content being used from the PeerInfos previously stored. In next PRs we will add other "books", namely the keybook and metadata book.
- identifyService
- pushToPeerStore - identify push (on libp2p.handle, libp2p.unhandle)
- iterate peerStore peers, can iterate on ProtoBook instead?
- After identify, **replace** peer's data
- After handle push message, **replace** peer's data
- Upgrader: …
> feat: address and proto books

- src/circuit/listener.js
- test/content-routing/content-routing.node.js
- test/dialing/relay.node.js
- test/peer-routing/peer-routing.node.js
* Makes the delegate tests less restrictive, we don't need to mock the query params, validation should be done in the modules themselves. This should make libp2p tests more resilient to non breaking, additive changes.
This makes setting a relay address a bit more lenient. You can now use:
```
/p2p-circuit/ip4/0.0.0.0/tcp/9090/p2p/QmRelay
// or
/ip4/0.0.0.0/tcp/9090/p2p/QmRelay/p2p-circuit
```
You could previously only do the former. Both will result in the same announced address: `/ip4/0.0.0.0/tcp/9090/p2p/QmRelay/p2p-circuit/p2p/QmOurId`
> fix: make circuit relay listening addresses more forgiving

- doc/API.md
- package.json
- src/content-routing.js
- src/index.js
- src/peer-store/README.md
- src/peer-store/address-book.js
- src/peer-store/index.js
- test/peer-routing/peer-routing.node.js
- test/peer-store/address-book.spec.js
- test/peer-store/peer-store.spec.js
Per [libp2p/js-libp2p#610](https://github.com/libp2p/js-libp2p/pull/610) review, we are renaming `MultiaddrInfo` into `Address`, and `peerStore.get` return value from `PeerData` into `peer` with an `addresses` property instead of `multiaddrInfos`.
This needs:
> chore: rename peer-store properties

- src/index.js
Clear `libp2p._discovery` upon `libp2p.start()` in order to avoid lingering modules.
An alternative would be to initialize once (without starting) and call `service.start/stop` in conjunction with `libp2p.start/stop`. Let me know, happy to alter if so.
> Clear old discovery modules upon reconnect

- doc/API.md
- doc/CONFIGURATION.md
- doc/GETTING_STARTED.md
- package.json
- src/address-manager/README.md
- src/address-manager/index.js
- src/circuit/index.js
- src/config.js
- src/identify/index.js
- src/index.js
- src/transport-manager.js
- test/addresses/address-manager.spec.js
- test/addresses/addresses.node.js
- test/addresses/utils.js
- test/core/listening.node.js
- test/core/ping.node.js
- test/dialing/direct.node.js
- test/dialing/relay.node.js
- test/identify/index.spec.js
- test/peer-discovery/index.node.js
- test/pubsub/implementations.node.js
- test/pubsub/operation.node.js
- test/transports/transport-manager.node.js
- test/transports/transport-manager.spec.js
- test/utils/creators/peer.js
This PR adds an Address Management component. This component aims to allow users to add to the libp2p configuration `{ listen, announce, noAnnounce }` addresses.
These addresses will be used by each subsystem according to their needs. The details for the reasoning for these addresses are detailed on `/src/address-manager/README.md`, which should be read in this branch (last commit)
Needs:
Closes #202 
Depends on:
> feat: address management

- README.md
I've been effectively not contributing as Tech Lead for a several months now, so not worth having my name there and mislead folks.
I see this is a natural transition, specially after all the great work from @jacobheun and @vasco-santos as the Lead Maintainers of the entire set of libp2p modules. You've made the project so much better, thank you for taking really great care of it, as you can imagine, it means a lot to me ❤️
> docs: remove Tech Lead from README

- package.json
`wrtc` dev dependency is not needed anympre
> chore: remove wrtc devdep

- package.json
- src/index.js
- test/connection-manager/index.node.js
- test/content-routing/dht/configuration.node.js
- test/content-routing/dht/operation.node.js
- test/core/listening.node.js
- test/dialing/relay.node.js
After #611 registrar does not keep the connections anymore. This introduced a bug that was not covered in the tests, which is the `libp2p.connections` getter. This getter was using the older `connections` property from the registrar.
This PR fixes the above issue, adds a test for it and removes redundant `multiaddr` creation on a few tests.
> fix: libp2p connections getter

- doc/API.md
- package.json
- src/connection-manager/index.js
- src/peer-store/README.md
- src/peer-store/address-book.js
- src/peer-store/book.js
- src/peer-store/index.js
- src/peer-store/key-book.js
- src/peer-store/persistent/consts.js
- src/peer-store/persistent/index.js
- test/identify/index.spec.js
- test/peer-store/key-book.spec.js
- test/peer-store/peer-store.node.js
- test/peer-store/peer-store.spec.js
- test/peer-store/persisted-peer-store.spec.js
This PR is part of the [PeerStore improvements EPIC](https://github.com/libp2p/js-libp2p/issues/582) and tackles part of the milestone 4 - [KeyBook](https://github.com/libp2p/js-libp2p/issues/591).
As a follow up of the work in #590, #598, #610 and #619 , this PR adds they KeyBook and integrates it with the `PeerStorePersistence`.
Needs:
> feat: keybook

- src/connection-manager/index.js
- test/identify/index.spec.js
- test/peer-store/peer-store.node.js
On the `KeyBook` PR, I added in the `onConnect` handler the addr of the connection to the addressBook and the public key to the keyBook.
I realised when updating the libp2p-daemon PR that this is not correct! This is adding to the addressBook the multiaddr with the port where the connection between these 2 nodes is established, not the listening multiaddr of the peer. This is problematic because the DHT will provide these multiaddrs in the `findProviders` / `findPeer`.
The correct multiaddrs will be added once the identifyService finishes
> fix: onConnect should not add addr to the addressBook

- src/peer-store/README.md
As a follow up PR from #590 , more specific on this review comment: https://github.com/libp2p/js-libp2p/pull/590#discussion_r406099716 the writing format for the use cases when peer store records are submitted and retrieved is changed
> chore: rewrite peer-store submit and retrieve docs

- package.json
- test/peer-store/peer-store.node.js
This got pending on a `noise` update after #626 got merged.
> chore: uncomment local peer public key after connect test

- doc/migrations/v0.26-v0.27.md
- doc/migrations/v0.27-v.28.md
This PR adds the migration guide from `libp2p@0.27.x` to `libp2p@0.28`
> docs: migration 0.27 to 0.28

- doc/API.md
- src/peer-store/README.md
- src/peer-store/address-book.js
- src/peer-store/index.js
- src/peer-store/metadata-book.js
- src/peer-store/persistent/consts.js
- src/peer-store/persistent/index.js
- src/peer-store/proto-book.js
- test/peer-store/metadata-book.spec.js
- test/peer-store/peer-store.spec.js
- test/peer-store/persisted-peer-store.spec.js
This PR adds the metadataBook to the PeerStore as described in #627 
Closes #627
> feat: metadata book

- doc/API.md
Just a tiny thing I noticed browsing the 0.28.x branch on github
> chore: fix api formatting

- README.md
As discussed offline, the libp2p migration guides are quite recent for `js-libp2p`. Aiming for better visibility for them, I added a reference in the Readme.
Also updated the outdated weekly meetings link and added the a Getting started reference.
> chore: add readme reference to migrations

- doc/API.md
- doc/CONFIGURATION.md
- src/config.js
- src/index.js
- src/transport-manager.js
- test/transports/transport-manager.spec.js
This PR allows libp2p users to support dial only mode, which will make transport manager tolerate errors, if none of the multiaddrs provided were successful used for listening on the configured transports.
We can also have this in the `addresses` configuration, but I preferred to have it assigned to the correct component. Moreover, I default this to the current behaviour but I do not have a strong opinion if we should go this way, or invert the logic. Let me know your thoughts
Closes #575
> feat: support dial only on transport manager to tolerate errors

- src/upgrader.js
- test/upgrading/upgrader.spec.js
Inbound streams aren't exposing the muxed stream interface (id, timeline, close, etc). Outbound streams are already doing this.
> fix: expose the muxed stream interface on inbound streams

- src/connection-manager/index.js
This is a bit noisy but matches the current behavior of 0.27. The problem with only emitting the first connection is that a parallel dial to a peer may result in the first connection being closed by the dialer. This would cause identify to fail and never be run again for the peer.
We should attempt to reduce the noise in the future and be more intelligent with the notifications, but that might be best to do during the connection manager overhaul.
> fix: always emit when a connection is made

- package.json
Per `libp2p@0.28` release and [libp2p/interop#36](https://github.com/libp2p/interop/pull/36) merged, we can now use its new version instead of relying in the branch
> chore: use interop release

- src/connection-manager/index.js
The implementation is _almost_ identical to `ConnectionManager#get` except instead of returning the first open connection or null, `getAll` returns an array of _all_ open connections (or an empty array).
Perhaps `get` could be refactored to use `getAll` to avoid code duplication?
Open to any suggestions, naming, implementation, otherwise
See https://github.com/ChainSafe/js-libp2p-gossipsub/pull/83#discussion_r437279222
> feat: add ConnectionManager#getAll

- RELEASE.md
We should add this to avoid leaving the libp2p docs website outdated
> chore: add libp2p docs website to release checklist

- src/identify/index.js
- src/metrics/index.js
- src/pnet/index.js
- src/upgrader.js
There were some pipe errors not being caught. This can result in unhandled exceptions being thrown.
While working on replicating https://github.com/libp2p/js-libp2p-tcp/issues/130 I noticed that we aren't catching all errors that can be thrown by `pipe`, which includes tcp reset errors. 
related: https://github.com/libp2p/js-libp2p-mplex/issues/111
> fix: catch pipe errors

- examples/libp2p-in-the-browser/README.md
- examples/libp2p-in-the-browser/index.js
- examples/libp2p-in-the-browser/package.json
Adds back public servers to the browser example to ease experimenting with the examples with less things to run
> chore: libp2p in the browser using webrtc servers

- doc/STREAMING_ITERABLES.md
You can confirm the link at npm https://www.npmjs.com/package/streaming-iterables
> Fix link to streaming-iterables' repo

- doc/CONFIGURATION.md
Links were pointing to the pre monorepo structure of ipfs.
> docs(fix): update link to ipfs config files

- doc/migrations/v0.27-v.28.md
Adding modules to update in the `0.28.x` release per #694
> chore: add modules to update in 0.28.x migration

- examples/discovery-mechanisms/README.md
In the discussion this was proposed as a solution to my problem with not knowing how to enable the DHT for peer discovery. https://discuss.libp2p.io/t/usage-example-of-dht-random-walk-for-discovery/583/2
The link to the docs helped me to configure it.
Extended the description with a link for how to configure the libp2p-kad-dht for peer discovery.
> Add documentations reference

- src/index.js
The DHT needs to be able to get its addresses for provide calls. This change passes libp2p itself to the DHT which is ideal, as we can get rid of all the subcomponents. To avoid the breaking change I am not removing the other components right now, but we should do this in 0.29.
> fix: pass libp2p to the dht

- src/identify/index.js
- src/metrics/index.js
- src/pnet/index.js
- src/upgrader.js
- test/metrics/index.node.js
This is a port of fixed in https://github.com/libp2p/js-libp2p/pull/678 for 0.27.x.
The metrics sink wrapper was not returning the wrapper which causes `sink()` to be undefined instead of a promise.
fixes: https://github.com/libp2p/js-libp2p/issues/694
> fix: back port #678 to catch pipe errors

- .aegir.js
- doc/CONFIGURATION.md
- doc/GETTING_STARTED.md
- src/config.js
- src/connection-manager/index.js
- src/index.js
- test/connection-manager/index.node.js
- test/connection-manager/index.spec.js
- test/peer-discovery/index.spec.js
This PR aims to block large numbers of dials on a peer restart, if this peer already new a large number of peers in the past.
It checks the `minPeers` as the `maybeConnect` function used by the discovery event handlers. This was also using the `minPeers`, but as all the dials were put in parallel, the `connectionManager.size` would not be updated to avoid further dials.
When we work on connectionManager, we should work on better strategies for this, and likely have them as configurable
> fix: not dial all known peers in parallel on startup

- src/connection-manager/index.js
- src/metrics/stats.js
`retimer` reschedule is not an `interval` feature but a "delay" of a previously defined interval. This PR fixes it
> fix: retimer reschedule does not work as interval

- MIGRATION_TEMPLATE.md
Per suggestion on https://github.com/libp2p/js-libp2p/pull/695#issuecomment-655482342 this PR adds a migration guide template.
Its goal is to create a consistent structure for this document to ease the life of users migrating and also to guarantee that we do not miss important things like the modules to update. Other points might be added in the future
> chore: add migration guide template

- doc/CONFIGURATION.md
To avoid confusions like we previously had. This was not fixed at the time
> docs: use tag for webrtc-star discovery config

- src/dialer/index.js
- test/dialing/direct.node.js
This PR fixes `_createDialTarget` dialer function to return an empty array of multiaddrs if there are no known multiaddrs for the target peer.
Closes #673 and #714
> fix: create dial target for peer with no known addrs

- .aegir.js
- doc/API.md
- src/identify/index.js
- src/index.js
- src/peer-store/address-book.js
- src/peer-store/index.js
- src/peer-store/persistent/index.js
- src/peer-store/persistent/pb/address-book.proto.js
- src/record/envelope/index.js
- test/dialing/direct.node.js
- test/dialing/direct.spec.js
- test/identify/index.spec.js
- test/peer-store/address-book.spec.js
- test/peer-store/key-book.spec.js
- test/peer-store/metadata-book.spec.js
- test/peer-store/peer-store.spec.js
- test/peer-store/persisted-peer-store.spec.js
- test/peer-store/proto-book.spec.js
- test/registrar/registrar.spec.js
This PR adds the signed peer records in the AddressBook as part of #653 
Remaining:
Needs:
The protobuf definition for persistence was inspired (copied) from go-libp2p, and the API to consume and get the records was inspired on go-libp2p CertifiedAddressBook [interface](https://github.com/libp2p/go-libp2p-core/blob/master/peerstore/peerstore.go#L147).
---
The AddressBook was previously holding `Map<string, Array<Address>>`, which mapped a peer id string identifier to an Array of Address (object with multiaddr property). It was changed to `Map<string, Array<Entry>>`, where the Entry is an object containing `{ addresses: Array<Address>, record: { raw: Buffer, seqNumber: number} }`. The Address now also includes a `isCertified` property that aims to allow subsystems to filter known …
> feat: certified addressbook

- src/index.js
- src/ping/index.js
- test/core/ping.node.js
When we try to ping using a multiaddr, under the hood we were trying to ping using the peer id but the address was not stored.
I added support for pinging using the multiaddr instead of adding the multiaddr to the addressBook because otherwise the ping could be done to a different multiaddr as a consequence of the parallel dials.
Context: https://discuss.libp2p.io/t/examples-failing-help-new-to-libp2p/620
> fix: ping multiaddr from peer not previously stored in peerstore

- doc/production/DELEGATE_NODES.md
- examples/delegated-routing/README.md
Patch for https://github.com/libp2p/js-libp2p/pull/718, aiming to cover SSL setup for `go-ipfs`, et.al `libp2p` nodes.
> ♻️  Additional notes on production guides

- src/identify/consts.js
- src/identify/index.js
- test/identify/index.spec.js
The AgentVersion in identify shouldn't be static. In go-libp2p the AgentVersion is generated by the application name and version, so for go-ipfs this looks like `go-ipfs/<version>`. Ideally we would replicate this, however this is a trickier to handle in JS as we need to account for browser usage. At the very least we need to default to the js-libp2p version, so this adds that basic level of support.
This is extremely helpful for understanding what versions are being used on the network, which helps us when determining upgrade strategies and change rollouts on the network.
go-libp2p also tracks the AgentVersion of peers in the metadata book, so I added that here as well, which is necessary for actually checking this data (we were previously ignoring this).
> fix(identify): make agentversion dynamic and add it to the peerstore

- doc/API.md
- package.json
- src/keychain/index.js
- test/keychain/keychain.spec.js
Adds support in the keychain for ed25519 and secp256k1 keys.
unblocks https://github.com/libp2p/js-libp2p/issues/669
unblocks usage of these keys in js-ipfs and any other apps leveraging the keychain
> feat(keychain): add support for ed25519 and secp keys

- README.md
Just noticed that we have node and npm badges outdated in the README
> chore: update node and npm badges

- src/index.js
- src/keychain/index.js
- test/keychain/keychain.spec.js
Listing, removing, renaming etc keys do not require a password so
the user should not be required to provide one.
This means we don't have to prompt the user to create a password
when they aren't going to do any operations that require a password.
> fix: allow certain keychain operations without a password

- package.json
Updates interop with latest `go-libp2p` and `js-libp2p-daemon` updated
> chore: update interop version

- test/pubsub/operation.node.js
The pubsub test `should handle quick reconnects with a delayed disconnect` was failing sometimes, mostly in linux. The test would timeout waiting for `await pWaitFor(() => handlerSpy.callCount === 2)`. In these cases, the `handlerSpy.callCount` was 1 and only `libp2p` (who triggered the connection close) would receive the message.
I added to the test a validation that waits for the other party to be notified of the connection close before publishing more pubsub messages. It checks if the connections map was updated by the connection manager as a result of the disconnect
Closes #709
> fix: pubsub intermittent test

- doc/API.md
- doc/CONFIGURATION.md
- doc/GETTING_STARTED.md
As we announced that we're removing support for the SECIO security transport, I removed its usage from the documentation, so that new users do not use it.
When we official deprecate it, we should remove it from the `CONFIGURATION.md` + Packages table and remove it as a fallback in the examples.
> chore: update docs after secio deprecation announcement

- RELEASE.md
We did not update `libp2p-examples` with the uint8array refactor.
I suggest that we add that task in our release process to avoid having inconsistencies between the latest `js-libp2p` and what is in `libp2p-examples#master`. Meanwhile, I will update the `libp2p-examples` with the latest release.
> chore: add libp2p-examples repo to release checklist

- doc/GETTING_STARTED.md
- examples/libp2p-in-the-browser/index.js
The getting started document was not totally updated when we released `0.28` and the connect event was not changed per https://github.com/libp2p/js-libp2p/blob/master/doc/migrations/v0.27-v0.28.md#events
Morever, `[Bootstrap.tag]` is now used in the browser example to be consistent and avoid confusions.
Closes #750
> chore: update getting started connect event

- doc/migrations/v0.28-v0.29.md
Added a point in `pubsubs.subscribe` about subscribing to multiple topics.
While we did not have any documentation for it in the past, people can be using it, as it was happening on https://github.com/ipfs/js-ipfs/issues/3282
> chore: complement 0.29 migration for pubsub subscribe

- doc/API.md
- src/circuit/auto-relay.js
- src/circuit/listener.js
- src/identify/index.js
- src/index.js
- src/record/utils.js
- src/transport-manager.js
- test/dialing/direct.node.js
- test/dialing/direct.spec.js
- test/identify/index.spec.js
- test/relay/auto-relay.node.js
- test/transports/transport-manager.node.js
This PR is a follow up of the [main implementation](https://github.com/libp2p/js-libp2p/pull/723) of auto relay to inform the connected peers of the new addresses to announce, by sending the new signed peer record via `identify-push`.
The self peer record update logic was added to create the new record, when the multiaddr changes. Ping unmount needed to be modified to before the transports close, otherwise when the ping unhandle protocol is triggered, the `identify-push` will try to access the addresses when they do not exist, causing unhandled exceptions, such as https://github.com/libp2p/js-libp2p-tcp/blob/v0.15.1/src/listener.js#L97
When we support dynamic transport updates, we should automate the self peer record update based on events for updated addresses. This will enable us to not …
> chore: auto relay multiaddr update push

- src/index.js
These events were moved to the connectionManager, but their docs were not removed
> chore: remove outdated events from libp2p js docs

- doc/CONFIGURATION.md
- examples/chat/src/libp2p-bundle.js
- examples/chat/src/listener.js
- examples/chat/src/stream.js
- examples/discovery-mechanisms/1.js
- examples/discovery-mechanisms/2.js
- examples/discovery-mechanisms/README.md
- examples/echo/src/libp2p-bundle.js
- examples/encrypted-communications/1.js
- examples/encrypted-communications/README.md
- examples/libp2p-in-the-browser/index.js
- examples/libp2p-in-the-browser/package.json
- examples/peer-and-content-routing/1.js
- examples/peer-and-content-routing/2.js
- examples/peer-and-content-routing/README.md
- examples/pnet/libp2p-node.js
- examples/protocol-and-stream-muxing/1.js
- examples/protocol-and-stream-muxing/2.js
- examples/protocol-and-stream-muxing/3.js
- examples/pubsub/1.js
- examples/pubsub/README.md
- examples/pubsub/message-filtering/1.js
- examples/pubsub/message-filtering/README.md
- examples/transports/1.js
- examples/transports/2.js
- examples/transports/3.js
- examples/transports/README.md
- src/circuit/README.md
As we announced that we're removing support for the SECIO security transport, this PR removes its usages from the examples per https://github.com/libp2p/js-libp2p/pull/745#pullrequestreview-484066297
> chore: examples not using secio

- README.md
We missed updating the badge when dropping node 10 tests in https://github.com/libp2p/js-libp2p/commit/098f3d1dd36ae8e069af3e00f366abd8ce44a295
> chore: update node badge

- doc/API.md
Adds missing links in the table of contents to the `pubsub.topicValidators.set` and `pubsub.topicValidators.delete` properties within API.md
> doc(pubsub): add topicValidators links in API.md table of contents

- examples/transports/1.js
- examples/transports/2.js
- examples/transports/3.js
- examples/transports/README.md
The transport example said to install `peer-info`but `npm` ended up complaining about the [package being deprecated](https://www.npmjs.com/package/peer-info). It turns out that the example never used this dependency and instead opted in to using the PeerStore. Thus this PR removes the instruction to install `peer-info`. Additionally, some of the code snippets in the document did not match the full solution. In particular, section 2 had code that printed the stream data in a way that causes the output to not match the final output given. For the sake of consistency, this PR updated the snippets to match the code in the corresponding solution files. The desynchronization also led to issues where I would follow the example but not have the code work properly. Notably, I had an issue in …
> Edited transport example

- .travis.yml
- package.json
- src/upgrader.js
- test/dialing/direct.node.js
This patch ensures that whenever a connection is closed, any remaining streams on the connection are aborted.
> fix: ensure streams are closed on connection close

- src/upgrader.js
Ensures any remaining streams are closed when the connection shuts down. This was discovered during testing of https://github.com/ChainSafe/lodestar.
Shouldn't be needed when https://github.com/libp2p/js-libp2p-interfaces/pull/67 is completed, but that won't land until 0.30.
> fix: cleanup open streams on conn close

- doc/API.md
- src/identify/index.js
- src/index.js
- src/peer-store/proto-book.js
- test/identify/index.spec.js
- test/peer-store/proto-book.spec.js
This PR stores the self protocols in the Protobook on `handle`/`unhandle`.
This allows the identify service to be consistent, by tracking self protocols change in the same way as #748 does for multiaddrs.
`Protobook.remove` API method was added for the unhandle.
Needs:
> chore: store self protocols in protobook

- doc/GETTING_STARTED.md
- examples/libp2p-in-the-browser/index.js
This updates the docs to point to new(er) bootstrap nodes. Infra would like to decouple how we announce bootstrap records so that the datacenter (`ams-1`, `lon-1`) is not strictly tied to a peer id (`QmSol...`).
These new examples are using servers on different continents, instead of both being EU-based.
> Update example multiaddrs of boostrap nodes

- doc/CONFIGURATION.md
- doc/GETTING_STARTED.md
- examples/libp2p-in-the-browser/index.js
- package.json
- src/config.js
- src/dialer/index.js
- src/index.js
- test/dialing/direct.node.js
- test/dialing/direct.spec.js
- test/dialing/resolver.spec.js
This PR adds the ability to resolve multiaddrs before dialling. The multiaddr resolvers are customizable within the dialer configuration and come with a default for `dnsaddr`. At this moment, we do not resolve `dns4` and `dns6` per https://github.com/libp2p/js-libp2p/pull/772#issuecomment-707164483 . I will make sure to create an issue to track this.
Needs:
> feat: resolve multiaddrs before dial

- doc/API.md
- src/config.js
- src/identify/index.js
- test/identify/index.spec.js
This PR adds the ability to custom the agentVersion of libp2p, as well as to store it and the protocol version self values in the metadataBook.
I added a host property to track this custom options. `go-libp2p` also has the concept of host and it seems a good naming. When we work on the configuration improvements, we should probably think about moving other options inside the host, such as the AddressBook options.
I followed the same logic of signedPeerRecords being created in the IdentifyService and added this into the Identify subsystem.
Closes #799
> feat: custom and store self agent version + store self protocol version

- package.json
- test/dialing/direct.spec.js
- test/dialing/resolver.spec.js
- test/transports/transport-manager.spec.js
- test/utils/base-options.browser.js
This PR updates websockets version, which comes with a BREAKING CHANGE on the filter. Only DNS+WSS addresses are now returned on filter by default in the browser. The tests were update to pass a custom filter so that we can test this locally with loopback websocket addresses
Needs:
> chore: update websockets

- doc/API.md
- doc/CONFIGURATION.md
- package.json
- src/config.js
- src/index.js
- src/peer-routing.js
- test/peer-routing/peer-routing.node.js
This PR adds a peer routing service to discover closest peers recurrently over time. The discovered addresses will be added to the AddressBook and the peers will be dialled if the autoDial is enabled and the connectionManager threshold is not reached. This will enable peers to better advertise themselves on the network as their closest peers will have their address records. 
Following up this PR, we should work on maintaining connections to our closest peers, as they will get push notifications whenever address changes occur. Further optimisations might be done, like trigger a find task when the announce addresses change. Keeping connections and more proactive connections should probably come together with connection manager overhaul as we need to implement dial strategies that can be …
> feat: discover and connect to closest peers

- package.json
- src/circuit/index.js
This PR makes circuit to use `set-delayed-interval` module per https://github.com/libp2p/js-libp2p/pull/798#discussion_r521950167
> chore: use set-delayed-interval module on circuit

- doc/API.md
- examples/chat/src/dialer.js
- examples/chat/src/libp2p-bundle.js
- examples/chat/src/listener.js
- examples/echo/src/dialer.js
- examples/echo/src/libp2p-bundle.js
- examples/echo/src/listener.js
I didn't changed the use of `new Libp2p()` in the `examples/delegated-routing` directory because this is already in progress in PR #507
https://github.com/libp2p/js-libp2p/blob/d0a9fada32677ee3b810d5c2fb8d5e2c4f5a9fef/examples/delegated-routing/src/libp2p-bundle.js#L23-L30
> docs: use Libp2p.create() in examples (#811)

- examples/pubsub/1.js
- examples/pubsub/README.md
- examples/pubsub/message-filtering/1.js
- examples/pubsub/message-filtering/README.md
This updates the pubsub examples docs to the new default emitSelf: false.
> chore: update pubsub example by disabled emit self

- doc/production/CIRCUIT_RELAY.md
- doc/production/DELEGATE_NODES.md
- doc/production/README.md
These were started in #718, but doing all of them in the same PR will just get things blocked longer. So, this PR is the first of a set of PRs that should land over time. One per guide to ease reviews and prioritize  accordingly.
This PR adds the base README for the production guides.
Needs:
> docs: production guide base setup

- package.json
- src/keychain/cms.js
- src/keychain/index.js
- src/peer-routing.js
I found some last issues integrating https://github.com/ipfs/js-ipfs/pull/3427
I needed to add the keychain types to smoothly integrate this on IPFS
> fix: types from ipfs integration

- package.json
- src/record/peer-record/consts.js
With multicodec types update, `getName` might return undefined.
This will never happen in this case but types complain that it might be undefined in the PeerRecord, so I added a fallback string value
Needs:
> chore: fix multicodec updates

- doc/CONFIGURATION.md
Addresses point 1 under #756.  
cc: @jacobheun @vasco-santos 
I wasn't clear from the issue description if the snippet desired is just an addition to the existing custom peer discovery or a whole separate section.  If the latter, let me know and I'm happy to re-write.
> docs: Add bootstrap to custom peer discovery

- src/connection-manager/index.js
- src/connection-manager/latency-monitor.js
- src/connection-manager/visibility-change-emitter.js
- src/index.js
- src/metrics/stats.js
- src/peer-store/index.js
- src/types.ts
This PR fixes the current broken build job of aegir.
EventEmitter types were broken in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50266. This was resulting in the following errors:
```
src/connection-manager/latency-monitor.js:2:1 - error TS9006: Declaration emit for this file requires using private name 'EventEmitter' from module '"events"'. An explicit type annotation may unblock declaration emit.
2 'use strict'
~~~~~~~~~~~~
src/connection-manager/visibility-change-emitter.js:7:1 - error TS9006: Declaration emit for this file requires using private name 'EventEmitter' from module '"events"'. An explicit type annotation may unblock declaration emit.
7 'use strict'
~~~~~~~~~~~~
src/index.js:1:1 - error TS9006: Declaration emit for this file requires using private name …
```
> fix: event emitter types with local types

- .github/workflows/main.yml
- examples/connection-encryption/1.js
- examples/connection-encryption/README.md
- examples/connection-encryption/test.js
This PR adds a test for the connection encryption example. The example folder name was changed to connection encryption to better match the connEncryption module name in libp2p configuration.
> chore: connection encryption example test

- examples/discovery-mechanisms/bootstrapers.js
It looks like the location of this file changed upstream. This change just fixes the URL in a comment
> Fix: Update comment in bootstrapers.js

- src/index.js
When using the libp2p create static function, the `peerId` parameter is not required.
I tried to simply make it optional in `CreateOptions`, but sadly it does not override the required in `Libp2pOptions`. So, I needed to create a new typedef.
Context https://github.com/libp2p/js-libp2p/issues/873
> fix: create has optional peer id type

- src/nat-manager.js
The retry operation in the NAT Manager can prevent node from shutting down, so unref the retries so they don't keep adding work to the event loop.
> fix: unref nat manager retries

- src/index.js
Making PeerDiscovery options to `Object` by now. Otherwise, ts projects will fail to build as they will need to add discovery modules configuration. This should only be done when we type the modules
Closes #876
> fix: peer discovery type in config to object

- src/identify/index.js
We have no way of verifying them so don't add them just yet.
> fix: do not add observed address received from peers

- .github/workflows/main.yml
- examples/discovery-mechanisms/3.js
- examples/discovery-mechanisms/README.md
- examples/discovery-mechanisms/test-3.js
- examples/discovery-mechanisms/test.js
- examples/package.json
This PR adds a new discovery example leveraging [libp2p/js-libp2p-relay-server](https://github.com/libp2p/js-libp2p-relay-server) with pubsub discovery.
Needs:
> chore: add discovery example with relay and pubsub discovery

- doc/CONFIGURATION.md
- test/content-routing/content-routing.node.js
Updates configuration docs for delegate config using the http-client per newer versions
> chore: update delegates config docs to use http client

- src/content-routing/index.js
- src/peer-routing.js
- test/content-routing/content-routing.node.js
- test/peer-routing/peer-routing.node.js
When used from IPFS (and other projects where the DHT module is added to the libp2p config), but the enabled option was turned to false (default), the DHT was being used for content/peer routing queries.
> fix: routers should only use dht if enabled

- src/transport-manager.js
- test/transports/transport-manager.spec.js
When we added a fault tolerance option to libp2p's transport manager, this only included a scenario where the provided multiaddrs were not compatible to the configured transport resulting in no listen multiaddrs used to create listeners in the transports.
This fault tolerance should also include tolerance for failure on trying to listen on multiaddrs that are compatible with the configured transport but the listen fails. This is specially important for remote listeners like relays and webrtc signal servers.
Context: https://github.com/ipfs-shipyard/ipfs-share-files/pull/121
> fix: transport manager fault tolerance should include tolerance to transport listen fail

- .aegir.js
- .github/workflows/main.yml
- examples/libp2p-in-the-browser/package.json
- examples/webrtc-direct/package.json
- src/metrics/stats.js
This PR fixes the connection manager access to the `movingAverages` getter. After the module update with types, this broke libp2p's build.
It returns an Object as we can see on:
- https://github.com/libp2p/js-libp2p/blob/master/src/metrics/stats.js#L29
- https://github.com/libp2p/js-libp2p/blob/master/src/metrics/stats.js#L88
This object contains a key for the metric and another object as value to create multiple intervals for computing the move average: `movingAverages[key][interval].movingAverage()` => This is the actual MovingAverage instance.
Metrics is not a public API and is not properly typed for now, the work is being tracked on https://github.com/libp2p/js-libp2p/issues/830 . We should probably change this from an Object to a Map and properly type these moving averages record, …
> fix: conn mgr access to moving averages record object

- .aegir.js
- src/keychain/index.js
- src/upgrader.js
This PR includes 3 commits:
1. Connection direction should be only inbound or outbound per https://github.com/libp2p/js-libp2p-interfaces/pull/86
2. Bundle size needs extra 1kb
3. `interface-datastore` was updated to export `d.ts` file instead
> fix: typescript module updates

- package.json
- src/nat-manager.js
- test/nat-manager/nat-manager.node.js
Fixes a regression introduced by #896
`promisify-es6` was swapped for `es6-promisify` but the APIs of the two modules are no the same so the NAT hole punching code broke and stopped libp2p nodes UDP ports open which prevented processes from exiting.
Also changes port numbers to 0 in the tests as other processes can be listening on those ports which causes spurious test failures.
> fix: the API of es6-promisify is not the same as promisify-es6

- test/nat-manager/nat-manager.node.js
The NAT manager test will throw if the current computer is behind a
double NAT as at runtime it won't be possible to map external ports.
We don't care about that during the test so configure a fake external
IP so the test will still test the shut-down functionality on a computer
that is behind a double NAT.
> chore: do not look up external IP during test

- src/metrics/stats.js
Otherwise the compiler cannot derive the type and thinks `stats.snapshot` returns `{}`
> fix: give stats initial values

- package.json
- src/upgrader.js
- test/ts-use/package.json
Fixes problem with create-react-app's default webpack config that
transpiles the functions to non-async methods.
Depends on:
> fix: remove inline arg types from function definitions

- src/dialer/index.js
- test/core/listening.node.js
- test/dialing/direct.node.js
Node warns of a possible memory leak thanks o added event listeners on abortSignal:
```
(node:52434) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
at EventTarget.[kNewListener] (node:internal/event_target:256:17)
at EventTarget.addEventListener (node:internal/event_target:335:23)
at anySignal (node_modules/any-signal/index.js:27:12)
at node_modules/libp2p/src/dialer/dial-request.js:70:85
at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:94:5)
```
This started to happen when we start supporting `dnsaddr` resolution and `js-ipfs` started using bootstrap nodes with such addresses. Once these `dnsaddr` records are resolved, we get a large list …
> fix: do not add abort signals to "useless" addresses

- package.json
- src/index.js
The [clientMode](https://github.com/libp2p/js-libp2p-kad-dht/blob/master/src/index.js#L63) arg was missing from the DhtOptions type and interface-datastore has a new version available.
> fix: add clientMode dht arg and upgrade interface-datastore

- src/circuit/auto-relay.js
- src/index.js
- src/peer-store/address-book.js
- test/peer-store/address-book.spec.js
- test/relay/auto-relay.node.js
The AddressBook.add has a bug where if a libp2p module does `addressBook.add(peerId, [])` the peer event will be emitted. This leads into two consequences:
- (with autoDial enabled) a dial will be attempted to the discovered peer, even though we can't really dial it
- dial on discovery is wrapped with a `try ... catch` and it will just fail and life goes on  
- when we really discover addresses for the peer and do a new `addressBook.add`, the event will not be emitted and the peer will not be dialled (if autoDial enabled)
Other than this bug and related to #886 , the `libp2p.dial` / `libp2p.dialProtocol` should be wrapped by a `try ... catch` as a dial fail should not make libp2p protocols fail to properly work. This PR also wraps the `autoRelay` dial to avoid a unhandled promise …
> fix: address book should not emit peer event if no addresses are known

- src/index.js
- src/pubsub-adapter.js
Changes the `Libp2pModules.pubsub` property to be a class that maybe
extends `PubsubBaseProtocol` instead of an instance of that class.
The `.dht` property could use the same treatment but that can be
done in a follow up as the current `object` type doesn't cause an error.
> fix: demand pubsub class instead of pubsub instance

- src/peer-store/address-book.js
- test/peer-store/address-book.spec.js
Sometimes delegate nodes return replicated addresses and then we will try to dial repeated addresses.
cc @aschmahmann (this happened while finding closest peers to `QmQ73f8hbM4hKwRYBqeUsPtiwfE2x6WPv9WnzaYt4nYcXf`). Not sure if an old node, or wether go DHT guarantees no replicated addresses are returned.
> fix: address book guarantees no replicated entries are added

- src/metrics/stats.js
Before the data type of Moving Averages (`IMovingAverage`) was exported by default, while the module exported the function that creates the `IMovingAverage` by default. This was creating issues on lodestar and we fixed it, but now libp2p record needs to store `IMovingAverage` instead
> fix: moving averages record types

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/open_an_issue.md
- .github/ISSUE_TEMPLATE/release.md
This PR moves the Release Template to an Issue Template.
Other changes:
- Release template does not track libp2p-examples
- Generic Issue template update: currently we have one (defined In Project settings?), but it mentions discuss.ipfs.io
Needs current issue template to be removed (I do not have permissions to access Settings)
> chore: add GitHub issue templates

- src/peer-routing.js
- test/peer-routing/peer-routing.node.js
Resolves an issue where nodes running findPeer() on themselves return abstract aggregateErrors instead of something "more suitable" like ERR_DIALED_SELF. Original issue can be found [here](https://github.com/libp2p/js-libp2p/issues/827).
This is accomplished by comparing the _idB58String of the ID parameter to this._peerId._idB58String at [peer-routing.js](https://github.com/libp2p/js-libp2p/blob/master/src/peer-routing.js#L102). if the two values are equal, an error is thrown alerting the user of the mistake. For example:
```javascript
async findPeer (id, options) { // eslint-disable-line require-await
...
if (id._idB58String == this._peerId._idB58String) throw errCode(new Error('Cannot search for self'), 'ERR_DIALED_SELF')
...
}
```
> fix: peerRouting.findPeer() trying to find self

- doc/CONFIGURATION.md
Fixed a typo at [setup keychain](https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md#setup-with-keychain) that was referencing "libp2p"  instead of "node." See below:
```javascript
const node = await Libp2p.create({...})
//Typo:
await libp2p.loadKeychain()
//Correction:
await node.loadKeychain()
```
> Fix: CONFIGURATION.md keychain typo

- src/identify/index.js
- test/identify/index.spec.js
These values were not being stored during identify.
> fix: store remote agent and protocol version during identify

- src/index.js
- src/keychain/index.js
- test/keychain/keychain.spec.js
This is a rough implementation supporting [rotating keychain passphrases](https://github.com/libp2p/js-libp2p/issues/728). I need some suggestions on how to proceed. I haven't received a reply so I've copied the original conversation here for reference:
```js
async changeKeychainPassword(oldPassword, newPassword){
if (typeof oldPassword !== 'string' || typeof newPassword !== 'string') {
throw new Error(`Invalid pass type '${typeof oldPassword}'`);
}
if (newPassword.length < 20) {
throw new Error('pass must be least 20 characters')
}
// TODO: Need to decide on how to import/generate opts
const newDek = newPassword
? crypto.pbkdf2(
newPassword,
this.opts.dek.salt,
this.opts.dek.iterationCount,
this.opts.dek.keyLength,
this.opts.dek.hash)
: ''
const oldDek = privates.get(this).dek …
```
> Feat: keychain rotate passphrase

- examples/chat/src/dialer.js
- examples/chat/src/listener.js
- examples/package.json
The Multiaddr update did not bubble up to the chat example 😱 Thanks @mobeiqingkong for pointing this out
The chat example test has been running fine in the CI (last commit: https://github.com/libp2p/js-libp2p/runs/2637518502), but it is using the old multiaddr. After looking into how it is getting the dependencies, I noticed that libp2p examples have some dependencies (`libp2p-pubsub-peer-discovery` and `libp2p-relay-server`) that use the older multiaddr and that ends up being the one used in the examples.
Needs:
> fix: chat example with new multiaddr

- doc/CONFIGURATION.md
This weekend I hooked up DHT in my js-libp2p app. It did not work, because I had not set dht.enable:true in the configuration on the client side. I [spent an embarrassing amount of time trying to fix this and wound up filing a bug](https://github.com/libp2p/js-libp2p-kad-dht/issues/221). Oops.
However, one thing occurs to me. I remember reading CONFIGURATION.md at some point while setting my app up, and I think I didn't realize the configuration was necessary because of the line "enabled by default"  immediately after. There are two "enabled:true" lines immediately next to each other, one is labeled "enabled by default" (and is), the other is disabled by default. I think I saw "enabled:true // by default" and thought ah! So I don't need to set it! and totally blanked that there was two …
> Be extra explicit on DHT configuration in CONFIGURATION.md

- doc/CONFIGURATION.md
- package.json
- src/circuit/utils.js
- src/nat-manager.js
- test/content-routing/content-routing.node.js
- test/peer-routing/peer-routing.node.js
- test/relay/auto-relay.node.js
- test/ts-use/src/main.ts
We only use it for the env detection, so use [wherearewe](https://www.npmjs.com/package/wherearewe) instead which is that, but pulled out into a tiny module.
The `TextDecoder` class is global everywhere we support so we don't need to pull it in from `ipfs-utils` and it's been removed from v8 of that module anyway.
Also updates ipfs-http-client to the latest version.
> chore: remove ipfs-utils dep

- src/connection-manager/index.js
- src/connection-manager/latency-monitor.js
- src/dialer/index.js
- test/dialing/direct.spec.js
This PR fixes the potential leaking of resources in the dialer on stop.
During the `transport.dial` flow, if libp2p is stopped the on going dials were being aborted. However, situations like https://github.com/libp2p/js-libp2p-tcp/issues/142 were possible when a given resolvable multiaddr (`dnsaddr`) is being resolved before getting into the transport level. This would result in new dial attempts after stop and established connections that prevented the process from properly stop.
Unfortunately, node's dns record resolution does not allow the lookup to be abortable. As a consequence, this PR adds a competing Cancellable promise, which will be rejected in case of `libp2p.stop()` => `dialer.destroy()`. With this, the promise that would resolve the `dialTarget` will be rejected and the …
> fix: dialer leaking resources after stopping

- package.json
> fix: move abortable-iterator to dependencies

- doc/CONFIGURATION.md
Current version points to deprecated repo. Fixed by using correct URL.
> Fix datastore link in configuration.md

- doc/API.md
Fixes #1018
The issue was caused when the repo [js-libp2p-interfaces](https://github.com/libp2p/js-libp2p-interfaces) was renamed and refactored in this [commit](https://github.com/libp2p/js-libp2p-interfaces/commit/946348f7f8acc1ff7bc9cd0ab4c2602d41106f76)
> docs: update connection link in API docs

- .github/workflows/examples.yml
Uses npm to install deps for examples.
We can put yarn back when we remove `node-fetch@2.x` from ipfs-utils, or when
yarn can download tarball dependencies reliably.
This either needs:
1. https://github.com/node-fetch/node-fetch/pull/1172 merging
2. Swap node-fetch for undici
3. Drop CJS support (node-fetch 3 has the above fix but is ESM-only)
> chore: fix examples

- src/connection-manager/auto-dialler.js
- src/connection-manager/index.js
- src/index.js
Stop the dht before the connection manager, otherwise in-flight eviction pings fail and we move on to the next one when we should just abort them all.
Also pulls in the fix from #1039 and splits the auto-dialler out from the connection manager as during shutdown it can get into a weird state where it's simultaneously killing and creating connections so stop auto-dialling things before we cause connections to dip below the low watermark by killing existing connections.
Fixes: https://github.com/ipfs/js-ipfs/issues/3923
> fix: stop dht before connection manager

- src/peer-routing.js
The DHT takes a `signal` not a timeout so if a timeout is passed,
create a `TimeoutController` that will abort the query after the
timeout.
> fix: do not let closest peers run forever

- src/dialer/dial-request.js
Sometimes you encounter peers with lots of addresses. When this happens you can attach more than 10x event listeners to the abort signal we use to abort all the dials - this causes node to print a warning which is misleading.
This PR increases the default number of listeners on the signal.
Fixes #900
> fix: increase maxlisteners on event target

- examples/pubsub/1.js
Seems like the correct return type of `Libp2p.pubsub.subscribe` is `void`, so the `await` can be removed: https://github.com/libp2p/js-libp2p/blob/ae21299ade9bcb2cf3fd00150c4389fbe3b24267/src/pubsub-adapter.js#L29
> Libp2p.pubsub.subscribe returns void, remove await

- package.json
- src/nat-manager.js
@motrix/nat-api is a fork, nat-api has the fix from https://github.com/alxhotel/nat-api/pull/25
> chore: switch to nat api

- src/dialer/index.js
If the `Promise.race` throws, execution of the function is terminated so the pending dial target is never removed from the map and we leak memory.
This can happen when there are invalid multiaddrs or when a peer reports more dialable addresses than the threshold.
Instead wrap the `Promise.race` in a `try/finally` which will always remove the pending dial target in the event of success or failure.
> fix: clean up pending dial targets

- .github/workflows/main.yml
- src/connection-manager/index.js
- src/dialer/index.js
- src/index.js
- src/metrics/index.js
- test/metrics/index.spec.js
Implements the idea from #1060 - allows us to get some insight into what's happening in a libp2p node out side of just bandwidth stats.
Configures a few default metrics if metrics are enabled - current connections, the state of the dial queue, etc.
Also makes the `Metrics` class not depend on the `ConnectionManager` class, otherwise we can't collect simple metrics from the connection manager class due to the circular dependency.
> feat: allow per-component metrics to be collected

- src/dialer/index.js
- src/peer-routing.js
We use timeout controllers to ensure we're not dialling peers forever but we can end up registering lots of listeners for the `abort` event when peers have a lot of addresses.
In node this means we see an unhelpful `MaxListenersExceededWarning` in the console warning of a potential memory leak.
Increase the max number of listeners on the signal to silence the warning.
> fix: increase the maxlisteners for timeout controllers

- src/connection-manager/index.js
- src/dialer/index.js
- src/index.js
- src/metrics/tracked-map.js
Small refactor of the component stats - adds a `TrackedMap` which encapsulates updating the metrics and means we don't need to null guard on `this._metrics` everywhere.
If metrics are not enabled a regular `Map` is used.
> fix: add tracked map

- .github/workflows/main.yml
On https://github.com/libp2p/js-libp2p/pull/1061 the bundle size was changed and the main CI workflow has not been running. It must include the branch/version
> fix: main ci workflow

- src/metrics/tracked-map.js
Record the size of a map after we `.clear()` it.
> fix: record tracked map clears

- src/dialer/index.js
Increase the number of listeners we allow on the actual signal we pass along, instead of the signal we pass into any-signal.
> fix: increase listeners on any-signal

- src/connection-manager/auto-dialler.js
When we've previously seen loads of peers and stored them in the
datastore we'll try to dial them as part of starting the autodial
component.
If we or our peers have bad network connections this can make
starting a libp2p node take ages so don't wait for a round of auto
dialing before considering the component started.
> fix: do not wait for autodial start

- src/dht/dht-peer-routing.js
`FINAL_PEER` means we found the peer, `PEER_RESPONSE` means a peer
responded to our query.
> fix: look for final peer event instead of peer response

- package.json
We don't need them anymore as we changed testing setup per https://github.com/libp2p/js-libp2p/issues/857
> chore: remove pubsub dev deps

- examples/pubsub/README.md
> Import uint8arrays package in example

- package.json
- test/dialing/dial-request.spec.js
- test/utils/mockMultiaddrConn.js
The `AbortController` class is supported by browsers and node 14+ - we only support node 16+ (e.g. LTS+Current) so the `abort-controller` module isn't needed any more.
> fix: remove abort-controller dep

- .github/workflows/main.yml
If we aren't releasing a version on a given release run, publish an rc under the `next` tag instead.
> chore: autopublish next version

- test/connection-manager/index.node.js
- test/core/ping.node.js
- test/dialing/direct.node.js
- test/dialing/direct.spec.js
- test/identify/index.spec.js
- test/peer-discovery/index.node.js
- test/peer-discovery/index.spec.js
- test/relay/auto-relay.node.js
- test/relay/relay.node.js
- test/utils/creators/peer.js
These tests are flaky in CI, probably due to differences in timing introduced by #1058
Fixes #1134
> chore: fix flaky tests

- doc/CONFIGURATION.md
- src/circuit/auto-relay.js
- test/relay/auto-relay.node.js
Try to use only public functions and properties to verify test behaviour and wait for things to be true.
> fix: make tests more reliable

- src/circuit/auto-relay.js
- src/connection-manager/index.js
- test/relay/auto-relay.node.js
The order of the addresses can affect our success rate in dialing a relay - if it's a loopback address or similar it won't work.
Instead try dialing every address.
Seems to be the cause of the random CI failures in https://github.com/libp2p/js-libp2p/pull/1136
> fix: try all peer addresses when dialing a relay

- src/index.js
- src/ping/index.js
- test/upgrading/upgrader.spec.js
To allow us to shut down cleanly, we must wait the unhandling of protocols - this is because they write the new list of protocols into the datastore which might also be in the process of shutting down.
> fix: await unhandle of protocols

- src/connection-manager/index.js
- src/peer-store/address-book.js
- test/dialing/direct.node.js
- test/dialing/direct.spec.js
- test/dialing/resolver.spec.js
- test/registrar/registrar.spec.js
- test/upgrading/upgrader.spec.js
When the node is shutting down, new connections can still be received.
If this happens we can end up writing into the datastore when it's
been closed which throws an error.
Instead, if we're not running, have the connection manager close new
incoming connections.
> fix: reject connections when not running

- examples/transports/README.md
> chore: update js-interfaces URL in examples/transports README

- doc/CONFIGURATION.md
- doc/STREAMING_ITERABLES.md
- doc/migrations/v0.26-v0.27.md
- package.json
- src/config.ts
- src/index.ts
- src/transport-manager.ts
- test/nat-manager/nat-manager.node.ts
- test/transports/transport-manager.spec.ts
Addresses PR comments from #1172 - fixes syntax of examples in docs, adds the transport manager to the exports map and renames fault tolerance enum for consistency.
> fix: add transport manager to exports map and fix docs

- src/index.ts
- src/libp2p.ts
Exposes fields used by bitswap and also uses dht for peer discovery which was missed.
> fix: expose metrics and registrar, use dht for peer discovery

- package.json
- src/connection-manager/index.ts
- test/dialing/direct.spec.ts
- test/identify/index.spec.ts
- test/upgrading/upgrader.spec.ts
**Motivation**
In lodestar, when we handle "peer:connect" event, we dial the peer which gives another "peer:connect" event and it causes other issues
**Motivation**
In `onConnect` function, "peer:connect" event should be emitted after we add connection to the `connections` map so that when app dial the peer in "peer:connect" event handler, it uses the same/existing connection
> fix: emit peer:connect after all

- doc/migrations/v0.36-v.037.md
Adds migration guide for `libp2p@0.37.x`
> docs: add migration guide

- package.json
- src/nat-manager.ts
- test/nat-manager/nat-manager.node.ts
The transport manager configures it's addresses during the `start`
phase so access them during `afterStart` so they'll be ready for use.
> fix: do upnp hole punch after startup

- src/upgrader.ts
- test/upgrading/upgrader.spec.ts
If an error is thrown during the initial stages of setting up a multiplexed stream, ensure we close the stream to free up any resources associated with it.
> fix: ensure streams are closed when protocol negotiation fails

- README.md
- examples/auto-relay/README.md
- examples/chat/README.md
- examples/echo/README.md
- examples/libp2p-in-the-browser/README.md
- examples/peer-and-content-routing/README.md
- examples/pnet/README.md
- examples/pubsub/README.md
Now that we need to build ts to js a build step is necessary.
Add it to the instructions where we are telling people to clone the repo first.
Refs: #1273
> docs: add build step to docs

- doc/API.md
- doc/CONFIGURATION.md
- doc/CONNECTION_MANAGER.md
- package.json
- src/connection-manager/index.ts
- test/connection-manager/index.spec.ts
Uses peer tag values to select low-value connections to prune when we have too many connections open.
BREAKING CHANGE: `connectionManager.peerValue` has been removed, use `peerStore.tagPeer` instead
> feat!: use tag values to choose which connections to close

- src/upgrader.ts
- test/relay/auto-relay.node.ts
- use `direction` in `muxerFactory.createStreamMuxer`
- use `muxer.close` instead of `muxer.streams.forEach(s => s.close())`
> fix: update muxer behavior

- src/circuit/transport.ts
- src/connection-manager/dialer/auto-dialer.ts
- src/connection-manager/index.ts
- src/fetch/index.ts
- src/identify/index.ts
- src/ping/index.ts
- src/upgrader.ts
Where we create signals that are passed down the stack, increase the max listeners to prevent warnings in the console.
> fix: MaxListenersExceeded warning

- README.md
Removed "Talks" section as links are broken.
> docs: removed talks section 

- examples/delegated-routing/package.json
- examples/libp2p-in-the-browser/package.json
- examples/webrtc-direct/package.json
- package.json
- test/relay/relay.node.ts
- test/upgrading/upgrader.spec.ts
Muxer errors are now standard across implementations so do not depend on the `"MPLEX_"` prefix
> fix: remove mplex prefix from muxer errors

- src/upgrader.ts
- test/upgrading/upgrader.spec.ts
If a protocol stream has been successfully negotiated and is to be
psased to the application, the peerstore should ensure that the peer is
registerd with that protocol.
@achingbrain should the `add` be awaited? or should it be done async?
> fix: add successful stream peer to protobook

- src/connection-manager/index.ts
Since we don't wait for successful reconnection to existing peers,
the peerstore can be closed while we're accessing it since we might
be shut down right after we've started up, e.g. during test runs so
just log any reconnect errors instead of throwing.
> fix: catch errors when reconnecting old peers

- src/circuit/transport.ts
Otherwise the reported remote addr is not valid
> fix: prepend connection addr to circuit relay address

- doc/API.md
- doc/CONFIGURATION.md
- src/index.ts
- src/keychain/index.ts
- src/libp2p.ts
- test/configuration/utils.ts
- test/keychain/keychain.spec.ts
To prevent triggering keychain attack prevention on startup, refactor the `KeyChain` class to load the current PeerId as the `'self'` key on startup.
Fixes #1315
BREAKING CHANGE: the `loadKeychain` method has been removed as it is no longer necessary
> fix!: load self key into keychain on startup if not present

- examples/discovery-mechanisms/3.js
- examples/discovery-mechanisms/test-2.js
- examples/discovery-mechanisms/test-3.js
- examples/package.json
- fixed tests that were passing even though the example isn't working
- added timeouts to avoid infinite wait
Depends on:
- https://github.com/libp2p/js-libp2p-pubsub-peer-discovery/pull/49
resolves #1229
> fix: discovery mechanism examples not working

- README.md
The libp2p <3 ethereum video seems to have been moved to https://archive.devcon.org/archive/watch/2/libp2p-devp2p-ipfs-and-ethereum-networking/
unfortunately couldnt find the slides and demos previously linked
Related:
https://github.com/libp2p/js-libp2p/issues/1299
https://github.com/libp2p/js-libp2p/pull/1300
> docs: re-add talks section

- doc/GETTING_STARTED.md
libp2p-noise has been moved to @chainsafe/libp2p-noise
> docs: update noise package name in instructions

- doc/GETTING_STARTED.md
- examples/auto-relay/README.md
- examples/discovery-mechanisms/README.md
- examples/peer-and-content-routing/README.md
- examples/protocol-and-stream-muxing/README.md
- examples/pubsub/README.md
- examples/pubsub/message-filtering/README.md
- examples/transports/README.md
- examples/webrtc-direct/README.md
This PR fixes all the errors in the code snippets in the readme files contained in the examples directory and it fixes the doc/GETTING_STARTED.md file.
I have also updated the old package names, e.g. `libp2p-websockets` -> `@libp2p/websockets`.
Resolves #1367 and resolves #1361.
> docs: fix examples in documentation

- src/dht/dht-peer-routing.ts
- test/peer-routing/peer-routing.node.ts
`PEER_RESPONSE` is an intermediate event, we should only yield from `FINAL_PEER` events as we'll only get `K` of those.
n.b. this will make the `libp2p.peerRouting.getClosestPeers` call take longer to start yielding results if they are only findable by the DHT but they'll be more accurate.
If you want status events, call the lower level [`libp2p.dht.getClosestPeers` method](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interface-dht/src/index.ts#L154) instead.
> fix: yield only final peers from dht getClosestPeers

- src/connection-manager/dialer/index.ts
It turns out because `Multiaddr.encapsulate` stringifies the `Multiaddr` it's a [suprisingly expensive operation](https://github.com/multiformats/js-multiaddr/pull/275#issuecomment-1254981709) so here we switch the order of our `Multiaddr` pipeline around so we filter undialable addresses (e.g. unsupported transports etc) before encapsulating the `PeerId` onto a `Multiaddr` we'd then just ignore.
> fix: when creating dial targets, encapsulate PeerIds last

- README.md
- doc/CONFIGURATION.md
- doc/LIMITS.md
To help people better configure their libp2p nodes to defend against malicious peers, document all the limit settings and protections in one place.
> docs: add limit configuration documentation

- src/identify/index.ts
Close the stream after we finish writing the identify message. This is behavior is specified https://github.com/libp2p/specs/blob/master/identify/README.md#identify
> The peer being identified responds by returning an Identify message and closes the stream.
This shows up when interacting with a go-libp2p node as go-libp2p waits for the stream to close before finishing reading the messages: https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/identify/id.go#L455.
> fix: close stream after sending identify

- doc/GETTING_STARTED.md
without the fix, it will give error:
> SyntaxError: The requested module '@libp2p/xxx' does not provide an export named 'xxx'
> docs: update GETTING_STARTED.md

- examples/webrtc-direct/listener.js
Previous import was importing WebRTCDirect instead of webRTCDirect.
```javascript
import { WebRTCDirect } from '@libp2p/webrtc-direct'
```
Is changed to 
```javascript
import { webRTCDirect } from '@libp2p/webrtc-direct'
```
> Fixed the WebRTC import

- test/core/listening.node.ts
If you're running the tests on a computer not attached to a network, for example on an aeroplane with flight-safe mode enabled, this test fails so allow detecting a single (loopback) address.
> test: address length test should accept a single address

- src/address-manager/index.ts
- test/addresses/address-manager.spec.ts
Some listen addresses are turned into valid unique addresses when listening on them, for example `/ip4/0.0.0.0/tcp/0`, so we should be able to listen on multiple versions of addresses like these.
Currently we dedupe listen addresses before listening starts so this isn't possible.
This PR removes the deduping and adds a test.
> fix: allow listening on duplicate addresses

- examples/libp2p-in-the-browser/README.md
The previous documentation link was wrong, updated to the new one.
> docs: fixed wrong link to the webrtc-star signaling server deployment file

- doc/API.md
Doesn't seem like this exists in the API anymore?
> docs: remove loadkeychain from instance methods

- src/upgrader.ts
Instead of using `it-pipe` to tie the inputs and outputs of the muxer and underlying connection together, pipe them in parallel.
When sending 105MB in 32b chunks:
```
testing 0.36.x
sender 3276810 messages 1638409 invocations  <-- how many mplex messages are sent in how many batches
sender 1638412 bufs 68 b                     <-- how many buffers are passed to the tcp socket and their average size
105 MB in 32 B chunks in 9238ms
```
```
testing 0.40.x-mplex
sender 3276811 messages 32 invocations
sender 6553636 bufs 17 b 27476 ms
105 MB in 32 B chunks in 27450ms
```
```
testing 0.40.x-mplex
sender 3276811 messages 17 invocations
sender 6553636 bufs 17 b 23781 ms
105 MB in 32 B chunks in 23753ms
```
```
testing 0.40.x
sender 3276811 messages 1638408 invocations
1638411 bufs 68 b
105 MB in …
```
> fix: pipe muxer/connection input/output streams in parallel

- examples/auto-relay/dialer.js
- examples/auto-relay/listener.js
- examples/echo/src/dialer.js
- src/get-peer.ts
- src/index.ts
- src/libp2p.ts
Only accept PeerId or Multiaddr objects as arguments to fetch and hangUp the same as ping, dial, etc.
This was missed during the typescript refactor.
BREAKING CHANGE: libp2p.hangUp and libp2p.fetch require PeerId or Multiaddr objects the same as other methods
> fix!: remove strings from fetch and hangUp

- src/keychain/index.ts
- src/upgrader.ts
- test/upgrading/upgrader.spec.ts
We already allow skipping upgrade steps for outgoing connections, this PR adds the same capability of incoming connections.
This is to support listeners for new transports like webtransport and webrtc that manage their own encryption and multiplexing.
> feat: allow skipping upgrade steps for incoming connections

- src/registrar.ts
- test/registrar/registrar.spec.ts
If the peer reconnects with the same protocols, `change:protocols` is not emitted and topology `onConnect` callbacks are not invoked. This adds listening to connect events in the registrar and checks if we already know protocols for peers before calling the topology `onConnect` callback.
resolves #1496
> fix: registrar is not calling topology on peer reconnect

- src/libp2p.ts
So we don't have to expose the registrar component, add a method to get the currently supported protocols
> fix: add getProtocols method

- src/libp2p.ts
BREAKING CHANGE: the connection manager and registrar are internal types and as such not part of the libp2p interface, instead use the methods exposed on the root libp2p type for obtaining connections and protocols
> fix!: forward connection manager events on and update types

- doc/migrations/v0.40-v0.41.md
- doc/migrations/v0.41-v0.42.md
Adds migration guide for the breaking changes in 0.42.x
> docs: add migration guide for 0.42.x

- src/connection-manager/index.ts
- test/connection-manager/index.node.ts
If the user does not care about the latency monitor, we should not run an interval sampling the delay as it's expensive and unecessary.
The fix here is to only create a latency monitor in the connection manager if the user sets a `maxEventLoopDelay` value.
> fix: only configure the latency monitor if a limit is configured

- src/identify/index.ts
- src/libp2p.ts
To satisfy the types these need to be public
> fix: expose identify service properties

- doc/LIMITS.md
- src/connection-manager/index.ts
- test/connection-manager/index.spec.ts
Closes https://github.com/libp2p/js-libp2p/issues/1509
> fix: close short-lived connections first when pruning by tag value

- doc/migrations/v0.41-v0.42.md
- src/libp2p.ts
Expose the register and unregister methods as part of the root libp2p node object.
> fix: add register and unregister methods to root node object

- examples/delegated-routing/package.json
- examples/libp2p-in-the-browser/package.json
- examples/webrtc-direct/package.json
> chore: update @chainsafe/libp2p-noise dep in examples

- examples/pubsub/message-filtering/1.js
- examples/pubsub/message-filtering/test.js
Instead of waiting an arbitrary amount of time for subscriptions to propagate, before sending messages, ensure that node1 has node2's subs and node2 has node3's subs.
Closes https://github.com/libp2p/js-libp2p/pull/1540
> fix: improve pubsub example

- doc/CONFIGURATION.md
`FaultTolerance` is imported from `@libp2p/interface-transport` since v0.42.0.
> docs: fix FaultTolerance import in configuration documentation

- src/keychain/index.ts
- test/keychain/keychain.spec.ts
We can import a PeerId but not export it, so this PR adds the ability to export a PeerId.  This is useful for IPNS and other things that need the ability to act on PeerIds stored in the keychain.
> fix: allow exporting PeerIds from the keychain

- src/address-manager/index.ts
- test/addresses/address-manager.spec.ts
Some multiaddrs have a path address as the final component - these components are terminal in that you cannot append further tuples to them, so do not do that when one is encountered.
> fix: do not append peer id to path addresses

- src/libp2p.ts
- test/core/peer-id.spec.ts
libp2p has a secure keychain where all items are stored in the datastore in an encrypted format, including the PeerId of the current node.
If no PeerId is passed into the factory function, a new PeerId is created for the current node.
Instead, if the factory function is passed a datastore, it should try to read the PeerId from the datastore and only create a new PeerId if the `self` key is not in the datastore.
> fix: allow reading PeerId from keychain

- doc/PEER_DISCOVERY.md
- src/address-manager/index.ts
- test/addresses/address-manager.spec.ts
Following https://github.com/libp2p/js-libp2p/pull/1397 being merged the docs need to be updated to reflect the new behaviour of the `AutoDialer` (being removed from the `connectionManager`) along with the new configurations proposed in https://github.com/libp2p/js-libp2p/pull/1511
> docs: Update the peer discovery docs

- src/connection-manager/auto-dialler.ts
- test/connection-manager/auto-dialler.spec.ts
When the number of connections the node has drops below the low watermark and auto-dial begins, exclude peers without multiaddrs from the list of peers that the node tries to connect to as dialing a peer without multiaddrs will fail.
Also removes use of `it-pipe` to make it a little faster as there's no need for the peer filtering/sorting to be asynchronous.
> fix: exclude peers without multiaddrs from auto dial

- src/connection-manager/dialer/index.ts
- src/connection-manager/index.ts
Closes https://github.com/libp2p/js-libp2p/issues/1567
Related to https://github.com/libp2p/js-libp2p-interfaces/pull/342
> feat: updated connection manager and dialer with new interface methods

- README.md
Libp2p has a channel (#libp2p-chatter) inside the IPFS discord server.
- invite link changed to https://discord.gg/ipfs
- server id for shield.io img fixed to 806902334369824788
Closes #1591
> chore: repair discord invite link

- src/config.ts
- test/ping/ping.node.ts
Modify the default configuration for the PING protocol to accept at most two streams per peer, as recommended in the PING protocol spec.
Quoting https://github.com/libp2p/specs/blob/d4b5fb0152a6bb86cfd9ea/ping/ping.md?plain=1#L38-L43
> The dialing peer MUST NOT keep more than one outbound stream for the ping protocol per peer.  The listening peer SHOULD accept at most two streams per peer since cross-stream behavior is non-linear and stream writes occur asynchronously. The listening peer may perceive the dialing peer closing and opening the wrong streams (for instance, closing stream B and opening stream A even though the dialing peer is opening stream B and closing stream A).
> fix: accept two incoming PING streams per peer

- doc/CONFIGURATION.md
- doc/GETTING_STARTED.md
- doc/PEER_DISCOVERY.md
- doc/migrations/v0.42-v0.43.md
- examples/discovery-mechanisms/1.js
- examples/transports/4.js
- src/config.ts
- src/connection-manager/auto-dialler.ts
- src/connection-manager/index.ts
- src/libp2p.ts
- test/circuit/utils.ts
- test/dialing/resolver.spec.ts
- test/peer-discovery/index.node.ts
The connection manager's `autoDial` option originally meant "dial every peer we discover".  Then it changed to "if we have fewer than `minConnections`, dial peers from the peer store until we have more than `minConnections`".
This is confusing and also redundant, since if we don't want to dial peers to ensure we have more than `minConnections` we can just set `minConnections` to `0`.
Adds a section to the upgrade guide covering the removal.
Also fixes a bug where we actually configured two autodialer components.
> fix!: remove connection manager autodial option

- doc/GETTING_STARTED.md
provide instructions for users using node/browser debugging
> docs(getting_started): add debugging info

- src/circuit/transport/reservation-store.ts
- src/circuit/utils.ts
- test/circuit/utils.spec.ts
This fixes #1635 which causes the circuit relay to repeatedly connect to a discovered relay. If the relay returns connection expiration in seconds, we get a negative ttl when calculating
`expiration - new Date().getTime()`.
This caused the `addRelay` function to set the timeout at 0ms. This timeout instantly triggers and calls `addRelay` recursively.
> fix: interpret circuit relay expiry as seconds

- src/connection-manager/index.ts
- test/connection-manager/index.spec.ts
> fix: Connections to Allow list peers will not be pruned

- src/connection-manager/dialer/index.ts
Partial revert of #1649 but prevents the node from appending the peer id to path multiaddrs.
> fix: remove duplicated peer id logic

- src/connection-manager/index.ts
fixes https://github.com/libp2p/js-libp2p/issues/1665
> fix:  ensure to check for Infinity in checkMaxLimit function

- src/connection-manager/index.ts
- src/libp2p.ts
https://github.com/libp2p/js-libp2p-interfaces/pull/351 has been merged so these comments can be removed.
> chore: remove ts-expect-errors

- package.json
- src/connection-manager/index.ts
- src/libp2p.ts
Given we have added these types to the interfaces we can update the imports 
Related: https://github.com/libp2p/js-libp2p-interfaces/pull/374 and https://github.com/libp2p/js-libp2p-interfaces/pull/371
> chore: update imports and remove unnecessary pending dial interfaces

- src/connection-manager/auto-dial.ts
- test/connection-manager/auto-dial.spec.ts
When selecting peers to auto-dial, exclude peers we are already connected to in order to not swamp the dial queue with pointless dials.  This reduces the amount of work browsers in particular have to do.
> fix: do not auto-dial connected peers

- src/transport-manager.ts
- test/transports/transport-manager.node.ts
When a listener closes, remove it from the stored list of listeners.
This wasn't much of a problem before as listeners tended to be very long lived but circuit relay listeners get closed all the time so this fixes a now much more obvious memory leak.
> fix: remove closed listeners from transport manager

- src/circuit-relay/server/index.ts
- src/circuit-relay/transport/discovery.ts
- src/circuit-relay/transport/index.ts
- src/circuit-relay/transport/listener.ts
- src/circuit-relay/transport/reservation-store.ts
Fixes a bug whereby receiving a circuit relay address would cause js-libp2p to try to listen on the non-relayed parts of the address.  For example if a relay listening on a WebTransport multiaddr was dialled, js-libp2p would then try to listen on the same address due to the relay reservation store calling `transportManager.listen` with the full address.  This would then fail and the relaying would not succeed.
The fix is to call `transportManager.listen` with a multiaddr that just has the peer id and the `p2p-circuit` segments so only the relay transport tries to use the address.
For safety if listening on an address or writing to the peer store fails while creating a relay reservation, remove the reservation from the reservation store to allow us to try again.
Also updates logging to …
> fix: listen on circuit relay addresses that contain unsupported segments

- doc/migrations/v0.44-v0.45.md
- src/autonat/constants.ts
- src/autonat/index.ts
- src/upnp-nat/index.ts
- test/autonat/index.spec.ts
- test/upnp-nat/upnp-nat.node.ts
Refactors exports for autonat and upnp-nat to be consistent with other services - fetch, ping, identify, etc.
> fix: update autonat and upnp-nat services to match fetch etc

- src/connection-manager/dial-queue.ts
Prevents spurious warnings appearing in the console.
> fix: increase dial queue shutdown controller signal max listeners

- package.json
The default agent version is pulled from `version.ts` which is updated before publish.  This is because dynamically reading from the `package.json` file would cause it to get included in the browser bundle and requires code contortions in ESM.
`version.ts` is updated in a `prepublishOnly` script to prevent PRs changing this file accidentally, the fix here is to rebuild the ts files after updating the version number, otherwise the published verison is still going to be `0.0.0`.
> fix: build after updating version.ts

- src/address-manager/index.ts
- src/address-manager/utils.ts
- src/transport-manager.ts
- test/addresses/address-manager.spec.ts
- test/addresses/addresses.node.ts
- test/connection-manager/direct.node.ts
- test/connection-manager/index.node.ts
- test/upnp-nat/upnp-nat.node.ts
Refactors the transport manager to just start and stop transports.
Now the address manager is responsible for writing addresses into the peer store.
Debounces writes to the peer store so we don't get lots of `self:peer:update` events on startup as each transport starts to listen on configured addresses.
> fix: make address manager responsible for addresses

- src/connection-manager/auto-dial.ts
This appears in the logs frequently and isn't much use.
> fix: trace happy path connection count message

- test/identify/service.node.ts
Ensure identify is run on both inbound and outbound connections.
> test: add test for inbound and outbound identify

- src/circuit-relay/transport/index.ts
- test/circuit-relay/relay.node.ts
If a dial to a relayed address fails, e.g. with status `NO_RESERVATION`, the newly created `/libp2p/circuit/relay/0.2.0/hop` stream is **never closed**. This can be particularly bad if the connection manager keeps auto-dialing the address, since the streams just accumulate until they hit the max per-protocol stream limit (64). I believe this is the ultimate issue behind [#1695](https://github.com/libp2p/js-libp2p/issues/1695).
I don't know whether closing or aborting the stream is more correct, or if it's important to catch potential exceptions in `await relayConnection.newStream` call, so this may need a little revision from someone with more context.
Also, I know that you typically want PRs to include tests covering the fix - I gave it a couple tries but couldn't figure out how to set …
> fix: close circuit-relay streams on connection failure

- package.json
- src/libp2p.ts
- test/core/events.spec.ts
Add `start` and `stop` events when a node starts or stops.
> fix: add start/stop events

- src/registrar.ts
- test/registrar/registrar.spec.ts
Refactors the registrar to use `peer:connect` and `peer:disconnect` events instead of `connection:open` and `connection:close`.
The connection events are too low-level for the purpose and can cause a race condition when multiple multiaddrs are dialed at the same time.
When this happens the first connection survives and others are closed but their corresponding `connection:open` event has already fired.
Interested parties registering topologies have their onConnect event invoked with the soon-to-be-closed connection.
The `peer:connect` event happens later in the lifecycle by which point the extra connection has been closed.
> fix: use peer events in registrar

- packages/libp2p/src/circuit-relay/transport/index.ts
Each incoming relayed connection uses a libp2p stream on the connection - we already allow the user to configure the number of HOP streams (e.g. local client to relay) this PR allows configuring the number of STOP strems (e.g. relay to remote client)
Default the values to the default max connections so all connections can be relayed connections.
> fix: expose config for max inbound/outbound stop streams

- packages/libp2p/package.json
- packages/libp2p/src/circuit-relay/server/index.ts
- packages/libp2p/src/circuit-relay/transport/index.ts
- packages/libp2p/src/upgrader.ts
- packages/libp2p/test/upgrading/upgrader.spec.ts
To allow overriding the default maximum outbound streams for a protocol when it's not been specified in a handler, allow passing it as an option when opening a new outbound stream.
> fix: allow specifiying maxOutboundStreams in connection.newStream

- packages/interface-pubsub-compliance-tests/src/utils.ts
This is necessary to emit events from components
> fix: add events bus to pubsub compliance tests

- doc/GETTING_STARTED.md
Related https://github.com/libp2p/js-libp2p/issues/1776
> docs: add ESM section to avoid configuration issues

- interop/Dockerfile
Otherwise the tests can't find the modules. Addresses some parts of https://github.com/libp2p/js-libp2p/issues/824
> fix: copy monorepo packages to multidim docker image

- interop/chromium-version.json
- interop/firefox-version.json
Following the discussion [here](https://github.com/libp2p/js-libp2p/issues/1809#issuecomment-1599357723) we need to investigate why webRTC tests are inconsistent. 
Closes #1809
> test: temporarily remove webRTC tests 

- packages/interface/package.json
- packages/interface/src/pubsub/index.ts
Adds interfaces from `@libp2p/interface-pubsub` to `/pubsub` export
> fix: add pubsub interfaces to @libp2p/interface

- packages/libp2p/package.json
`nat-api` isn't used by this module any more.
> fix: remove redundant nat-api override

- packages/transport-webrtc/src/private-to-public/sdp.ts
- packages/transport-webrtc/test/sdp.spec.ts
Closes https://github.com/libp2p/js-libp2p/issues/1908
> fix: update max message size SDP attribute

- packages/transport-webrtc/.aegir.js
- packages/transport-webrtc/package.json
- packages/transport-webrtc/src/private-to-private/handler.ts
- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/src/private-to-private/util.ts
- packages/transport-webrtc/src/private-to-public/transport.ts
- packages/transport-webrtc/src/webrtc/index.browser.ts
- packages/transport-webrtc/src/webrtc/index.ts
- packages/transport-webrtc/src/webrtc/rtc-data-channel.ts
- packages/transport-webrtc/src/webrtc/rtc-events.ts
- packages/transport-webrtc/src/webrtc/rtc-ice-candidate.ts
- packages/transport-webrtc/src/webrtc/rtc-peer-connection.ts
- packages/transport-webrtc/src/webrtc/rtc-session-description.ts
- packages/transport-webrtc/test/listener.spec.ts
- packages/transport-webrtc/test/maconn.browser.spec.ts
- packages/transport-webrtc/test/peer.browser.spec.ts
- packages/transport-webrtc/test/stream.browser.spec.ts
Uses [node-datachannel](https://www.npmjs.com/package/node-datachannel) to add support for node.js and electron (main process) to @libp2p/webrtc.
Supports:
- Dialing private-to-private
- Listening private-to-private
- Dialing private-to-public
Does not support:
- Listening private-to-public
> feat: add node.js/electron support for webrtc transport

- .github/workflows/main.yml
These are needed to publish to the gh-pages branch.
> fix: add gh credentials to publish docs

- packages/interface/src/stream-muxer/stream.ts
Check the stream timeline for closeWrite/closeRead to make sure we don't send multiple close messages.
> fix: do not send duplicate close read/write

- packages/interface-compliance-tests/package.json
- packages/interface-compliance-tests/src/connection/index.ts
- packages/interface-compliance-tests/src/mocks/connection.ts
- packages/interface/src/connection/index.ts
- packages/libp2p/src/connection/index.ts
- packages/libp2p/src/upgrader.ts
- packages/libp2p/test/connection/compliance.spec.ts
remove (add|remove)Stream from connection interface
remove (add|remove)Stream use from interface-compliance-tests
remove (add|remove)Stream from libp2p connection methods
remove (add|remove)Stream from libp2p upgrader methods
Closes #1855
> fix: remove stream add/remove methods from connection interface

- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/test/connection-manager/dial-queue.spec.ts
- packages/libp2p/test/connection-manager/direct.spec.ts
Some multiaddrs like `/dnsaddr/bootstrap.ipfs.io` resolve to multiple PeerIds.
E.g:
```console
% dig _dnsaddr.bootstrap.libp2p.io TXT
; <<>> DiG 9.10.6 <<>> _dnsaddr.bootstrap.libp2p.io TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53473
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;_dnsaddr.bootstrap.libp2p.io.	IN	TXT
;; ANSWER SECTION:
_dnsaddr.bootstrap.libp2p.io. 261 IN	TXT	"dnsaddr=/dnsaddr/am6.bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
_dnsaddr.bootstrap.libp2p.io. 261 IN	TXT	"dnsaddr=/dnsaddr/ny5.bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa"
_dnsaddr.bootstrap.libp2p.io. 261 …
```
> fix(libp2p): filter out dnsaddrs for different peers

- packages/utils/package.json
- packages/utils/src/ip-port-to-multiaddr.ts
- packages/utils/test/ip-port-to-multiaddr.spec.ts
The `@achingbrain/ip-address` module is a fork of `ip-address` which seems to have dependencies on older modules that break modern runtimes like react native.
`@Chainsafe/is-ip` does not have these limitations so switch to that.
Fixes #1926
> fix(@libp2p/utils): switch to @chainsafe/is-ip

- packages/crypto/src/aes/index.ts
- packages/crypto/src/ciphers/aes-gcm.browser.ts
- packages/crypto/src/ciphers/aes-gcm.ts
- packages/crypto/src/hmac/index-browser.ts
- packages/crypto/src/hmac/index.ts
- packages/crypto/src/keys/ecdh.ts
- packages/crypto/src/keys/ed25519-class.ts
- packages/crypto/src/keys/index.ts
- packages/crypto/src/keys/rsa-class.ts
- packages/crypto/src/keys/rsa.ts
These eslint-disable-line comments are no longer needed.
They were added ~3 years ago and do not affect current linting rules.
provenance: https://github.com/libp2p/js-libp2p/commit/7273739f045b33a46aae45f5003dd09f7ea6e37e
related: https://github.com/libp2p/js-libp2p/issues/1949
> chore: remove require-await comments in libp2p/crypto

- packages/interface-compliance-tests/package.json
Given that this package is primarily responsible for testing, I think that `aegir` is required as a dependency to utilize it properly.
Closes #1974
> fix(@libp2p/interface-compliance-tests): add aegir to deps

- packages/libp2p/src/autonat/index.ts
- packages/libp2p/src/upgrader.ts
Removes use of `any-signal` where we only have one signal.
> refactor(libp2p): remove unnecessary any-signal

- packages/libp2p/src/registrar.ts
- packages/libp2p/test/registrar/registrar.spec.ts
When unhandling a protocol, update the peer store entry for the current peer with the correct set of protocols.
> fix(libp2p): update peer store with supported protocols after unhandle

- packages/transport-webtransport/package.json
- packages/transport-webtransport/typedoc.json
This file does not exist in this project so remove it from the exports map.
> fix(@libp2p/webtransport): remove filters export

- packages/peer-discovery-mdns/package.json
- packages/peer-discovery-mdns/src/index.ts
- packages/peer-discovery-mdns/src/query.ts
- packages/peer-discovery-mdns/test/compliance.spec.ts
- packages/peer-discovery-mdns/test/multicast-dns.spec.ts
The data field of mDNS TXT records has a [hard limit of 255 characters](https://agnat.github.io/node_mdns/user_guide.html#txt_records) - some multiaddrs can be longer than this so filter them out before sending, otherwise remote peers can fail to parse our mDNS response.
We should also only be sending [link-local addresses](https://github.com/libp2p/specs/blob/master/discovery/mdns.md#issues) in mDNS responses so filter any non-link-local addresses out too, though go-libp2p includes loopback addresses even though it probably shouldn't (according to the mDNS spec which conflicts with our mDNS Peer Discovery spec) so we continue to do so as well.
Fixes #2012
> fix(@libp2p/mdns): do not send TXT records that are too long

- interop/README.md
- interop/package.json
This module is now published as `@libp2p/multidim-interop`.
Closes #2005
> chore: publish multidim interop test module

- packages/libp2p/src/connection-manager/auto-dial.ts
- packages/libp2p/src/connection-manager/constants.defaults.ts
- packages/libp2p/src/connection-manager/index.ts
- packages/libp2p/src/libp2p.ts
To notifiy components that a new peer has been discovered, emit the `peer:discovered` event on the event bus component.
Allows the auto-dialer to choose to dial newly discovered peers immediately instead of waiting for the next autodial interval.
> fix(libp2p): emit peer:discovered event on internal event bus

- packages/transport-webtransport/src/index.ts
- packages/transport-webtransport/src/stream.ts
- packages/transport-webtransport/test/browser.ts
TypeScript has shipped a release with built in WebTransport types so use these instead.
> fix(@libp2p/webtransport): remove custom WebTransport types

- interop/package.json
This whole package should have `aegir` as a dep since it's core functionality is built around testing js-libp2p with `aegir` via the [test command](https://github.com/libp2p/js-libp2p/blob/master/interop/package.json#L49) but especially In order to utilize `aegir` for browser multidim interop testing we should add `aegir` as a dependency here.
Related: https://github.com/libp2p/test-plans/pull/288
> deps(@multidim-interop): add aegir to deps

- .release-please.json
Otherwise releases are not created for changes.
I think this is why #2023 did not create a "release master" issue.
Missed from #2008.
> chore: add interop to release-please config

- packages/libp2p/src/connection-manager/constants.browser.ts
- packages/libp2p/src/connection-manager/constants.defaults.ts
- packages/libp2p/src/connection-manager/constants.ts
- packages/libp2p/src/connection-manager/index.ts
- packages/libp2p/test/circuit-relay/relay.node.ts
- packages/libp2p/test/connection-manager/dial-queue.spec.ts
- packages/libp2p/test/connection-manager/direct.node.ts
- packages/libp2p/test/connection-manager/direct.spec.ts
The observation for dialing is that for a given peer with multiple addresses, for a given class of address (e.g. public or private), either the first dial succeeds or they all fail, so there's not much point dialing all addresses together since in either case you waste resources either cancelling redundant dials or dialing addresses that fail.
We can't do much about dialing addresses that fail but we can reduce the number of redundant dials so with this change we only ever dial one multiaddr at a time.
Refs: #2010
> fix(libp2p): only dial one address at a time for peers

- packages/utils/test/address-sort.spec.ts
Fixes a typo in the address used in the test
> chore(libp2p): correct webrtc multiaddr string

- packages/peer-discovery-mdns/README.md
It's clear from the code that `broadcast` and `serviceTag` defaults are not what docs said https://github.com/libp2p/js-libp2p/blob/5294f14caa314bb150554afff3a7ff45d2bf17ba/packages/peer-discovery-mdns/src/index.ts#L42-L44
> docs(@libp2p/mdns): update mdns defaults in README.md

- packages/transport-webrtc/src/stream.ts
Fixes typo in stream logger name for webrtc transport
> fix(@libp2p/webrtc): update stream logger name to webrtc

- packages/transport-webrtc/src/stream.ts
Streams should use the `this.log` property for logging to ensure the log messages are scoped to an invidual stream.
> fix(@libp2p/webrtc): use stream logger instead of global logger

- packages/transport-webrtc/src/private-to-private/handler.ts
Use the UDP port in the remote address parsed from the last successful ICE candidate.
> fix(@libp2p/webrtc): use correct udp port in remote address

- packages/transport-webtransport/package.json
- packages/transport-webtransport/src/utils/parse-multiaddr.ts
- packages/transport-webtransport/test/browser.ts
- packages/transport-webtransport/test/utils/parse-multiaddr.spec.ts
We should be able to dial WebRTC addresses over Circuit Relay over WebTransport but the `parseMultiaddr` function was rejecting them.
Simplifies the parsing function to handle this and future address variants and adds tests.
> fix(@libp2p/webtransport): handle dialing circuit addresses

- packages/transport-webrtc/package.json
- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/src/private-to-public/transport.ts
- packages/transport-webrtc/test/peer.browser.spec.ts
- packages/transport-webrtc/test/transport.browser.spec.ts
- packages/transport-webtransport/package.json
- packages/transport-webtransport/src/index.ts
- packages/transport-webtransport/test/browser.ts
- packages/transport-webtransport/test/transport.spec.ts
Use exact matchers for filtering webtransport and webrtc addresses so those transports do not try to dial (for example) p2p-circuit addresses, instead leaving the more specific address to other transports.
Refs: https://github.com/ipfs/helia/pull/267
> fix(transports): filter circuit addresses

- packages/libp2p/src/connection-manager/auto-dial.ts
This seems to have been missed.
> fix: include peer id in autodial log message

- packages/transport-websockets/src/socket-to-conn.ts
When gracefully closing a websocket connection fails, log the error to make debugging easier.
> fix: log websocket error on graceful close failure

- packages/interface-compliance-tests/src/mocks/connection.ts
- packages/interface-compliance-tests/src/mocks/index.ts
Adds a `streamPair` convenience function to the interface mocks that returns two `Stream` objects where the duplex streams read/write to/from the other.
> feat: add mock stream pair

- examples/pubsub/message-filtering/README.md
docs: pubsub example topic validator fix
Fixes https://github.com/libp2p/js-libp2p/issues/1394.
topic validators for gossipsub require a specific return type to accept the message.
> docs: pubsub example topic validator fix

- tsconfig.json
> chore: add root tsconfig

- README.md
docs: update README structure and contributing guidelines 
I have  updated the structure of the `README` to be a bit more welcoming by moving monorepo file structure below the ## Project Status. The assumption is that a first time consumer is less interested in the monorepo as opposed to just installing and using the library.
> docs: update README structure 

- packages/interface/src/connection/index.ts
- packages/interface/src/stream-muxer/stream.ts
- packages/transport-webrtc/package.json
- packages/transport-webrtc/src/muxer.ts
- packages/transport-webrtc/src/pb/message.proto
- packages/transport-webrtc/src/pb/message.ts
- packages/transport-webrtc/src/private-to-private/initiate-connection.ts
- packages/transport-webrtc/src/private-to-private/signaling-stream-handler.ts
- packages/transport-webrtc/src/private-to-private/util.ts
- packages/transport-webrtc/src/stream.ts
- packages/transport-webrtc/src/util.ts
- packages/transport-webrtc/test/basics.spec.ts
- packages/transport-webrtc/test/stream.browser.spec.ts
- packages/transport-webrtc/test/stream.spec.ts
- packages/transport-webrtc/test/util.ts
Chrome does not always send all messages after closing a datachannel even if `bufferedAmount` is `0` before closing.
This PR adds a `FIN_ACK` message that is sent in reply to a `FIN` message - because all messages are send in-order, when this is received we know the remote has recieved all of our data messages and it's safe to close the channel.
- Depends on
> fix: close webrtc streams

- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/test/connection-manager/auto-dial.spec.ts
- Remove the confusing "dialler" word in metrics, replacing with "dial_queue"
> fix!: remove dialler language

- packages/interface/src/topology/index.ts
Once upon a time these options were intended to cause libp2p to close connections or search for more peers that support a given protocol but it was never implemented.
Remove the options since they don't do anything, they may be restored in future if the functionality is ever required.
> fix!: remove min/max from topologies

- packages/interface-compliance-tests/src/mocks/peer-discovery.ts
- packages/interface/src/peer-info/index.ts
- packages/kad-dht/src/content-routing/index.ts
- packages/kad-dht/src/kad-dht.ts
- packages/kad-dht/src/message/index.ts
- packages/kad-dht/src/peer-routing/index.ts
- packages/kad-dht/src/rpc/handlers/find-node.ts
- packages/kad-dht/src/rpc/handlers/get-providers.ts
- packages/kad-dht/test/kad-utils.spec.ts
- packages/kad-dht/test/query-self.spec.ts
- packages/kad-dht/test/query.spec.ts
- packages/kad-dht/test/rpc/handlers/add-provider.spec.ts
- packages/kad-dht/test/rpc/handlers/find-node.spec.ts
- packages/kad-dht/test/rpc/handlers/get-providers.spec.ts
- packages/kad-dht/test/rpc/handlers/get-value.spec.ts
- packages/kad-dht/test/utils/test-dht.ts
- packages/libp2p/src/libp2p.ts
- packages/libp2p/test/circuit-relay/utils.ts
- packages/libp2p/test/content-routing/content-routing.node.ts
- packages/peer-discovery-bootstrap/src/index.ts
- packages/peer-discovery-mdns/src/query.ts
A [PeerInfo](https://docs.libp2p.io/concepts/fundamentals/peers/#peer-info) is a libp2p object that combines a PeerID and some Multiaddrs.
We also add a list of protocols. This was a mistake because protocols are exchanged during Identify but the PeerInfo object is used for peer discovery.
This is evident because we set the protocol list to an empty array everywhere.
PeerInfo is useful for exchanging peer data with other nodes, if we need a more fleshed-out peer representation we'd use the `Peer` interface from the peer store.
BREAKING CHANGE: the `.protocols` property has been removed from the `PeerInfo` interface
> fix!: remove protocols from PeerInfo

- packages/kad-dht/src/index.ts
This needs to be exported for reuse by things that create DHT records such as IPNS.  Previously it was imported from the `@libp2p/record` module.
Exported as `Record` because it's a KAD-DHT specific record and `KAD-DHT` in a class name is redundant within the scope of the KAD-DHT module.
> fix: export DHT record class

- packages/kad-dht/src/dual-kad-dht.ts
- packages/kad-dht/src/query-self.ts
- packages/kad-dht/src/record/selectors.ts
- packages/kad-dht/src/record/validators.ts
- packages/kad-dht/test/record/selection.spec.ts
- packages/kad-dht/test/record/validator.spec.ts
When we run our first self-query we first check the routing table to see if it has peers.
If not we wait for some peers to be discovered before continuing.
The change here is to use the general query AbortSignal to abort waiting for peers to be discovered.  If they are not discovered allow other queries to continue and fail with eaiser to understand error messages.
Also fixes some logging typos and makes error messages more understandable.
> fix: allow DHT self-query to time out

- .github/workflows/main.yml
Add the interop output dirs to the npm/build cache
> chore: cache interop build files

- packages/interface/package.json
- packages/interface/src/events.browser.ts
- packages/interface/src/events.ts
- packages/kad-dht/package.json
- packages/kad-dht/src/query-self.ts
- packages/kad-dht/src/query/manager.ts
- packages/libp2p/package.json
- packages/libp2p/src/autonat/index.ts
- packages/libp2p/src/circuit-relay/server/index.ts
- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/src/connection-manager/utils.ts
- packages/libp2p/src/connection/index.ts
- packages/libp2p/src/fetch/index.ts
- packages/libp2p/src/identify/identify.ts
- packages/libp2p/src/libp2p.ts
- packages/libp2p/src/upgrader.ts
- Discussed in https://github.com/libp2p/js-libp2p/discussions/2138
- Move `setMaxListeners` handling into a single wrapped function exported from `@libp2p/interface/events`
- Instead of setting `"browser": {"events": false}` as was discussed in #2138, an actual file is given. Without doing this, an annoying warning is produced in this package and every consumer package in the monorepo!
> refactor: move setMaxListeners to @libp2p/interface

- packages/libp2p/src/dcutr/dcutr.ts
- packages/libp2p/src/dcutr/utils.ts
- packages/libp2p/test/dcutr/utils.spec.ts
In order to get a better view on testing DCUtR, split the utility functions out to test them separately starting with `isPublicAndDialable`.
> refactor: extract DCUtR utils

- packages/libp2p/test/interop.ts
- packages/pubsub/src/index.ts
When opening outbound streams, only make sure no outbound pubsub streams exist on the connection, not just any pubsub streams.
Improves logging:
- Disables autodial during interop tests to make logs quieter
- Makes logging why we can't send an RPC message to a peer clearer
Fixes a race condition where the remote peer can open streams before us which then prevents us opening streams.
> chore: fix pubsub interop tests

- packages/libp2p/src/circuit-relay/transport/listener.ts
- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/src/connection-manager/index.ts
- packages/libp2p/test/connection-manager/index.spec.ts
If we dial a peer that we already have a connection to, we return that connection instead of dialing.
This creates a problem when we are trying to make a direct connection to a peer that we already have a relay connection to since the relay connection is returned.
The fix here is to allow additional dials to peers when we only have relay connections.
If a direct connection exists, we will still return it instead of dialing.
> fix: allow dialing a peer when we only have transient connections

- packages/libp2p/src/identify/identify.ts
- packages/libp2p/test/identify/index.spec.ts
During identify-push in response to a protocol update go-libp2p does not send a signed peer record or the current list of listen addresses.
This manifests in intermittent interop test failures where we have no valid addresses for a dial, when we dial a peer ID after adding multiaddrs for it to the peer store.
Protobuf does not let us differentiate between an empty list and no list items at all because the field is just `repeated` - an absence of repeated fields doesn't mean the list was omitted.
> fix: do not overwrite addresses on identify push when none are sent

- packages/libp2p/src/identify/identify.ts
When logging peer data, pass the peer id and the update to the logger instead of just the update values, otherwise the values get logged as `[object Object]`.
> fix: log peer data in identify correctly

- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/test/connection-manager/dial-queue.spec.ts
Some transports like WebRTC require the target peer id to be present on the multiaddr, so append the peer id before filtering by supported transport.
> fix: append peer id to dial addresses before filtering

- packages/transport-webrtc/src/private-to-private/initiate-connection.ts
- packages/transport-webrtc/src/private-to-private/signaling-stream-handler.ts
- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/src/private-to-private/util.ts
- packages/transport-webrtc/test/basics.spec.ts
- packages/transport-webrtc/test/peer.browser.spec.ts
Updates the reported remote address of webrtc connections to be the address that was dialed, so it can be treated as an opaque value and shared with other interested parties.
The recipient remote address is just `/webrtc/p2p/QmInitiator` as there is no guarantee that the intiator has a reservation anywhere.
> fix: make initiator webrtc address dialable

- packages/libp2p/src/identify/identify.ts
- packages/libp2p/src/upgrader.ts
- packages/libp2p/test/identify/index.spec.ts
Some addresses are not naturally routable - for example incoming webrtc addresses, so do not send them as observed addresses in identify responses.
> fix: only send ip/domain observed address in identify

- packages/transport-webrtc/src/muxer.ts
- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/src/stream.ts
A race condition exists where a remote can start opening streams over WebRTC before we have finished the connection upgrade.
When this happens we need to be able to gracefully close the stream the same as ones opened after the upgrade.
This PR makes the action taken on stream close reconfigurable after the muxer factory has been created.
> fix: close early WebRTC streams properly

- packages/transport-webrtc/src/muxer.ts
Fixes regession introduced by #2200
> fix: datachannel label should be an empty string

- packages/transport-webrtc/src/muxer.ts
- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/test/muxer.spec.ts
The datachannel muxer is created during set up of the `Connection` object.  If we notify of early stream creation before the `Connection` object is properly configured, the early streams will be lost.
This can happen when the remote opens a data channel before the local node has finished setting up it's end of the connection.
The fix is to notify asynchronously which gives the upgrader enough time to finish setting up the `Connection`.
> fix: delay notification of early WebRTC stream creation

- packages/interface/src/index.ts
- packages/libp2p/src/components.ts
- packages/libp2p/src/connection-manager/auto-dial.ts
- packages/libp2p/src/connection-manager/connection-pruner.ts
- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/src/connection-manager/index.ts
- packages/libp2p/src/connection-manager/utils.ts
- packages/libp2p/src/connection/index.ts
- packages/libp2p/src/identify/identify.ts
- packages/libp2p/src/identify/index.ts
- packages/libp2p/src/index.ts
- packages/libp2p/src/libp2p.ts
- packages/libp2p/src/upgrader.ts
- packages/libp2p/test/connection-manager/auto-dial.spec.ts
- packages/libp2p/test/connection-manager/dial-queue.spec.ts
- packages/libp2p/test/connection-manager/index.spec.ts
- packages/libp2p/test/connection/compliance.spec.ts
- packages/libp2p/test/connection/index.spec.ts
- packages/logger/src/index.ts
- packages/logger/src/utils.ts
- packages/logger/test/index.spec.ts
- packages/logger/test/utils.spec.ts
When running multiple libp2p instances simultaneously it's often hard to work out which log messages come from which instance. This PR solves the problem.
- Adds a `ComponentLogger` interface to libp2p which is an object that lets a component get a logger specific to that component.
- Adds an optional `logger` config key to libp2p which is an implementation of `ComponentLogger`.
- Adds three implementations of `ComponentLogger`
- `defaultLogger` - this preserves existing logging behaviour
- `peerLogger` - this prefixes all log lines with a truncated peer id
- `prefixLogger` - this prefixes all log lines with an arbitrary string
`libp2p` uses the passed logger if one is configured, otherwise it uses `defaultLogger` to make this change backwards compatible.
The logger is added to the …
> feat: add component logger

- packages/kad-dht/src/query/manager.ts
- packages/libp2p/src/connection/index.ts
- packages/libp2p/src/identify/identify.ts
- packages/libp2p/src/ping/index.ts
- packages/libp2p/src/upgrader.ts
- packages/protocol-perf/src/perf-service.ts
- packages/transport-tcp/src/socket-to-conn.ts
- packages/transport-websockets/src/socket-to-conn.ts
Where we set a default abort signal for an operation, copy the incoming options object instead of overwriting the property as sometimes a user will reuse the options object they have passed in and be surprised when a signal that they didn't set aborts a subsequent operation.
> fix: do not overwrite signal property of options

- packages/libp2p/test/ping/ping.node.ts
The ping tests run over transient connections which can hit relay limits.
Instead listen on tcp connections so the tests only run over direct connections.
> chore: fix ping tests

- packages/kad-dht/package.json
- packages/kad-dht/src/query/query-path.ts
- packages/kad-dht/src/query/utils.ts
- packages/kad-dht/test/query/utils.spec.ts
If a DHT query is aborted during reading, the deferred promise can become rejected while nothing is `await`ing it.
Switch the implementation to use a `pushable` queue instead.
Fixes #2216
> fix: crash during DHT query abort when reading is slow

- doc/migrations/v0.46-v1.0.0.md
- packages/protocol-perf/README.md
- packages/protocol-perf/src/index.ts
- packages/protocol-perf/src/perf-service.ts
- packages/protocol-perf/test/index.spec.ts
Removes the redundant `Service` from perf exports in line with other changes to modules in v1.
BREAKING CHANGE: the `perfService` export is now just `perf`
> refactor!: rename perf exports to remove Service

- packages/stream-multiplexer-mplex/test/fixtures/utils.ts
- packages/stream-multiplexer-mplex/test/stream.spec.ts
The timing has changed on these tests has changed to do a release of `it-foreach` which now does not introduce artificial async when calling the each method.
> chore: fix mplex tests

- packages/utils/src/stream-to-ma-conn.ts
Ensure the .close timeline property is set correctly after the sink/source for the stream have both finished.
> fix: close maconn stream after reading/writing

- packages/transport-tcp/src/index.ts
- packages/transport-tcp/src/utils.ts
Allow specifying default socket options to `net.connect` and `net.createServer` - this allows users to turn keep alive, tcp delays, etc on/off as per their individual requirements.
```js
tcp({
socket: {
// net.connect options here
},
server: {
// net.createServer options here
}
})
```
> feat: support default options for tcp sockets/servers

- packages/transport-tcp/src/index.ts
- packages/transport-tcp/src/listener.ts
By default Node.js enables Nagle's algorithm. This adds a small delay when sending tiny buffers to batch-send them later.
Unfortunately this makes protocol negotiation slower as the protocol strings are small enough to be batch sent.
The change here is to turn it off by default, this reduces the perf test connection establisment from 1.2s to 0.8s.
See the latency measurements in the "Connection Establishment" test [on this run](https://observablehq.com/@libp2p-workspace/performance-dashboard?branch=cac8364ac83a4d8856851687a605e50b1e3855fb) for an example.
#2241 will let users turn this back on if they need it.
> fix: disable Nagle's algorithm by default

- packages/libp2p/src/upgrader.ts
- packages/multistream-select/package.json
- packages/multistream-select/src/handle.ts
- packages/multistream-select/src/index.ts
- packages/multistream-select/src/select.ts
- packages/multistream-select/test/integration.spec.ts
- packages/multistream-select/test/multistream.spec.ts
Updates the multistream lazy select to support lazy select on streams that are only read from.
> fix: allow mss lazy select on read

- packages/interface/src/events.ts
- packages/peer-discovery-mdns/src/mdns.ts
All code should be using `TypedEventEmitter` instead of `EventEmitter` so remove the re-export from the interfaces package.
BREAKING CHANGE: removed EventEmitter re-export - please use TypedEventEmitter instead
> fix!: remove event emitter type from interfaces

- packages/crypto/package.json
- packages/crypto/src/keys/ed25519-browser.ts
- packages/crypto/src/keys/ed25519-class.ts
- packages/crypto/src/keys/ed25519.ts
- packages/crypto/src/keys/rsa-browser.ts
- packages/crypto/src/keys/rsa-class.ts
- packages/crypto/src/keys/rsa.ts
- packages/crypto/src/keys/secp256k1-browser.ts
- packages/crypto/src/keys/secp256k1-class.ts
- packages/crypto/test/keys/ed25519.spec.ts
- packages/crypto/test/keys/rsa.spec.ts
- packages/crypto/test/keys/secp256k1.spec.ts
- packages/interface/src/keys/index.ts
Accept `Uint8ArrayList`s as arguments to sign or verify and use streaming hashes internally when they are passed (if supported). This way we can skip having to copy the `Uint8ArrayList` contents into a `Uint8Array` first.
> feat: support streaming hashes for key sign/verify

- packages/crypto/src/keys/ed25519-class.ts
- packages/crypto/src/keys/rsa-class.ts
- packages/crypto/src/keys/secp256k1-browser.ts
- packages/crypto/src/keys/secp256k1-class.ts
- packages/crypto/src/keys/secp256k1.ts
- packages/crypto/src/util.ts
- packages/crypto/test/helpers/test-garbage-error-handling.ts
- packages/crypto/test/keys/ed25519.spec.ts
- packages/crypto/test/keys/secp256k1.spec.ts
- packages/interface/src/keys/index.ts
Removes unnecessary async from Ed/Secp keys sign/verify methods.
Ed is sync everywhere, Secp is sync in node but async in browsers.
Follow up to #1963
> fix: allow keys to do sync sign/verify

- .github/workflows/examples.yml
- .release-please.json
- packages/multistream-select/src/handle.ts
- packages/multistream-select/src/multistream.ts
- packages/multistream-select/src/select.ts
Check logger is present before use.  This should have gone out as a breaking change.
> fix: make mss check logger before use

- packages/interface/src/index.ts
- packages/libp2p/src/libp2p.ts
- packages/libp2p/test/core/status.node.ts
To tell if the node has been started or not.
> fix: add status property

- packages/libp2p/package.json
To allow consumers to programatically report the version of libp2p that is running, export the version file.
> fix: export version from libp2p

- packages/libp2p/src/upgrader.ts
To give more scope of where operations are taking place, use the connection logger to log messages about the upgrade process.
> fix: log upgrade messages on connection

- packages/interface-internal/src/registrar/index.ts
- packages/interface-internal/src/transport-manager/index.ts
To allow following semver on `@libp2p/interface-internal`, release as v1.
Release-As: 1.0.0
> fix: update interface internal and release as v1

- packages/multistream-select/src/handle.ts
- packages/multistream-select/src/multistream.ts
- packages/multistream-select/src/select.ts
- packages/multistream-select/test/multistream.spec.ts
- packages/peer-collections/src/index.ts
- packages/peer-id-factory/src/index.ts
- packages/peer-record/src/index.ts
- packages/peer-store/src/index.ts
- packages/pubsub-floodsub/src/index.ts
- packages/pubsub/src/index.ts
Pre-v1.0 versions of libp2p are still depending on post-1.0 modules which means they have a mixed set of versions.
The change here is to cause those modules to have major releases.
BREAKING CHANGE: requires libp2p v1
> fix!: release majors of modules that had patches during v1.0

- packages/libp2p/src/libp2p.ts
In order to stop components that have been started during a failed startup, set the current status to started after catching the error - `this.stop` will immediately set it to `stopping`.
> fix: set libp2p status to started before stopping

- packages/libp2p/src/connection-manager/auto-dial.ts
There's no need to set a timeout for autodialing during `.start` since we autodial during `.afterStart` which will then set the timeout for the next dial if one is required.
We guard on running twice so this isn't a problem, it's just unecessary.
> fix: remove duplicate autodial from startup

- packages/libp2p/src/config.ts
- packages/libp2p/src/content-routing/index.ts
- packages/libp2p/src/errors.ts
There are times where a node could be configured with no transports, for example if it is going to do all of it's work via delegates.
Removes the check for at least one transport module being configured.
> fix: allow no transports in config

- packages/libp2p/test/core/core.spec.ts
No need to pass an empty init object
> chore: remove empty object from test

- packages/peer-collections/package.json
- packages/peer-collections/src/index.ts
- packages/peer-collections/src/list.ts
- packages/peer-collections/src/map.ts
- packages/peer-collections/src/set.ts
- packages/peer-collections/src/tracked-list.ts
- packages/peer-collections/src/tracked-map.ts
- packages/peer-collections/src/tracked-set.ts
- packages/peer-collections/test/tracked-list.spec.ts
- packages/peer-collections/test/tracked-map.spec.ts
- packages/peer-collections/test/tracked-set.spec.ts
Adds peer collections that report their sizes to the libp2p metrics service.
> feat: add versions of peer lists/sets/maps that report their sizes

- packages/transport-webrtc/package.json
- packages/transport-webrtc/src/private-to-private/initiate-connection.ts
- packages/transport-webrtc/src/private-to-private/listener.ts
- packages/transport-webrtc/src/private-to-private/signaling-stream-handler.ts
- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/src/private-to-private/util.ts
- packages/transport-webrtc/test/peer.spec.ts
Simplifies the connection logic to just use the abort signal to abort the dial instead of the abort signal and multiple deferred promises.
Fixes a crash in node where the abort signal passed into a WebRTC private to private dial can cause an unhandled promise rejection due to a race condition between the abort firing and awaiting the `connectedPromise` promise:
```
file:///Users/alex/Documents/Workspaces/ipfs/helia-http-gateway/node_modules/@libp2p/webrtc/dist/src/private-to-private/initiate-connection.js:42
connectedPromise.reject(new CodeError('SDP handshake aborted', 'ERR_SDP_HANDSHAKE_ABORTED'));
^
CodeError: SDP handshake aborted
at EventTarget.sdpAbortedListener (file:///Users/alex/Documents/Workspaces/ipfs/helia-http-gateway/node_modules/@libp2p/webrtc/dist/src/private-to-private/in …
```
> fix: WebRTC transport unhandled promise rejection during connect

- packages/transport-webrtc/src/private-to-private/initiate-connection.ts
- packages/transport-webrtc/src/private-to-private/signaling-stream-handler.ts
- packages/transport-webrtc/test/peer.spec.ts
We catch WebRTC errors, log them and throw normalised errors to ensure they are the same across WebRTC stacks (FF, Chrome, node).
#2299 made one of these operations async which would cause an UHPR if thrown.
> fix: WebRTC uncaught promise rejection on incoming connection

- packages/utils/package.json
- packages/utils/src/peer-job-queue.ts
- packages/utils/src/stream-to-ma-conn.ts
- packages/utils/test/peer-job-queue.spec.ts
When we have a PeerJobQueue, the jobs are usually expensive but the result is transferable - opening a connection, etc.
This PR adds a `joinJob` method to `PeerJobQueue` - if a job is queued for the passed `PeerId`, a promise is returned that resolves/rejects based on the outcome of the job.
> feat: allow joining jobs in peer queues

- packages/multistream-select/package.json
- packages/multistream-select/src/select.ts
- packages/multistream-select/test/integration.spec.ts
When we are doing optimistic protocol selection and we send a small amount of data then immediately close the stream, if necessary wait until we have finished sending protocol+data before allowing the underlying stream to close.
> fix: graceful close of optimistic selection with early data

- packages/utils/src/peer-job-queue.ts
- packages/utils/test/peer-job-queue.spec.ts
After clearing jobs, the results map should be empty.
> fix: remove results map on job queue clear

- packages/transport-circuit-relay-v2/src/transport/discovery.ts
- packages/transport-circuit-relay-v2/src/transport/reservation-store.ts
- packages/transport-circuit-relay-v2/src/transport/transport.ts
This should be done in the `afterStart` method otherwise the DHT query manager may not have been started yet.
> fix: query for circuit relays after start

- packages/integration-tests/test/lifecycle.spec.ts
- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/src/connection-manager/index.ts
When a node is stopped and started we need to reset the dial queue shutdown controller otherwise every dial attempt after a restart will be rejected as the shutdown controller signal is still aborted.
Fixes #2188
> fix: reset dial queue shut down controller on node restart

- packages/interface/src/peer-id/index.ts
- packages/peer-id/src/index.ts
- packages/peer-id/test/index.spec.ts
This makes the code a bit more flexible, for example when taking action based on an optional peerid having been passed to a function when an existing peer id is known.
> fix: make peerid optional in peerid.equals

- packages/transport-websockets/test/node.ts
The types for it-goodbye have become less permissive.
> fix: update websockets tests

- packages/interface-compliance-tests/src/mocks/metrics.ts
These `??` operators should be `||`, fixes an eslint warning about suspicious nullish coalescing operator usage.
> chore: fix MockMetrics eslint warning

- packages/kad-dht/package.json
- packages/kad-dht/src/query/manager.ts
- packages/kad-dht/test/query.spec.ts
If query results are consumed from a `for await..of`-style loop, and that loop is exited from before the results are complete, ensure we abort any running sub-queries.
> fix: ensure dht query is aborted on early exit

- packages/utils/package.json
- packages/utils/src/tracked-list.ts
- packages/utils/test/tracked-list.spec.ts
- packages/utils/typedoc.json
To allow tracking sizes of internal lists using libp2p metrics, add a tracked list type simmilar to tracked map.
> feat: add tracked list to utils

- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/src/connection-manager/index.ts
- packages/libp2p/src/content-routing.ts
- packages/libp2p/src/peer-routing.ts
- packages/libp2p/test/connection-manager/auto-dial.spec.ts
- packages/libp2p/test/connection-manager/dial-queue.spec.ts
- packages/libp2p/test/connection-manager/direct.node.ts
- packages/libp2p/test/connection-manager/index.spec.ts
- packages/libp2p/test/fixtures/matchers.ts
- packages/libp2p/test/registrar/registrar.spec.ts
A recent change to go-libp2p started yielding peers with no multiaddrs during DHT queries.
These peer ids have addresses that can be found during a find peer query but performing this query for every peer is expensive, so do the lookup only when dialing the peer.
> fix: perform find peer during dial if peer has no multiaddrs

- doc/migrations/v0.46-v1.0.0.md
This was missed from the release notes.
> docs: add note about persisting peer ids in the keychain

- packages/kad-dht/README.md
- packages/kad-dht/src/index.ts
- packages/transport-tcp/README.md
The `addressFilter` init option should be `peerInfoMapper`
> docs: update dht readme

- packages/libp2p/src/libp2p.ts
- packages/libp2p/test/core/get-public-key.spec.ts
Updates the test to assert that the routing is, in fact, queried for a missing RSA public key.
> fix: query routing for RSA public key

- packages/libp2p/package.json
- packages/libp2p/src/connection-manager/index.ts
- packages/stream-multiplexer-mplex/package.json
- packages/stream-multiplexer-mplex/src/mplex.ts
- packages/utils/package.json
- packages/utils/src/rate-limiter.ts
- packages/utils/test/rate-limiter.spec.ts
- packages/utils/typedoc.json
[rate-limiter-flexible](https://npmjs.com/package/rate-limiter-flexible) is a CJS module with a single export of all it's various implementations.
This defeats tree shaking resulting in the addition of 42KB to the bundle size.
https://github.com/animir/node-rate-limiter-flexible/issues/249
This PR brings the source & tests for the in-memory rate limiter into `@libp2p/utils` which reduces the bundle size increase to a few KBs.
> fix: replace rate-limiter

- .github/workflows/main.yml
Disable tests until rust-libp2p builds again.
Refs: https://github.com/libp2p/test-plans/issues/343
> chore: temporarily disable interop tests

- doc/migrations/v0.46-v1.0.0.md
migration guide (specifically https://github.com/libp2p/js-libp2p/blob/c9ed1c7d62e9af974789eb753d6f8e3c6410df94/doc/migrations/v0.46-v1.0.0.md#keeping-the-same-peerid-after-a-restart) was missing an import for `Key`. This may not be the correct import, but appears to be what libp2p/keychain and others are using.
related: https://github.com/libp2p/js-libp2p/issues/2317 once the correct import is added.
> docs: migration guide -> missing import

- packages/utils/src/abstract-stream.ts
- packages/utils/test/abstract-stream.spec.ts
Race the passed abort signal along with gracefully closing read/write ends of a stream, so that the signal will abort a stream that is very slow to send data.
> fix: abort slow sending streams

- packages/multistream-select/test/integration.spec.ts
Fixes uncaught exception from expected error that can crash browser tests occasionally.
> chore: fix uncaught exception in test

- packages/utils/src/abstract-stream.ts
- packages/utils/test/abstract-stream.spec.ts
When gracefully closing a stream, allow the stream to send it's final data payload before aborting it.
> fix: give send data a chance to complete before closing stream

- packages/interface/src/event-target.ts
- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/src/upgrader.ts
- packages/transport-websockets/test/compliance.node.ts
When recreating the dial queue shutdown controller, we must also increase the number of listeners it can have, otherwise warnings are printed when there are more than 10 peers in the dial queue.
> fix: silence max listeners warning

- packages/peer-record/src/index.ts
**docs: add links to finished RFCs to docs for peer-record**
Update docs to link to actual RFCs and not just to PRs. 
Fixes https://github.com/libp2p/js-libp2p/issues/2404
> docs: add links to finished RFCs to docs for peer-record

- packages/transport-tcp/src/listener.ts
- packages/transport-tcp/src/socket-to-conn.ts
- packages/transport-tcp/test/socket-to-conn.spec.ts
- packages/transport-websockets/test/compliance.node.ts
Fixes a race condition introduced by https://github.com/libp2p/js-libp2p/pull/2058
By starting to closing connections before starting to close the server, on a slow machine or one under load it's possible for a connection to close before the server status is set to `INACTIVE`, then the listener will never emit it's `'close'` event and the node will not shut down.
Also has edits for style & consistency.
> fix: tcp server close race condition

- .github/workflows/main.yml
Install a specific version of go because sometimes quic-go isn't buildable on the latest release.
> chore: lock go version to 1.20

- packages/kad-dht/test/query-self.spec.ts
`.on` stubbing needs to change to `.addEventListener` as the type has changed to `TypedEventEmitter`
> chore: fix dht tests

- packages/kad-dht/src/index.ts
- packages/kad-dht/src/query/events.ts
- packages/kad-dht/test/kad-dht.spec.ts
As of TypeScript 5.4.x enums need to have the same values to be compatible so re-use the exported enum from the message definition.
Refs: https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/#new-enum-assignability-restrictions
> fix: typescript enums need to be value-compatible

- packages/libp2p/package.json
- packages/libp2p/src/components.ts
- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/src/connection-manager/utils.ts
- packages/libp2p/src/index.ts
- packages/libp2p/src/libp2p.ts
- packages/libp2p/test/connection-manager/index.node.ts
- packages/libp2p/test/connection-manager/resolver.spec.ts
Adds a `dns` config key that lets users specify an instance of the `DNS` interface from `@multiformats/dns`.
This instance will be passed through to DNSADDR `multiaddr`s for use when the DNSLink TXT record is resolved.
Removes recursive DNSADDR resolution since this is now handled by `@multiformats/multiaddr`.
> feat: support custom DNS resolvers

- packages/protocol-echo/LICENSE
- packages/protocol-echo/LICENSE-APACHE
- packages/protocol-echo/LICENSE-MIT
- packages/protocol-echo/README.md
- packages/protocol-echo/package.json
- packages/protocol-echo/src/constants.ts
- packages/protocol-echo/src/echo.ts
- packages/protocol-echo/src/index.ts
- packages/protocol-echo/test/index.spec.ts
- packages/protocol-echo/tsconfig.json
- packages/protocol-echo/typedoc.json
To save us having to re-implement an echo protocol over and over again in documentation and examples, just publish a simple reusable echo protocol module.
> feat: add simple echo protocol

- packages/interface/src/errors.ts
As discussed in https://github.com/ipfs/helia-verified-fetch/issues/25#issuecomment-2018003309, this PR adds the name property to the AbortError type. 
This has a couple of benefits:
- Sticks the common convention for Error types (all built in Error types have the name property set to the class name)
- Allows checking the error type at runtime in a TS codebase without importing the type
- Should we also set the name property on UnexpectedPeerError, InvalidCryptoExchangeError and InvalidCryptoTransmissionError?
> fix: add name property to exported interface errors

- packages/connection-encrypter-tls/src/tls.ts
- packages/connection-encrypter-tls/src/utils.ts
`@peculiar/x509` cannot represent dates as far in advance as go-libp2p so the certs are rejected.
Reduce the maximum validity of certificates to keep them under 2050 - this can be re-evaluated after https://github.com/PeculiarVentures/x509/issues/73 is fixed.
> fix: reduce TLS cert validity time

- doc/CONFIGURATION.md
I appears that "crypto" was replaced with "connection encrypter".  Configuration document used the old term and referred to non-existing code location.
> docs: CONFIGURATION.md referenced renamed crypto component

- packages/integration-tests/package.json
@libp2p/tls is v1 so update the dep version.
> chore: update tls version in integration tests

- packages/connection-encrypter-tls/src/utils.ts
Partial revert of #2457.  We can specify dates in the far future, causing `@peculiar/x509` to use `GeneralizedTime` values, but it doesn't strip fractional seconds as per RFC 5280 so do it ourselves.
> fix: remove ms from TLS notAfter date

- packages/kad-dht/src/content-routing/index.ts
- packages/kad-dht/src/query-self.ts
- packages/kad-dht/src/query/manager.ts
- packages/kad-dht/src/query/query-path.ts
The way we were counting DHT providers was wrong, count the actual number found - this prevents queries continuing to execute after we've found K providers.
> fix: count dht providers and abort when enough found

- packages/libp2p/src/connection-manager/constants.defaults.ts
- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/src/connection-manager/index.ts
- packages/libp2p/test/connection-manager/direct.spec.ts
Add an upper bound to the maximum length of the dial queue.
Any attempts to dial when the queue is full will throw.
> fix: limit max dial queue size

- packages/utils/src/queue/index.ts
- packages/utils/test/peer-job-queue.spec.ts
Adds extra events to the Queue class that allow access to more context during the event, for example being able to access the options that were passed to a job.
> feat: add queue success and failure events

- packages/utils/src/queue/index.ts
- packages/utils/src/queue/job.ts
- packages/utils/src/queue/recipient.ts
- packages/utils/test/fixtures/test-signal.ts
- packages/utils/test/queue.spec.ts
Fixes a bug where aborted queue jobs were not removing abort signal listeners properly.
Also removes the aborted job from the queue immediately to reduce size and allow garbage collection sooner.
> fix: ensure abort listeners are removed from queue jobs

- packages/transport-tcp/src/socket-to-conn.ts
- packages/transport-tcp/test/socket-to-conn.spec.ts
Close MultiaddrConnection once
- It's designed to close MultiaddrConnection once, however in case there are some writable data remaining, socket is not destroyed yet https://github.com/libp2p/js-libp2p/blob/c5003d40207bc3be15645b5af93f8dec1fd5d55b/packages/transport-tcp/src/socket-to-conn.ts#L177 and when there is a called to `close()` again it'll run the function again
- Instead use a variable to control it like other places
this could fix #2477 see https://github.com/libp2p/js-libp2p/issues/2477#issuecomment-2049121628
> fix: close MultiaddrConnection once

- packages/transport-tcp/src/socket-to-conn.ts
Use same promise when closing`MultiaddrConnection` multiple time
See https://github.com/libp2p/js-libp2p/pull/2478#pullrequestreview-2000610558
- Replace `status` variable introduced in #2478 with a `closePromise`
- use this `closePromise` for subsequent `maConn.close()` calls
- the new unit test in #2478 passed
related to #2477
> fix: use same promise when closing maconn multiple times

- packages/libp2p/src/upgrader.ts
fix: upgrader error msg shows current/max
Provides more information in the error message so users can better understand the error state.
> CodeError: Too many outbound protocol streams for protocol "/ipfs/id/push/1.0.0" - limit 1
This error message is not super helpful for debugging. What's the overage amount?
Also, the check is checking `>=`, and if your limit is 1, that will prevent ANY outbound protocol streams. Is this intended? should we be comparing with only `>` ?
> fix: upgrader error msg to show current/max

- packages/crypto/src/keys/ed25519-class.ts
- packages/crypto/src/keys/index.ts
- packages/crypto/src/keys/rsa-class.ts
- packages/crypto/src/keys/secp256k1-class.ts
- packages/interface/src/keys/index.ts
- packages/interface/src/peer-id/index.ts
- packages/peer-id-factory/src/index.ts
- packages/peer-id/src/index.ts
Sometimes a peer will have a non-cryptographic identifier such as a URL.
Update the PeerId type to be an interface so we can use arbitrary data to identify other peers, not just cryptographic keys.
> feat: extensible peer ids

- packages/kad-dht/src/rpc/handlers/find-node.ts
- packages/kad-dht/src/rpc/handlers/get-providers.ts
- packages/kad-dht/test/kad-dht.spec.ts
- packages/kad-dht/test/rpc/handlers/find-node.spec.ts
- packages/kad-dht/test/rpc/index.node.ts
The `FIND_NODE` DHT operation should return the closest peers the node knows to the value.
It does not need to return itself in the list because the calling peer already knows about it.
Fixes #2450
> fix: return closest peers from FIND_NODE

- .github/workflows/main.yml
- packages/transport-webrtc/package.json
- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/src/webrtc/index.browser.ts
- packages/transport-webrtc/src/webrtc/index.ts
The cleanup function from `node-datachannel` closes all open peer connections/datachannels - if there are multiple transports/nodes in the same process they will all be closed.
Fixes #2425
> fix: do not run webrtc cleanup on transport close

- packages/interface-internal/src/index.ts
- packages/interface-internal/src/random-walk/index.ts
- packages/libp2p/package.json
- packages/libp2p/src/libp2p.ts
- packages/libp2p/src/random-walk.ts
- packages/libp2p/test/core/random-walk.spec.ts
To allow finding network services, add a random walk component that lets services find random network peers in a scalable way.
If two services try to random walk at the same time, they will share the results.
> feat: add random walk component

- packages/kad-dht/src/peer-routing/index.ts
- packages/kad-dht/src/rpc/handlers/find-node.ts
- packages/kad-dht/test/kad-dht.spec.ts
- packages/kad-dht/test/rpc/handlers/find-node.spec.ts
- packages/kad-dht/test/rpc/index.node.ts
Partial revert of #2499
If a node is queried for it's own peer id, return it's own peer info.
This is necessary because since https://github.com/libp2p/go-libp2p-kad-dht/pull/820 go-libp2p-kad-dht won't add a peer to it's routing tables that doesn't have any DHT peers that are KAD-futher from it's own ID already.
> fix: return self in FIND_NODE for self

- packages/kad-dht/src/kad-dht.ts
- packages/kad-dht/src/routing-table/refresh.ts
Fixes an error in the logs where we try to refresh the routing table before it's started.
Switch to doing it in `afterStart` so the routing table is available.
> fix: begin routing table refresh after routing table has started

- packages/peer-collections/src/filter.ts
- packages/peer-collections/test/filter.spec.ts
- packages/peer-collections/tsconfig.json
- packages/utils/package.json
- packages/utils/src/filters/bloom-filter.ts
- packages/utils/src/filters/bucket.ts
- packages/utils/src/filters/cuckoo-filter.ts
- packages/utils/src/filters/fingerprint.ts
- packages/utils/src/filters/hashes.ts
- packages/utils/src/filters/index.ts
- packages/utils/src/filters/scalable-cuckoo-filter.ts
- packages/utils/src/filters/utils.ts
- packages/utils/test/filter/bloom-filter.spec.ts
- packages/utils/test/filter/cuckoo-filter.spec.ts
- packages/utils/test/filter/scalable-cuckoo-filter.spec.ts
Add a filter type that lets us efficiently remove items as well as add them.
It would be better to use the `bloom-filters` module at this point but it's published as a big blob of CJS that adds 50KB+ to browser bundles for very simple use cases so it's not suitable.
We can revisit if https://github.com/Callidon/bloom-filters/issues/70 is ever resolved.
> feat: add cuckoo filter

- packages/libp2p/src/connection-manager/connection-pruner.ts
- packages/libp2p/test/connection-manager/connection-pruner.spec.ts
- packages/utils/package.json
- packages/utils/src/abort-options.ts
- packages/utils/src/close.ts
- packages/utils/test/close.spec.ts
Changes how we sort connections to prune to be more than just tags and age.
Now we'll sort by tags, the number of open streams, direction and age.
This should choose idle connections without streams to close over those that are in use.
> fix: prune connections based on stream counts and direction

- interop/test/ping.spec.ts
Slow CI is slow so try increasing the default ping timeout.
> chore: increase ping test timeout

- packages/kad-dht/src/constants.ts
30s is not enough for a typical query with an empty routing table.
A typical time is more like 60s so increase to 180s to give headroom.
> fix: increase default DHT query timeout

- packages/libp2p/src/connection-manager/index.ts
fix: options in connection manager init should be passed to autodial
`autoDialPeerRetryThreshold` and `autoDialDiscoveredPeersDebounce` should be passed from connection manager to auto dial, otherwise it won't work
> fix: pass autodial config thorugh in connection manager init

- packages/kad-dht/src/routing-table/index.ts
- packages/kad-dht/test/libp2p-routing.spec.ts
- packages/kad-dht/test/routing-table.spec.ts
On startup, query the peerstore for every peer that supports the configured KAD protocol and add them to the routing table.
> fix: load peerstore peers into routing table at startup

- packages/kad-dht/src/index.ts
- packages/kad-dht/src/peer-list/peer-distance-list.ts
- packages/kad-dht/src/query/manager.ts
- packages/kad-dht/src/query/query-path.ts
- packages/kad-dht/src/routing-table/index.ts
- packages/kad-dht/src/routing-table/k-bucket.ts
- packages/kad-dht/src/routing-table/refresh.ts
- packages/kad-dht/src/utils.ts
- packages/kad-dht/test/libp2p-routing.spec.ts
- packages/kad-dht/test/query.spec.ts
- packages/kad-dht/test/routing-table.spec.ts
The Kademlia paper shows a simple binary tree as a data structure for the routing table.  This can grow very deep for long keys so an optimisation is to only use a prefix of the KAD-ID when constructing the table.
This results in faster lookups for better performance.
> fix: use prefix binary tree for routing table

- packages/interface/src/topology/index.ts
- packages/libp2p/src/registrar.ts
- packages/libp2p/test/registrar/errors.spec.ts
- packages/libp2p/test/registrar/protocols.spec.ts
- packages/libp2p/test/registrar/registrar.spec.ts
Adds a `filter` option to topologies to allow filtering out duplicate notifications.
> feat: add optional topology filter

- packages/metrics-simple/src/index.ts
- packages/metrics-simple/test/index.spec.ts
Fixes a small bug in the creation of in-memory metrics.
> fix: allow creating counter groups

- packages/libp2p/src/upgrader.ts
The peer id was meant to be passed to the format string with the error afterwards.
> fix: log error correctly

- interop/.aegir.js
Sometimes docker in CI resolves localhost to an ip4 address, sometimes an ip6 address so just bind to all interfaces.
> fix: bind redis proxy to all interfaces

- packages/connection-encrypter-tls/src/utils.ts
The WebCrypto polyfill has [improved it's validation](https://github.com/PeculiarVentures/webcrypto-core/commit/4ef9eaab136fdee833884762f865f4b6dce28465) and we now fail to export the private key of the generated cert correctly.
Update to export in pkcs8 format instead, which we can just base64 encode to turn it into the PEM format.
> fix: export tls key as pkcs8

- packages/transport-webtransport/.aegir.js
These modules have dependencies on `@libp2p/interface` which is part of this monorepo so may not be built yet if they are statically imported at the top of the file.
Instead import them dynamically when they are used during the test phase.
> chore: import multiaddr and daemon client modules dynamically

- packages/transport-webtransport/src/muxer.ts
If the WebTransport session has closed, trying to read new stream can cause the promise to reject, printing an error in the console.
This is non-fatal for browsers but let's catch and log the error instead.
> fix: catch unhandled promise rejection in WebTransport muxer

- packages/transport-webrtc/README.md
- packages/transport-webrtc/src/index.ts
Update comment about WebRTC direct support in Go and Rust libp2p
> docs: update webrtc-direct support

- packages/transport-webrtc/.aegir.js
- packages/transport-webrtc/package.json
- packages/transport-webrtc/test/transport.spec.ts
node-datachannel appears to be keeping processes running again.
> chore: fix webrtc tests

- packages/protocol-autonat/package.json
- packages/protocol-autonat/src/autonat.ts
- packages/protocol-autonat/src/index.ts
- packages/protocol-autonat/test/index.spec.ts
Refactor to reuse the randomwalk component rather than rolling our own during autonat address verification.
> fix: use randomwalk when performing autonat

- packages/interface-compliance-tests/src/transport/dial-test.ts
- packages/interface-compliance-tests/src/transport/filter-test.ts
- packages/interface-compliance-tests/src/transport/index.ts
- packages/interface-compliance-tests/src/transport/listen-test.ts
- packages/transport-tcp/test/compliance.spec.ts
- packages/transport-websockets/test/compliance.node.ts
To support asymmetric transports, call `.listen` and `.dial` on separate properties of the transport interface setup return value.
For symmetric transports these can be the same transport instance.
> fix: split listeners and dialers in transport interface tests

- packages/interface/src/connection-gater/index.ts
- packages/interface/src/index.ts
- packages/libp2p/src/config.ts
- packages/libp2p/src/index.ts
- packages/libp2p/src/libp2p.ts
- packages/libp2p/test/connection-manager/direct.node.ts
- packages/libp2p/test/connection-manager/index.node.ts
- packages/libp2p/test/registrar/protocols.spec.ts
- packages/metrics-devtools/src/index.ts
- packages/peer-store/src/index.ts
- packages/transport-circuit-relay-v2/src/server/reservation-store.ts
Derive the type of the components arg from a union of the internal components plus the service map type.
> fix: allow custom services to depend on each other

- packages/transport-webrtc/src/private-to-private/initiate-connection.ts
- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/src/private-to-private/util.ts
- packages/transport-webrtc/test/peer.spec.ts
- packages/transport-webrtc/test/stream.spec.ts
Chrome limits how many RTCPeerConnections a given tab can instantiated during it's lifetime - https://issues.chromium.org/issues/41378764
To delay hitting this limit, only create the dial-end RTCPeerConnection once a relayed connection has successfully been opened to the dial target, this prevents needlessly creating RTCPeerConnections when the dial fails before they are actually used.
Fixes #2591
> fix: create RTCPeerConnection after dialing remote peer

- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/src/private-to-public/transport.ts
In order to allow refreshing STUN/TURN credentials between dials, allow passing a function that returns rtc config.
Fixes #2554
> feat: allow passing a function for rtcConfiguration

- packages/stream-multiplexer-mplex/src/index.ts
- packages/stream-multiplexer-mplex/src/mplex.ts
These should be defined on the factory not the instance, since the factory is the component.
> fix: move mplex capabilities to the factory

- packages/interface-internal/package.json
- packages/interface-internal/src/connection-manager/index.ts
- packages/interface-internal/src/transport-manager/index.ts
- packages/libp2p/package.json
- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/src/connection-manager/index.ts
- packages/libp2p/src/transport-manager.ts
- packages/libp2p/test/connection-manager/direct.spec.ts
If the user passes an `onProgress` callback to a dial request, invoke the callback with progress events during the dial.
> feat: invoke progress events during dialing

- packages/interface/src/peer-id/index.ts
- packages/peer-id-factory/src/index.ts
- packages/peer-id/src/index.ts
- packages/peer-id/test/index.spec.ts
To parse non-cryptographic peer ids from http servers, add the url peer id type.
> feat: add url peer id

- packages/transport-webtransport/src/index.ts
- packages/transport-webtransport/src/webtransport.browser.ts
Make sure the WebTransport transport can load in Safari without erroring.
> fix: WebTransport fail gracefully in Safari

- packages/transport-webrtc/src/constants.ts
- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/src/private-to-public/transport.ts
- packages/transport-webrtc/src/util.ts
To make it easier to connect to remote nodes behind NATs, add default STUN servers to the WebRTC transport.
> fix: add default STUN servers to WebRTC transport

- README.md
Added Topology Logo in the "Used by" section as suggested by @achingbrain [here](https://github.com/topology-foundation/ts-topology/issues/27). We are currently heavily using js-libp2p in our [protocol implementation](https://github.com/topology-foundation/ts-topology).
> docs: add topology logo

- packages/interface/src/metrics/index.ts
The import statement needs a closing `'` in places.
> docs: fix metrics example typo

- packages/interface-internal/src/connection-manager/index.ts
- packages/interface-internal/src/transport-manager/index.ts
- packages/interface/src/index.ts
- packages/interface/src/transport/index.ts
- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/src/libp2p.ts
- packages/transport-circuit-relay-v2/src/transport/transport.ts
- packages/transport-tcp/src/index.ts
- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/src/private-to-public/options.ts
- packages/transport-websockets/src/index.ts
- packages/transport-webtransport/src/index.ts
Accept the `onProgress` event via types.
> fix: expose progress events in dial/dialProtocol types

- packages/transport-webrtc/src/constants.ts
Using 5x or more causes the following error to be printed in the console so only use 4x servers:
```
WebRTC: Using five or more STUN/TURN servers slows down discovery
```
> fix: limit default WebRTC STUN servers to 4x

- packages/kad-dht/src/index.ts
- packages/kad-dht/src/kad-dht.ts
The default values set up an amino dht node so don't require an init arg since it can have no properties but still work.
> fix: make kad-dht init object optional

- .github/workflows/main.yml
nim broke compatibility a while back, re-enable tests to see if it has been restored.
> chore: enable testing against nim-libp2p in multidim tests

- .github/workflows/main.yml
- interop/Dockerfile
There's a regression in the latest node lts that causes npm 10.7.0 to fail to install so pin to the last release with 10.6.0.
> chore: pin node version in transport interop tests

- packages/interface/src/index.ts
docs: update newStream return value
newStream doesn't return an object with a stream property
> docs: update `connection.newStream` return value

- packages/transport-webrtc/src/stream.ts
From experimental testing, 16MB is too big for Chrome to handle, when sending large amounts of data - the `bufferedamountlow` event never fires.
Lower it to 2MB which seems to actually work when running the Helia transport benchmarks.
> fix: decrease max buffered amount for WebRTC datachannels

- packages/transport-webrtc/src/stream.ts
The 16KB limit was fixed in browsers quite a while back so we should be able to increase the max datachannel message size to 256KB at least.
Fixes #2612
> fix: increase WebRTC max datachannel message size

- packages/interface/src/event-target.ts
The EventTarget implementation of libp2p contained workarounds for incomplete runtime support for the feature. One of the workarounds was specifically marked to be removed once CustomEvent was implemented in NodeJS and the [upstream ticket](https://github.com/nodejs/node/issues/40678) was closed. This has happened two years ago. The implementation of the standard event in Node18 and the subsequent removal of the experimental flag in Node19 broke the current workaround and causes tsc to error. Some of these were suppressed with @ts-ignore, others were not. This fix closes #2420.
The fix removes the workaround as instructed by the source code and restores compatibility with recent versions of Node:
```
/**
* CustomEvent is a standard event but it's not supported by node.
*
* Remove this …
```
> fix: remove CustomEvent polyfill

- packages/interface-compliance-tests/src/transport/listen-test.ts
- packages/interface/src/event-target.ts
- packages/kad-dht/src/kad-dht.ts
- packages/kad-dht/src/query/events.ts
- packages/kad-dht/src/topology-listener.ts
- packages/kad-dht/test/query-self.spec.ts
- packages/kad-dht/test/routing-table.spec.ts
- packages/libp2p/src/libp2p.ts
- packages/peer-discovery-mdns/src/mdns.ts
- packages/peer-discovery-mdns/test/compliance.spec.ts
- packages/pubsub/src/index.ts
- packages/pubsub/src/peer-streams.ts
- packages/transport-websockets/src/listener.ts
`CustomEvent` is global in Node.js as of `v18.7.0`. We support LTS and Current which means `v20+`, and Electron has upgraded to node 20 so the polyfill isn't necessary any more.
BREAKING CHANGE: `@libp2p/interface` no longer exports a `CustomEvent` polyfill
> fix!: remove CustomEvent export from `@libp2p/interface`

- packages/libp2p/src/connection-monitor.ts
- packages/libp2p/test/connection-monitor/index.spec.ts
The new connection monitor currently uses the hard-coded default ping protocol `'/ipfs/ping/1.0.0'`. The ping service lets the developer override the `ipfs` component with a custom protocol prefix, and some apps are already doing this. This PR adds support for a `protocolPrefix` option in `ConnectionMonitorInit` that matches the option in `PingServiceInit`.
> fix: accept custom ping protocol prefix in connection monitor

- packages/protocol-ping/src/ping.ts
- packages/protocol-ping/test/index.spec.ts
As per the spec only allow 32 bytes to be sent as a ping.
Reset the stream if more bytes are received.
> fix: limit incoming ping bytes to 32

- packages/libp2p/src/connection-monitor.ts
Update the number of bytes sent by the connection manager so that it is compatible with other `ping` implementations
https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/ping/ping.go#L23
https://github.com/libp2p/rust-libp2p/blob/master/protocols/ping/src/protocol.rs#L48
https://github.com/libp2p/js-libp2p/blob/main/packages/protocol-ping/src/constants.ts#L2
> fix: connection monitor compatible with other ping implementations

- funding.json
This funding.json file is added here in order to apply for Optimism's rPGF round 5: https://retrofunding.optimism.io/application/5
The application process requires this file to exist in public github repositories that are linked to applications.
The js-libp2p repo will be listed in IP Shipyard's application for round 5.
The contents of this file were autogenerated:
> chore: add a funding JSON file to apply for Optimism rPGF round 5

- packages/transport-webrtc/package.json
- packages/transport-webrtc/src/stream.ts
- packages/transport-webrtc/test/stream.spec.ts
go-libp2p and rust-libp2p close incoming streams when the message size is greater than 16KiB so reset to the previous limit.
Reverts #2627
> fix: revert WebRTC message size increase

- packages/transport-webrtc/src/private-to-public/sdp.ts
- packages/transport-webrtc/test/sdp.spec.ts
Do not hard code the `max-message-size` SDP directive, instead reuse the `MAX_MESSAGE_SIZE` constant.
> fix: parameterise max message size in SDP messages

- packages/utils/benchmark/filter/bloom-filter.cjs
- packages/utils/package.json
- packages/utils/src/filters/bloom-filter.ts
Constant time `setbit` and `getbit` in the bloom filter - was hitting performance issues when using a 30mb bloom filter
Benchmarks below
```
Loop 8bits x 171,777,298 ops/sec ±2.70% (89 runs sampled)
Math Ops 8bits x 216,520,449 ops/sec ±6.46% (77 runs sampled)
Loop 64bits x 127,603,004 ops/sec ±3.28% (85 runs sampled)
Math Ops 64bits x 225,485,149 ops/sec ±5.94% (81 runs sampled)
Loop 512bits x 35,893,950 ops/sec ±0.76% (97 runs sampled)
Math Ops 512bits x 223,396,999 ops/sec ±5.05% (79 runs sampled)
Loop 4096bits x 4,824,731 ops/sec ±0.91% (97 runs sampled)
Math Ops 4096bits x 211,234,954 ops/sec ±5.26% (77 runs sampled)
Loop 32768bits x 579,890 ops/sec ±0.40% (100 runs sampled)
Math Ops 32768bits x 206,112,847 ops/sec ±5.97% (74 runs sampled)
Loop 262144bits x 60,922 ops/sec ±0.15% (98 …
```
> fix: remove while loop for setbit & getbit

- packages/crypto/src/keys/index.ts
- packages/crypto/test/keys/ed25519.spec.ts
- packages/crypto/test/keys/rsa.spec.ts
- packages/crypto/test/keys/secp256k1.spec.ts
> fix: correct secp256k1 key length detection in publicKeyFromRaw

- packages/crypto/test/keys/ed25519.spec.ts
- packages/crypto/test/keys/rsa.spec.ts
- packages/crypto/test/keys/secp256k1.spec.ts
- packages/interface/src/keys/index.ts
To give typescript some hints about object types, add `isPrivateKey` and `isPublicKey` functions.
> fix: add public/private key type disambiguators

- packages/keychain/src/keychain.ts
- packages/keychain/test/keychain.spec.ts
Because the keychain doesn't create keys, only accepts them, allow importing the "self" key.
If the key already exists it will fail, and you still can't remove or rename it.
> fix: allow importing the self key

- packages/interface-compliance-tests/src/pubsub/api.ts
- packages/interface/src/pubsub/index.ts
- packages/pubsub-floodsub/src/index.ts
- packages/pubsub-floodsub/test/floodsub.spec.ts
Adds a type disambiguator function to signal to tsc that an object implements the PubSub interface.
> feat: add isPubSub method to detect PubSub implementations

- packages/metrics-devtools/package.json
- packages/metrics-devtools/src/index.ts
- packages/metrics-devtools/src/rpc/index.ts
- packages/metrics-devtools/src/rpc/rpc.ts
- packages/metrics-devtools/src/utils/find-capability.ts
- packages/metrics-devtools/src/utils/gather-capabilities.ts
- packages/metrics-devtools/src/utils/get-pubsub.ts
Adds the ability to find configured services that possess a given capability and interact with that service via rpc.
Starts with a configured PubSub service.
> feat: add capability detection to metrics-devtools

- packages/protocol-ping/package.json
- packages/protocol-ping/src/ping.ts
- packages/protocol-ping/test/index.spec.ts
Read incoming ping messges in 32 byte chunks as per the spec and echo them back to the sending peer.
If the remote fails to send us 32 bytes, reset the stream with a `TimeoutError`.
> fix: allow multiple ping messages

- packages/interface-compliance-tests/package.json
- packages/interface-compliance-tests/src/mocks/metrics.ts
- packages/interface/src/metrics/index.ts
- packages/metrics-devtools/src/index.ts
- packages/metrics-prometheus/src/histogram-group.ts
- packages/metrics-prometheus/src/histogram.ts
- packages/metrics-prometheus/src/index.ts
- packages/metrics-prometheus/src/summary-group.ts
- packages/metrics-prometheus/src/summary.ts
- packages/metrics-prometheus/test/histogram-groups.spec.ts
- packages/metrics-prometheus/test/histograms.spec.ts
- packages/metrics-prometheus/test/summaries.spec.ts
- packages/metrics-prometheus/test/summary-groups.spec.ts
- packages/metrics-simple/package.json
- packages/metrics-simple/src/index.ts
- Add `Histogram`, `HistogramGroup`, `Summary`, `SummaryGroup` metric types
- Add `registerHistogram`, `registerHistogramGroup`, `registerSummary`, `registerSummaryGroup` methods to `Metrics` interface
- Add corresponding implementations to prometheus and simple metrics packages
> feat: add histogram and summary metric types

- packages/libp2p/src/connection-manager/index.ts
> feat: add pending connections count to metrics

- packages/interface-compliance-tests/src/transport/listen-test.ts
- packages/interface-internal/src/connection-manager/index.ts
- packages/interface/src/connection/index.ts
- packages/libp2p/src/connection-manager/constants.defaults.ts
- packages/libp2p/src/connection-manager/index.ts
- packages/libp2p/src/libp2p.ts
- packages/libp2p/src/upgrader.ts
- packages/transport-tcp/src/listener.ts
- packages/transport-tcp/src/tcp.ts
- packages/transport-tcp/test/listen-dial.spec.ts
- Unifies inbound/outbound upgrade
- Adds default timeouts for inbound/outbound upgrades and stream protocol negotation
- Ensure tcp listener closes sockets when upgrade times out
- Passes abort signal to connection encrypter
- Uses simple promise rejection to abort tcp connections
Before:
After:
Fixes #2537
Fixes #2477
> fix: simplify connection upgrade

- packages/transport-circuit-relay-v2/package.json
- packages/transport-circuit-relay-v2/src/server/index.ts
- packages/transport-circuit-relay-v2/src/server/reservation-store.ts
- packages/transport-circuit-relay-v2/test/hop.spec.ts
- packages/transport-circuit-relay-v2/test/reservation-store.spec.ts
- packages/transport-circuit-relay-v2/test/stop.spec.ts
Tracks the reservation store map to observe how many reservation slots are currently occupied.
Also reinstates tests that were accidentally removed by the linter.
> feat: add relay server reservation store metrics

- packages/logger/src/index.ts
Try to log the stack trace, if it's not available use the message
> feat: add %e error formatter

- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/src/connection-manager/index.ts
- packages/libp2p/src/upgrader.ts
- packages/libp2p/test/connection-manager/direct.spec.ts
- packages/libp2p/test/connection-manager/index.spec.ts
Splitting metrics is considered best practice where there are a small number of outcomes.
Refs: https://promlabs.com/blog/2023/09/19/errors-successes-totals-which-metrics-should-i-expose-to-prometheus/
> fix: split error/operation metrics

- packages/transport-tcp/src/listener.ts
- packages/transport-tcp/src/socket-to-conn.ts
In the first close attempt we wrap the `closePromise` with a try/catch and call `.abort` if it throws, and we don't propagate the error.
In the second invocation we return the `closePromise` which can reject making the code non-deterministic.
> fix: make tcp closing error throwing consistent

- packages/integration-tests/test/circuit-relay.node.ts
- packages/transport-tcp/package.json
- packages/transport-tcp/src/constants.ts
- packages/transport-tcp/src/index.ts
- packages/transport-tcp/src/listener.ts
- packages/transport-tcp/src/socket-to-conn.ts
- packages/transport-tcp/src/tcp.ts
- packages/transport-tcp/test/socket-to-conn.spec.ts
Simplifies tcp transport connection opening/closing, catches some instances where we were not destroying sockets for incoming and outgoing connections which caused a file descriptor leak.
Before/after:
> fix: refactor connection opening and closing

- packages/kad-dht/src/index.ts
- packages/kad-dht/src/kad-dht.ts
- packages/kad-dht/src/routing-table/index.ts
- packages/kad-dht/test/routing-table.spec.ts
This will ensure we are always connected to peers in our root kad bucket.
Also passes the complete set of options to the routing table to allow constraining memory usage from the constructor.
> fix: tag kad-close peers with keepalive

- packages/utils/src/queue/index.ts
There will always be an abort signal passed to a queue job so the options arg will always be present.
> fix: make queue job args non-optional

- packages/kad-dht/package.json
- packages/kad-dht/src/errors.ts
- packages/kad-dht/src/index.ts
- packages/kad-dht/src/kad-dht.ts
- packages/kad-dht/src/network.ts
- packages/kad-dht/src/query-self.ts
- packages/kad-dht/src/routing-table/index.ts
- packages/kad-dht/src/routing-table/k-bucket.ts
- packages/kad-dht/src/routing-table/refresh.ts
- packages/kad-dht/src/rpc/index.ts
- packages/kad-dht/test/generate-peers/generate-peers.node.ts
- packages/kad-dht/test/kad-dht.spec.ts
- packages/kad-dht/test/libp2p-routing.spec.ts
- packages/kad-dht/test/routing-table.spec.ts
- packages/kad-dht/test/utils/test-dht.ts
Implements the [check-before-add](https://github.com/libp2p/go-libp2p-kad-dht/blob/master/optimizations.md#checking-before-adding) client optimisation to ping a peer before adding it to the routing table.
Adds a "new peer ping queue" to apply a concurrency limit to these pings, because it would be expected for old contacts to be less likely to be online so don't block adding new contacts to unrelated buckets if the connection to an old contact is timing out while being pinged before eviction.
BREAKING CHANGE: the routing ping options have been split into "old contact" and "new contact" and renamed according
> feat!: ping peers before adding to routing table

- packages/libp2p/README.md
The roadmap was removed in #2689. There are a few links to it still.
This PR removes the link in libp2p/js-libp2p/packages/libp2p
https://github.com/libp2p/js-libp2p/blob/main/packages/libp2p/README.md#roadmap
There is also a link from libp2p/specs.
https://github.com/libp2p/specs/blob/master/ROADMAP.md#implementation-roadmaps
Can open a PR there for it to be removed but #2689 mentions that `can view roadmap in Github issues` but was not able to find something to link to.
> chore: remove reference to removed roadmap

- packages/transport-circuit-relay-v2/src/transport/reservation-store.ts
Since the auto dialer was removed, we need to tag the relay with `KEEP_ALIVE` to reconnect to it if we disconnect.
> fix: tag relay with keep_alive

- packages/transport-tcp/test/socket-to-conn.spec.ts
Depending on timing either error can be thrown.
> chore: fix socket test

- packages/integration-tests/test/circuit-relay.node.ts
- packages/interface/src/index.ts
- packages/libp2p/src/connection-manager/reconnect-queue.ts
- packages/transport-circuit-relay-v2/package.json
- packages/transport-circuit-relay-v2/src/constants.ts
- packages/transport-circuit-relay-v2/src/index.ts
- packages/transport-circuit-relay-v2/src/server/index.ts
- packages/transport-circuit-relay-v2/src/transport/discovery.ts
- packages/transport-circuit-relay-v2/src/transport/index.ts
- packages/transport-circuit-relay-v2/src/transport/listener.ts
- packages/transport-circuit-relay-v2/src/transport/reservation-store.ts
- packages/transport-circuit-relay-v2/test/hop.spec.ts
- packages/transport-circuit-relay-v2/test/transport/reservation-store.spec.ts
To signal to the rest of libp2p that our addresses are changing, emit the `listening` event when relays go away or our reservation expires.
Also remove the old tags on startup to ensure we don't reconnect to old relays as the spec says the reservation is only valid while we are connected.
> fix: emit 'listening' when relays change

- README.md
Remove link to deprecated package
> docs: remove peer-id-factory

- packages/integration-tests/test/circuit-relay.node.ts
- packages/transport-circuit-relay-v2/package.json
- packages/transport-circuit-relay-v2/src/constants.ts
- packages/transport-circuit-relay-v2/src/index.ts
- packages/transport-circuit-relay-v2/src/pb/index.proto
- packages/transport-circuit-relay-v2/src/pb/index.ts
- packages/transport-circuit-relay-v2/src/server/index.ts
- packages/transport-circuit-relay-v2/src/server/reservation-store.ts
- packages/transport-circuit-relay-v2/src/server/reservation-voucher.ts
- packages/transport-circuit-relay-v2/src/transport/reservation-store.ts
- packages/transport-circuit-relay-v2/src/transport/transport.ts
- packages/transport-circuit-relay-v2/src/utils.ts
- packages/transport-circuit-relay-v2/test/reservation-store.spec.ts
- packages/transport-circuit-relay-v2/test/utils.spec.ts
Handles some more instances where we don't remove old reservations when refreshing them fails.
> fix: handle more circuit relay refresh failures

- packages/protocol-echo/package.json
- packages/protocol-echo/src/echo.ts
- packages/protocol-echo/src/index.ts
- packages/protocol-echo/test/index.spec.ts
To make it easier to invoke the echo protocol, add a method to the service.
> feat: add .echo method to echo protocol

- packages/logger/README.md
- packages/logger/src/index.ts
debug was swapped for weald because it's in TypeScript, update the readme to reflect this.
> docs: update readme with link to weald

- .github/workflows/examples.yml
- doc/CONFIGURATION.md
- doc/migrations/v0.42-v0.43.md
- interop/test/fixtures/get-libp2p.ts
- packages/integration-tests/test/circuit-relay-discovery.node.ts
- packages/integration-tests/test/circuit-relay-discovery.spec.ts
- packages/integration-tests/test/circuit-relay.node.ts
- packages/logger/src/index.ts
- packages/transport-circuit-relay-v2/package.json
- packages/transport-circuit-relay-v2/src/constants.ts
- packages/transport-circuit-relay-v2/src/errors.ts
- packages/transport-circuit-relay-v2/src/transport/discovery.ts
- packages/transport-circuit-relay-v2/src/transport/index.ts
- packages/transport-circuit-relay-v2/src/transport/listener.ts
- packages/transport-circuit-relay-v2/src/transport/reservation-store.ts
- packages/transport-circuit-relay-v2/src/transport/transport.ts
- packages/transport-circuit-relay-v2/src/utils.ts
- packages/transport-circuit-relay-v2/test/transport/reservation-store.spec.ts
Refactors the circuit relay transport to behave like other transports
1. Specify the addresses to listen on in the `addresses.listen` config
2. Remove the `discoverRelays` option
3. Remove the transport manager listen call to just listen on configured addresses
4. Emit the `listen` event when listen addresses change like other transports
This fixes the instances where we miss relay address updates and the corresponding `self:peer:update` event never fires.
BREAKING CHANGE: The `discoverRelays` option has been removed, instead add one or more instances of `"/p2p-circuit"` to the libp2p config under the `addresses.listen` key
> fix!: make circuit relay listen on addresses like other transports

- README.md
- ROADMAP.md
- packages/libp2p/README.md
As discussed on the call there's a slight preference to having a roadmap file in the root of the repo for ease of reference and linking to.
All items were discussed on during the 2024 js colo, please add your thoughts to the PR.
> docs: add roadmap for 2024/early 25

- packages/peer-store/package.json
- packages/peer-store/src/store.ts
In cases where the peer store has grown very large (e.g. when a well connected node has been online for a long time), the peer store can get so large that this cache causes abnormal memory use.
The cache was added without any profiling, remove the cache for now, we can add it back if it actually solves a problem.
> fix: remove peer cache

- packages/metrics-prometheus/src/metric-group.ts
- packages/metrics-prometheus/test/metric-groups.spec.ts
We need to pass the metric label as the object key, otherwise trying to stop a group timer throws.
> fix: fix metric group timers

- packages/libp2p/src/upgrader.ts
- packages/libp2p/test/upgrading/upgrader.spec.ts
The `afterUpgradeInbound` function decrements the count of pending (e.g. not upgraded yet) incoming connections, so only invoke that method if we actually accepted the connection, otherwise we decrement a counter that was never incremented.
> fix: only update pending incoming connections if connection accepted

- packages/crypto/src/keys/rsa/utils.ts
When converting an asn1js Integer to a base64url encoded string, use the raw byte value instead of converting it to a string, then a bigint, then bytes.
This greatly improves performance with a large peer store, and RSA peers in general, particularly during startup.
Before:
After:
> fix: use raw asn1js int value to improve performance

- packages/protocol-echo/src/index.ts
Adds optional `AbortOptions` to interface, not sure why this wasn't there before.
> fix: add abort options to echo

- .github/workflows/main.yml
The `path` arg to `actions/cache` has to be the same every time it is used otherwise it causes cache misses.
> chore: fix ci cache

- packages/peer-id/package.json
- packages/peer-id/test/index.spec.ts
Makes sure we can use peer ids with sinon stubs without custom matchers.
> chore: add test to assert peer ids can be passed to stubs

- packages/upnp-nat/package.json
- packages/upnp-nat/src/check-external-address.ts
- packages/upnp-nat/src/errors.ts
- packages/upnp-nat/src/index.ts
- packages/upnp-nat/src/upnp-nat.ts
- packages/upnp-nat/test/index.spec.ts
- Updates NAT port mapper to handle unavailable ports
- Runs NAT port mapping on address change rather than once at startup
- Re-maps addresses when the public IP address changes
> fix: run UPnP nat on address change, update nat port mapper

- packages/integration-tests/.aegir.js
- packages/integration-tests/test/compliance/transport/circuit-relay.spec.ts
- packages/integration-tests/test/compliance/transport/memory.spec.ts
- packages/integration-tests/test/compliance/transport/tcp.spec.ts
- packages/integration-tests/test/compliance/transport/webrtc.spec.ts
- packages/integration-tests/test/compliance/transport/websockets.spec.ts
- packages/interface-compliance-tests/src/transport/index.ts
- packages/transport-webrtc/src/muxer.ts
- packages/transport-webrtc/src/stream.ts
CI is underpowered, the "many small writes" test overloads process and means the connection monitor thinks the remote has gone away so disable it during interface tests.
> chore: make tests more reliable in ci

- packages/upnp-nat/src/upnp-nat.ts
The user will need autonat to confirm addresses if not doing it automatically.
> fix: require autonat when not automatically confirming addresses

- packages/protocol-ping/src/ping.ts
This PR fixes the [UnexpectedEOFError issue](https://github.com/libp2p/js-libp2p/issues/2770). This issue happens because the ping protocol does not handle the case where the remote peer closes the stream and with the introduction of `connectionMonitor` this became an issue. It opens a stream for the ping protocol, sends a ping, gets the response then closes the stream. The local peer throws an exception and triggers a yamux reset.
> fix: gracefully handle remote stream closure during ping

- packages/integration-tests/test/circuit-relay.node.ts
- packages/utils/src/abstract-stream.ts
Adds a guard to the `.close` operation similar to the one on `.abort` that ensures we only close the stream if it is open.
The individual `.closeRead`/`.closeWrite` operations already guard on the read/write status of the stream so there's no functional change, we just avoid a bit more async work as those methods return promises.
> fix: only close stream if it is open

- packages/transport-webrtc/test/peer.spec.ts
The latest version of chrome changes the error message thrown from `signal.throwIfAborted`
> chore: update error message check

- packages/interface-compliance-tests/src/transport/index.ts
- packages/interface-compliance-tests/src/transport/utils.ts
The idea is if async work is done after `.dial` is invoked but before `upgrader.upgradeInbound` is called, and the abort signal aborts, then `.dial` should respect the abort and throw, but there's no reliable cross-transport way to inject the latency that would cause the test to fail so remove the test.
> fix: remove slow network test

- packages/libp2p/src/address-manager.ts
- packages/libp2p/test/addresses/address-manager.spec.ts
Adds an `appendAnnounce` key to the address manager's init type - any multiaddrs specified here will be added to the list of announced addresses.
> feat: add append announce addresses

- packages/upnp-nat/src/check-external-address.ts
- packages/upnp-nat/src/index.ts
- packages/upnp-nat/src/upnp-nat.ts
- packages/upnp-nat/test/index.spec.ts
Switch to the new public address mapping api in the address manager to ensure all host/port pairs are advertised with external ip addresses
BREAKING CHANGE: the `autoConfirmAddress` option has been removed
> fix!: use ip/port mapping

- packages/auto-tls/README.md
- packages/auto-tls/package.json
- packages/auto-tls/src/auto-tls.ts
- packages/auto-tls/src/constants.ts
- packages/auto-tls/src/index.ts
The p2p-forge service at libp2p.direct sometimes rejects requests with 401 errors, the only thing to do is to retry.
This can probably be reverted in future if it becomes clear why some requests are rejected.
> fix: add retries to certificate provisioning

- packages/auto-tls/src/auto-tls.ts
The `acme-client` module takes care of retries after 429s so no need to handle it at this level.
> chore: remove todo from auto tls

- packages/utils/src/multiaddr/is-private.ts
- packages/utils/test/multiaddr/is-private.spec.ts
Refactors the `isPrivate(multiaddr)` function to not require tcp/udp ports to be part of the address.
> fix: isPrivate should handle more types of addresses

- packages/utils/package.json
- packages/utils/src/multiaddr/is-link-local.ts
- packages/utils/test/multiaddr/is-link-local.spec.ts
Add function for detecting link-local multiaddrs
> feat: add isLinkLocal function

- packages/libp2p/package.json
- packages/libp2p/src/address-manager.ts
- packages/libp2p/test/addresses/address-manager.spec.ts
Handle the case where the router has an external IPv4 address but the internal network is IPv6 only, and vice versa.
> fix: handle router mappings of mixed IP version

- packages/peer-store/src/store.ts
- packages/peer-store/test/merge.spec.ts
- packages/peer-store/test/save.spec.ts
When we can't load or parse peerstore data, ignore it
> fix: ignore corrupt peerstore data

- packages/libp2p/src/address-manager.ts
- packages/libp2p/test/addresses/address-manager.spec.ts
Wildcard DNS servers let us map anything we think is a public ip address to a domain name, but ports stil need to be opened in firewalls so don't use the DNS mapping until an external port mapping has been configured.
> fix: confirm dns mappings with ip mappings

- packages/peer-store/src/store.ts
Only log an error when parsing peer data fails, not when it is not present.
> fix: only log when data is invalid

- packages/transport-websockets/src/listener.ts
Network interfaces generate their own link-local addresses when bootstrapping to the network.  With IPv4 these are discarded when a DHCP server assigns an address but IPv6 interfaces keep them around.
These aren't useful addresses after a routable address has been assigned so do not return them as addresses we are listening on.
> fix: ignore IPv6 link-local addresses

- packages/kad-dht/src/rpc/index.ts
- packages/kad-dht/test/rpc/handlers/ping.spec.ts
I was having a issue where 2 docker dht nodes failed to dht ping each other on startup. The streams would abort due to a read timeout. 
Also removed `key` from the ping tests as not required.
I don't think there needs to be a call to `this.routingTable.add` in `onIncomingStream` as it should be handled by the topology register.  Although alternatively maybe it could be moved to after the `pipe`?
Couldn't replicate the issue on localhost between 2 non-dockerised instances although I can provide docker files / test repo / logs if needed
> fix: do not add peers to routing table during RPC handling

- packages/protocol-identify/src/identify.ts
To prevent throwing when non-thin waist addresses are encountered, use `isPrivate` instead of converting the multiaddr to a node address.
> fix: use isPrivate to detect private multiaddrs

- packages/libp2p/src/address-manager.ts
- packages/libp2p/test/addresses/address-manager.spec.ts
This is done in the identify protocol but the address manager should guard itself against misuse.
> fix: limit observed addresses in address manager

- packages/utils/package.json
- packages/utils/src/global-unicast-ip.ts
- packages/utils/src/multiaddr/is-global-unicast.ts
- packages/utils/test/global-unicast-ip.spec.ts
- packages/utils/test/link-local-ip.spec.ts
- packages/utils/test/multiaddr/is-global-unicast.spec.ts
Adds functions for detecting global unicast IPv6 multiaddrs and IP addresses.
> feat: add isGlobalUnicast function

- packages/protocol-identify/src/identify.ts
- packages/protocol-identify/test/index.spec.ts
Only add public IPv4 or global unicast IPv6 addresses to the list of observed external addresses.
> fix: ignore observed IPv6 addresses that are not global unicast

- packages/interface-internal/src/address-manager/index.ts
- packages/libp2p/src/address-manager/dns-mappings.ts
- packages/libp2p/src/address-manager/index.ts
- packages/libp2p/src/address-manager/ip-mappings.ts
- packages/libp2p/src/address-manager/observed-addresses.ts
- packages/libp2p/src/address-manager/transport-addresses.ts
- packages/libp2p/src/connection-manager/index.ts
- packages/libp2p/test/addresses/address-manager.spec.ts
- packages/libp2p/test/connection-manager/index.spec.ts
Some routers will allocate global unicast addresses which peers will treat as publicly routable.  The routers may also firewall any incoming traffic to these addresses so require confirmation that the node is reachable before publishing such addresses.
> fix: require confirmation of global unicast addresses

- packages/interface-compliance-tests/src/mocks/connection-manager.ts
- packages/interface-internal/src/connection-manager/index.ts
Adds a method to expose the max connections config setting.
> feat: add getMaxConnections method to connection manager

- packages/protocol-autonat/src/autonat.ts
- packages/protocol-autonat/src/constants.ts
- packages/protocol-autonat/src/index.ts
- packages/protocol-autonat/test/index.spec.ts
If the node is close to it's max connections, skip reverification of previously verified addresses.
This is because the verifying node may find it hard to connect and then report that the address is undialable.
> fix: check max connections before reverifying addresses

- packages/upnp-nat/src/check-external-address.ts
Defer creating the last public ip promise until it's guaranteed to have a a listener for promise rejections.
Fixes ipfs/helia#702
> fix: unhandled promise rejection when finding gateway

- packages/interface-internal/src/address-manager/index.ts
- packages/libp2p/src/address-manager/index.ts
- packages/libp2p/test/addresses/address-manager.spec.ts
- packages/transport-circuit-relay-v2/src/transport/listener.ts
- packages/transport-circuit-relay-v2/src/transport/transport.ts
- packages/transport-circuit-relay-v2/test/listener.spec.ts
After we have created a reservation on a relay, automatically confirm that it is publicly dialable.
Fixes #2883
> fix: auto-confirm relay addresses

- packages/protocol-autonat/src/autonat.ts
- packages/protocol-autonat/src/constants.ts
- packages/protocol-autonat/src/index.ts
Allows more outgoing streams to be open at the same time and limits the allowed incoming message size.
> fix: increase max autonat streams and limit incoming message size

- packages/libp2p/src/connection-manager/dial-queue.ts
Where we fail to find any addresses for a peer id we are dialing, and we perform a routing query to find their addresses, pass the dial abort signal in to the query to ensure it doesn't continue if we are no longer interested in the result.
> fix: pass abort signal to peer routing query

- packages/transport-websockets/src/listener.ts
- packages/transport-websockets/test/node.ts
If `getAddrs` is called on a WS listener after `.listen` has been called but before any socket(s) have opened, return an empty list instead of throwing.
Fixes #2902
> fix: return empty address list during listen operation

- packages/integration-tests/test/fetch.spec.ts
- packages/protocol-fetch/README.md
- packages/protocol-fetch/src/fetch.ts
- packages/protocol-fetch/src/index.ts
- packages/protocol-fetch/src/pb/proto.proto
- packages/protocol-fetch/src/pb/proto.ts
- packages/protocol-fetch/test/index.spec.ts
To allow use cases like fetching IPNS records in a way compatible with go-libp2p we need to send binary as fetch identifiers.
JavaScript strings are UTF-16 so we can't round-trip binary reliably since some byte sequences are interpreted as multi-byte or otherwise non-printable characters.
Instead we need to accept Uint8Arrays and send them over the wire as-is.
This is a backwards compatible change as far as interop goes since protobuf `bytes` and `string` types are identical on the wire, but it's breaking for API consumers in that the lookup function now needs to accept a `Uint8Array` identifier instead of a `string`.
Refs: https://github.com/libp2p/specs/issues/656
BREAKING CHANGE: registered lookup functions now receive a Uint8Array identifier instead of a string
> fix!: accept Uint8Arrays as keys

- packages/pubsub-floodsub/src/index.ts
Add missing service capabilities
This is used to know when a service as the pub sub capabilities
> fix: add missing service capabilities

- packages/auto-tls/src/auto-tls.ts
- packages/auto-tls/src/index.ts
To allow declaring services in any order, access components via a components property after all services are constructed.
> fix: access components via property

- packages/interface/src/keys/index.ts
- Correct small typo. I'm pretty sure the `raw` field on the private key types is the actual private key
> docs: correct typo in private key type

- packages/auto-tls/README.md
- packages/auto-tls/src/index.ts
Signed-off-by: Sacha Froment <sfroment42@gmail.com>
> docs: wss as been replaced with tls/ws and autoNat is mandatory

- packages/utils/package.json
- packages/utils/src/is-async-generator.ts
- packages/utils/src/is-generator.ts
- packages/utils/test/is-async-generator.spec.ts
- packages/utils/test/is-generator.spec.ts
- packages/utils/test/is-promise.spec.ts
- packages/utils/typedoc.json
Functions like this are used in several places in the stack so move them to the utils package for reuse.
Incorporates changes from #2918
> feat: add generator detection functions to utils

- .github/workflows/main.yml
- interop/firefox-version.json
Firefox 134.0 has broken interop as it can no longer dial go-libp2p via WebTransport.
The regression is fixed in Firefox Nightly (136.0) so disable Firefox WebTransport interop testing until that has been released and Playwright has upgraded the version it supports (likely some time in March) or until go-libp2p ships a fix that allows dialling it again.
> chore: disable Firefox WebTransport interop tests

- packages/crypto/src/keys/ed25519/index.ts
Although [RFC7518 6.3.2](https://datatracker.ietf.org/doc/html/rfc7518#section-6.3.2) specifies that private key JWKs must include all the fields present in the public key, this is not the case for the implementation of `node:crypto.generateKeyPairSync` in the deno runtime.
While Node returns the (same) `x` property in both, the `privateKey` and the `publicKey`, Deno only returns the `x` property in `publicKey` (i.e. [no x here](https://github.com/denoland/deno/blob/88490d092751288f736855b2418a4da606a31ce7/ext/node/ops/crypto/keys.rs#L1475)).
This change should not affect any Node users, but would enable the use of libp2p on Deno.
> fix: use publicKey.x instead of privateKey.x

- packages/integration-tests/test/dcutr.node.ts
- packages/interface-internal/src/connection-manager/index.ts
- packages/interface/src/transport/index.ts
- packages/libp2p/src/upgrader.ts
- packages/protocol-dcutr/src/dcutr.ts
According to the DCUtR spec to complete a holepunch via TCP Simultaneous Connect, the dialer (B) needs to act as a multistream-select server rather than a client, otherwise both sides will try to initiate mss which will fail.
> fix: allow overriding mss mode

- packages/auto-tls/src/auto-tls.ts
- packages/auto-tls/src/index.ts
- packages/auto-tls/test/index.spec.ts
Sends a js-libp2p specific user agent to libp2p.direct while configuring the ACME DNS-01 response.
The user agent can be overridden but the default is something like:
```
js-libp2p/2.5.1 node/20.1.5
```
Refs: https://github.com/ipshipyard/p2p-forge/issues/48
> fix: send user agent during auto tls

- packages/utils/src/repeating-task.ts
- packages/utils/test/repeating-task.spec.ts
To allow for changing the frequency and timeout of repeating tasks add `setInterval` and `setTimeout` methods to the task.
This lets us repeat a task often to start with, then slow down the repetition once a successful result has occured.
> feat: allow changing repeating task interval and timeout

- packages/libp2p/src/address-manager/observed-addresses.ts
Without this we continually re-validate observed addresses which causes a lot of unecessary network activity.
> fix: set expires on observed address

- packages/upnp-nat/README.md
- packages/upnp-nat/src/check-external-address.ts
- packages/upnp-nat/src/index.ts
- packages/upnp-nat/src/search-gateway-finder.ts
- packages/upnp-nat/src/static-gateway-finder.ts
- packages/upnp-nat/src/upnp-nat.ts
- packages/upnp-nat/src/upnp-port-mapper.ts
Some ISP-provided routers are underpowered and require frequent reboots before they will respond to SSDP M-SEARCH messages.
To make working with them easier, allow manually specifying gateways and external network addresses.
> feat: allow specifying UPnP gateways and external address

- packages/libp2p/package.json
- packages/libp2p/src/address-manager/index.ts
- packages/libp2p/test/addresses/address-manager.spec.ts
When an observed address with a publicly routable IPv4 host is confirmed by autonat, and there's only one listener it could be associated with, upgrade the observed address to an IP mapping, this allows the DNS mapping to add SNI tuples to corresponding transport addresses with a TLS tuple.
This will, for example, detect when external infrastructure such as a router has been configured manually (e.g. not by UPnP) to forward traffic to the current node.
Fixes #2929
> fix: upgrade observed address to ip mapping

- packages/auto-tls/src/auto-tls.ts
- packages/auto-tls/src/index.ts
- packages/auto-tls/test/index.spec.ts
- packages/interface/src/index.ts
- packages/libp2p/.aegir.js
- packages/libp2p/package.json
- packages/libp2p/src/index.ts
- packages/libp2p/src/libp2p.ts
- packages/libp2p/src/user-agent.browser.ts
- packages/libp2p/src/user-agent.react-native.ts
- packages/libp2p/src/user-agent.ts
- packages/libp2p/test/core/user-agent.spec.ts
- packages/libp2p/typedoc.json
- packages/metrics-opentelemetry/test/index.spec.ts
- packages/protocol-identify/package.json
- packages/protocol-identify/src/index.ts
- packages/protocol-identify/src/utils.ts
- packages/protocol-identify/test/index.spec.ts
- packages/protocol-identify/test/push.spec.ts
- packages/upnp-nat/test/index.spec.ts
Adds a `userAgent` property to `NodeInfo` that includes the platform the node is running on with detection for node, browsers, electron, deno, bun and react-native.
Also allows importing the user agent function for reuse elsewhere.
the node is running on with detection for node, browsers, electron,
deno, bun and react-native.
Also allows importing the user agent function for reuse elsewhere so applications can easily extend the user agent with their own information.
> fix: include platform in user agent

- packages/interface-internal/src/registrar/index.ts
- packages/interface/src/index.ts
- packages/interface/src/stream-handler/index.ts
- packages/libp2p/src/libp2p.ts
- packages/libp2p/src/registrar.ts
- packages/libp2p/test/registrar/errors.spec.ts
- packages/libp2p/test/registrar/protocols.spec.ts
- packages/libp2p/test/registrar/registrar.spec.ts
Adds a `force` flag to `libp2p.handle` that means the method will not throw if a handler already exists for the protocol being handled.
Fixes #2928
> feat: allow overriding stream handlers

- packages/libp2p/package.json
Add a browser override in the exports map in case the "browsers" field is not picked up.
> fix: override user agent in exports map

- packages/libp2p/src/connection-manager/index.ts
- packages/libp2p/src/libp2p.ts
- packages/libp2p/src/upgrader.ts
Only fall back to the configured upgrade timeout if no abort signal was passed to the dial, otherwise let the user decide when to cancel.
Also expose the inbound/outbound protocol negotiation timeout settings.
> fix: respect dial signal and expose protocol negotiation timeouts

- packages/upnp-nat/package.json
- packages/upnp-nat/src/upnp-nat.browser.ts
- packages/upnp-nat/test/browser.ts
To give more helpful error messages, add a browser shim for upnp-nat, similar to `@libp2p/tcp` - without this the user gets errors about not being able to load node api modules, instead throw a specific error that tells them their configuration is invalid.
> fix: add browser polyfill to upnp-nat

- packages/transport-tcp/src/tcp.browser.ts
Removes unused imports and properties.
> fix: remove unused fields from browser polyfill

- packages/interface-internal/src/address-manager.ts
- packages/interface-internal/src/connection-manager.ts
- packages/interface-internal/src/index.ts
- packages/interface-internal/src/random-walk.ts
- packages/interface-internal/src/registrar.ts
- packages/interface-internal/src/transport-manager.ts
docs: Add TSDoc comments to @libp2p/interface-internal (#2113 )
This PR adds TSDoc comments to `@libp2p/interface-internal`, ensuring that all exported interfaces, types, and constants have proper documentation. This improves the generated API documentation and aligns with the project's documentation standards.
- Please review if the added examples align with best practices.
- Let me know if any additional clarifications are needed.
> docs: add TSDoc comments interface-internal module

- packages/transport-tcp/package.json
The browser override for the tcp module throws if the user tries to use it in a browser environment.
React-native can run a tcp polyfill but selects the browser override so add a react-native override that selects the node implementation.
Fixes #2969
> fix: override browser override for react-native

- packages/transport-webrtc/package.json
- packages/transport-webrtc/src/private-to-public/listener.ts
- packages/transport-webrtc/src/private-to-public/transport.ts
- packages/transport-webrtc/src/private-to-public/utils/stun-listener.ts
Note: This is my second attempt, I put it on a completely clean feature branch this time.
This PR removes the dependency on the abandoned `stun` package from the WebRTC transport implementation, which had critical security vulnerabilities through its dependencies:
- `ip`: SSRF vulnerability in isPublic categorization
- `parse-path`: Authorization bypass vulnerability
- `trim-newlines`: Uncontrolled resource consumption
- `yargs-parser`: Prototype pollution vulnerability
The change replaces the STUN message handling with the built-in implementation from `@ipshipyard/node-datachannel`, which we already use for most of our WebRTC functionality. This simplifies our dependency tree and removes these security issues without affecting functionality.
All tests are passing and npm audit now …
> fix(webrtc): remove vulnerable unmaintained stun package dependency

- packages/keychain/src/index.ts
- packages/keychain/src/keychain.ts
- packages/keychain/test/keychain.spec.ts
To allow the node's private key to be stored under a name other than 'self', allow passing the name of the self-key as a config option.
> feat: allow configuring self key name

- packages/config/src/load-private-key.ts
- packages/config/test/load-private-key.spec.ts
Allows passing a `selfKey` param to use a different name for the self key.
> feat: allow configuring self-key name in config

- packages/interface/src/transport.ts
- packages/libp2p/src/address-manager/index.ts
- packages/transport-circuit-relay-v2/src/transport/listener.ts
- packages/transport-memory/src/listener.ts
- packages/transport-tcp/src/listener.ts
- packages/transport-webrtc/package.json
- packages/transport-webrtc/src/private-to-private/listener.ts
- packages/transport-webrtc/src/private-to-public/listener.browser.ts
- packages/transport-webrtc/src/private-to-public/listener.ts
- packages/transport-webrtc/test/transport.spec.ts
- packages/transport-websockets/src/listener.ts
In cases where the published multiaddr for a given transport needs to have a component that can only be known at runtime, allow transports to modify configured announce addresses.
This lets WebRTC Direct add `/certhash` tuples to announced addrs.
> feat: allow transports to modify announce addresses

- packages/integration-tests/test/webrtc-private-to-private.spec.ts
- packages/transport-webrtc/src/private-to-private/listener.ts
- packages/transport-webrtc/src/private-to-private/transport.ts
Fixes https://github.com/libp2p/js-libp2p/issues/2539
> fix: maximum call stack size with duplicate webrtc addresses

- interop/test/fixtures/get-libp2p.ts
- interop/test/fixtures/relay.ts
- packages/integration-tests/test/bootstrap.spec.ts
- packages/integration-tests/test/circuit-relay-discovery.spec.ts
- packages/integration-tests/test/circuit-relay.spec.ts
- packages/integration-tests/test/compliance/transport/circuit-relay.spec.ts
- packages/integration-tests/test/compliance/transport/webrtc.spec.ts
- packages/integration-tests/test/compliance/transport/websockets.spec.ts
- packages/integration-tests/test/fixtures/base-options.browser.ts
- packages/integration-tests/test/fixtures/base-options.ts
- packages/transport-webrtc/README.md
- packages/transport-webrtc/src/index.ts
- packages/transport-websockets/src/filters.ts
These are deprecated in favour of the connection gater so remove their use in the codebase.
> fix: remove ws filters

- packages/libp2p/src/libp2p.ts
The agent version string had the module name twice.
> fix: report version correctly

- packages/kad-dht/package.json
- packages/libp2p/package.json
- packages/multistream-select/package.json
- packages/transport-circuit-relay-v2/package.json
- packages/transport-webrtc/package.json
- packages/transport-websockets/package.json
- packages/transport-webtransport/package.json
- packages/upnp-nat/package.json
- packages/utils/package.json
1.1.2 fixes a potential crash so ensure we get the latest version.
Fixes #2702
> fix: update race-signal

- packages/transport-webrtc/src/constants.ts
- packages/transport-webrtc/src/private-to-public/listener.ts
- packages/transport-webrtc/src/private-to-public/transport.ts
- packages/transport-webrtc/src/private-to-public/utils/connect.ts
- packages/transport-webrtc/src/private-to-public/utils/sdp.ts
To allow the noise handshake to time out, pass the abort signal to the upgrade methods
> fix: pass abort signal to noise and the upgrader

- packages/transport-tcp/package.json
- packages/transport-tcp/src/constants.ts
- packages/transport-tcp/src/index.ts
- packages/transport-tcp/src/listener.ts
- packages/transport-tcp/src/tcp.ts
Similar to other transports, this lets us close the connection if encryption/muxer negotiation takes too long.  Defaults to 10s.
> fix: add inbound upgrade timeout config option

- packages/transport-webrtc/src/private-to-private/listener.ts
- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/test/listener.spec.ts
- packages/transport-webrtc/test/peer.spec.ts
Instead of emitting the 'listening' event as soon as the transport is started, emit it after we start listening on a circuit relay address.
> fix: emit listening event after circuit relays listen

- packages/libp2p/src/errors.ts
- packages/libp2p/src/transport-manager.ts
- packages/libp2p/test/transports/transport-manager.spec.ts
- packages/transport-webrtc/src/private-to-private/listener.ts
- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/test/listener.spec.ts
- packages/transport-webrtc/test/peer.spec.ts
If listening on all IPv4 addresses succeeds but listening on all IPv6 addresses fails, we may be on a network that doesn't support IPv6 so ignore the failure.
Fixes #2977
> fix: ignore failures to listen on IPv6 addresses when IPv4 succeeds

- packages/integration-tests/.aegir.js
- packages/kad-dht/.aegir.js
- packages/metrics-prometheus/.aegir.js
- packages/pubsub-floodsub/.aegir.js
- packages/stream-multiplexer-mplex/.aegir.js
Where a relay server is started, use a prefix logger to prevent DEBUG output clashing with the unit under test
> chore: use prefix logger

- packages/integration-tests/test/listening.spec.ts
- packages/libp2p/src/errors.ts
- packages/libp2p/src/transport-manager.ts
- packages/libp2p/test/transports/transport-manager.spec.ts
When transports fail to listen, include specific error messages and advice on how to proceed.
> fix: improve error message when starting server

- packages/kad-dht/benchmarks/add-with-kad-id.js
- packages/kad-dht/package.json
- packages/kad-dht/src/peer-distance-list.ts
- packages/kad-dht/src/routing-table/k-bucket.ts
Refactors `addWithKadId` to splice the new entry into the list rather than adding it and then sorting.
This becomes a bottleneck when the routing table is full (~5k nodes).
> fix: improve kad distance list performance

- packages/transport-tcp/src/utils.ts
Solves a port conflict if both ip4 and ip6 wildcard ports are listened on.
Only seems to affect some Linuxes.
> fix: constrain ip6 listener to ip6 addresses

- packages/crypto/package.json
- packages/keychain/package.json
- packages/logger/package.json
- packages/peer-discovery-bootstrap/package.json
- packages/peer-record/package.json
- packages/peer-store/package.json
- packages/pubsub-floodsub/package.json
- packages/transport-webtransport/package.json
- packages/utils/package.json
fix: .d.ts is in ./dist folder
Since the export is badly done when you try to resolve with esplugin import it will lead to 
1:27  error  Unable to resolve path to module '@libp2p/bootstrap'    import/no-unresolved
> fix: .d.ts is in ./dist folder

- packages/interface-compliance-tests/src/mocks/upgrader.ts
- packages/interface/src/connection-encrypter.ts
- packages/interface/src/transport.ts
- packages/libp2p/src/upgrader.ts
- packages/libp2p/test/upgrading/upgrader.spec.ts
- packages/libp2p/test/upgrading/utils.ts
Some encrypters allow sending application protocols along with the initial handshake.
We can use these to select muxers and save the round-trips of mss.
> feat: allow early muxer selection by connection encrypters

- packages/connection-encrypter-plaintext/src/pb/proto.proto
- packages/connection-encrypter-plaintext/src/pb/proto.ts
Mark the field `optional` so we always send it on the wire, otherwise proto2 decoders that have it marked `required` will fail to decode the incoming message.
> fix: always send key type

- packages/kad-dht/src/index.ts
- packages/kad-dht/src/routing-table/index.ts
- packages/kad-dht/test/routing-table.spec.ts
Reduces the default routing table size to 1280 (down from 5120).
This improves CPU/memory/network usage as we don't need to sort as many peers when finding the closest ones to a given key, nor do we need to contact as many to ensure only live peers are still in the table.
> fix: decrease default routing table size

- packages/transport-webtransport/package.json
- packages/transport-webtransport/src/index.ts
- packages/transport-webtransport/test/transport.spec.ts
Compatibility fix ahead of https://github.com/ChainSafe/js-libp2p-noise/pull/482
> fix: pass upgrader to noise

- packages/transport-webrtc/src/constants.ts
fix: drain timeout is 30s no 301s
Before it was 30s https://github.com/libp2p/js-libp2p/pull/3005/files#diff-622f25d2f456a8282d3c1a3fe645b8a63044e11f384fabdad6ac7fc78eafa090L16 so I think it is just a typo
> fix: drain timeout is 30s no 301s

- packages/peer-id/src/index.ts
- packages/peer-id/test/index.spec.ts
Given the prevalence of both CID encoded PeerIDs and base58mh encoded ones, I found myself defining this function in multiple places. 
This PR introduces this as a helper (as was supported in an earlier version of js-libp2p)
> feat: support parsing base32 and base36 libp2p-key CIDs in peerIdFromString

- packages/utils/package.json
- packages/utils/src/get-thin-waist-addresses.browser.ts
- packages/utils/src/get-thin-waist-addresses.ts
- packages/utils/test/get-thin-waist-addresses.spec.ts
Adds a utillity to get all thin waist addresses for the current host, expanding ip4/ip6 wildcards as appropriate.
Largely ports the code from `@libp2p/tcp` for use elsewhere.
> feat: add util to get thin waist addresses

- packages/transport-tcp/package.json
- packages/transport-tcp/src/constants.ts
- packages/transport-tcp/src/listener.ts
- packages/transport-tcp/src/tcp.ts
- packages/transport-tcp/src/utils.ts
- packages/transport-tcp/test/filter.spec.ts
- packages/transport-tcp/test/listen-dial.spec.ts
- packages/transport-webrtc/src/private-to-public/listener.ts
- packages/transport-webrtc/test/transport.spec.ts
- packages/transport-websockets/src/listener.ts
- packages/transport-websockets/test/node.ts
- packages/utils/src/get-thin-waist-addresses.browser.ts
- packages/utils/src/get-thin-waist-addresses.ts
- packages/utils/src/link-local-ip.ts
- packages/utils/test/get-thin-waist-addresses.spec.ts
- packages/utils/typedoc.json
Instead of every tcp/udp transport calculating thin waist addresses, use the function in `@libp2p/utils` instead.
> fix: use getThinWaistAddresss function

- interop/node-version.json
- interop/package.json
- interop/test/fixtures/get-libp2p.ts
Tests the experimental quic transport from @chainsafe/libp2p-quic
> test: add @chainsafe/libp2p-quic to interop suite

- packages/transport-webrtc/src/private-to-public/listener.ts
- packages/transport-webrtc/test/transport.spec.ts
If we are passed a wildcard port, start a UDP mux listener on a ephemeral port, otherwise check the existing listeners before trying to start a new one.
To be reused an existing listener must be owned by the current peer and be of the other IP family (e.g. you cannot listen on `[ip4-host]:1234` twice but you can listen on `[ip4-host:1234]` and `[ip6-host]:1234`.
Fixes #3049
> fix: only check for non-wildcard ports

- packages/peer-store/src/store.ts
- packages/peer-store/test/index.spec.ts
Do not apply address/record expiry to the peer store entry for the self peer.
Fixes #3051
> fix: do not expire self multiaddrs

- packages/connection-encrypter-tls/package.json
- packages/connection-encrypter-tls/src/utils.ts
To reduce memory usage, use a queueless pushable which will wait for the consumer to consume a buffer before accepting another.
Pauses incoming streams until the application has read the data.
> fix: add backpressure to tls encryption

- packages/keychain/package.json
- packages/keychain/src/index.ts
- packages/keychain/src/keychain.ts
- packages/keychain/test/certificates.spec.ts
- packages/keychain/test/fixtures/create-certificate.ts
- packages/keychain/test/keychain.spec.ts
Adds `importX509`/`exportX509`/etc methods to the keychain to enable storing x509 certificates securely.
> feat: store x509 certs in the keychain

- packages/transport-webrtc/src/constants.ts
- packages/transport-webrtc/src/private-to-public/listener.ts
- packages/transport-webrtc/src/private-to-public/transport.ts
- packages/transport-webrtc/test/certificates.spec.ts
- packages/transport-webrtc/test/transport.spec.ts
Lowers the validity of webrtc direct certs to two weeks similar to webtransport and updates listening multiaddrs after the cert has been renewed.
The validity is lowered because the longest `setTimeout` we can do is just under a month, otherwise we overflow the max value we can pass to `setTimeout`.
> fix: rotate webrtc direct certificates

- .github/workflows/examples.yml
- packages/integration-tests/test/circuit-relay-discovery.node.ts
- packages/integration-tests/test/dht.node.ts
- packages/integration-tests/test/interop.ts
- packages/kad-dht/README.md
- packages/kad-dht/package.json
- packages/kad-dht/src/index.ts
- packages/kad-dht/src/kad-dht.ts
- packages/kad-dht/src/routing-table/index.ts
- packages/kad-dht/test/generate-peers/generate-peers.node.ts
- packages/kad-dht/test/libp2p-routing.spec.ts
- packages/kad-dht/test/routing-table.spec.ts
- packages/kad-dht/test/utils/test-dht.ts
The [kad-dht spec](s://github.com/libp2p/specs/tree/master/kad-dht) says:
> PING: Deprecated message type replaced by the dedicated ping protocol. Implementations may still handle incoming PING requests for backwards compatibility. Implementations must not actively send PING requests.
Switch to using `@libp2p/ping` instead of KAD-DHT `PING` messages to be compliant with the spec.
Incoming KAD-DHT `PING` messages are still supported.
Refs: https://github.com/libp2p/js-libp2p/discussions/3058
Fixes: https://github.com/libp2p/js-libp2p/issues/3072
BREAKING CHANGE: `@libp2p/kad-dht` now depends on `@libp2p/ping` - please configure this in your service map
> fix!: use libp2p ping instad of kad ping

- packages/libp2p/src/connection-manager/dial-queue.ts
Some `ErrorEvent` implementations don't have a `.detail` field so null-guard on it before accessing properties.
> fix: allow empty error events

- packages/connection-encrypter-tls/src/tls.ts
- packages/connection-encrypter-tls/test/index.spec.ts
- packages/interface/src/connection-encrypter.ts
Some transports have their own muxers but use existing encrypers to do a handshake so skip sending muxer lists as it is not necessary.
> feat: add skip muxer negotiation

- .github/workflows/main.yml
- packages/transport-webrtc/src/private-to-public/utils/connect.ts
- packages/transport-webrtc/src/stream.ts
Removes the closing of the handshake datachannel after the connection has been opened because it breaks compatibility with rust-libp2p 53.
This can be revisited after https://github.com/libp2p/rust-libp2p/issues/5986 is resolved.
> fix: partial revert of #3076 - do not close handshake channel

- packages/libp2p/src/address-manager/index.ts
- packages/libp2p/test/addresses/address-manager.spec.ts
We allow transports to update announce addresses to add certhashes and other data but updating append announce addresses was missed.
Fixes #3080
> fix: update append announce addresses

- packages/transport-webrtc/src/private-to-public/utils/connect.ts
- packages/transport-webtransport/src/index.ts
Skips early muxer negotiation during noise handshake since WebRTC incorporates it's own muxer.
Fixes an edge case where a node is only configured with the WebRTC-Direct transport and no additional muxers.
Refs: https://github.com/ChainSafe/js-libp2p-noise/pull/519
Refs: https://github.com/ipshipyard/roadmaps/issues/22
> fix: skip muxer negotiation

- packages/libp2p/src/content-routing.ts
- packages/libp2p/src/peer-routing.ts
- packages/libp2p/test/content-routing/content-routing.spec.ts
- packages/libp2p/test/peer-routing/peer-routing.spec.ts
So routing implementations don't have to have empty methods for features they don't support, guard on the routing method being present before invoking it.
> fix: allow partial routing implementations

- packages/transport-webrtc/src/webrtc/index.ts
- packages/transport-webrtc/test/muxer.spec.ts
Since https://github.com/murat-dogan/node-datachannel/pull/346 `node-datachannel` returns global types where appropriate so it's no longer necessary to export the polyfill versions.
Refs https://github.com/libp2p/js-libp2p/pull/3095#issuecomment-2855245991
> fix: remove redundant types

- packages/interface/src/peer-store.ts
- packages/peer-store/src/index.ts
- packages/peer-store/src/utils/dedupe-addresses.ts
- packages/peer-store/test/index.spec.ts
Adds a function to return a `PeerInfo` object - this is more lightweight than a full `Peer` object as it only contains the peer id and the listening addresses and is commonly used for exchanging peer information.
> feat: add getInfo function to peerstore

- packages/transport-circuit-relay-v2/src/transport/transport.ts
- packages/transport-memory/src/listener.ts
- packages/transport-webrtc/src/private-to-public/listener.ts
- packages/transport-websockets/src/listener.ts
Silences `MaxListenersExceededWarning` for shutdown controller signals
- it is expected because they are used a lot.
> fix: increase signal listeners

- packages/libp2p/test/connection-monitor/index.spec.ts
- packages/utils/src/adaptive-timeout.ts
- packages/utils/test/adaptive-timeout.spec.ts
2s is too small, increase to 5s.
> fix: increase default adaptive timeout

- packages/utils/src/queue/index.ts
- packages/utils/test/queue.spec.ts
Browsers and Node.js handle resuming control from `yield` slightly differently - a queue that empties in browsers can end up repeating it's idle even when a new job is being added so debounce the call to trigger after a (very) short time has passed.
> fix: debounce queue idle/empty events

- packages/interface-compliance-tests/src/mocks/connection-manager.ts
- packages/interface-compliance-tests/src/mocks/connection.ts
Check the abort signal and throw if it has been aborted
> fix: abort open connection and new stream

- packages/kad-dht/package.json
- packages/kad-dht/src/constants.ts
- packages/kad-dht/src/content-fetching/index.ts
- packages/kad-dht/src/content-routing/index.ts
- packages/kad-dht/src/index.ts
- packages/kad-dht/src/kad-dht.ts
- packages/kad-dht/src/network.ts
- packages/kad-dht/src/peer-distance-list.ts
- packages/kad-dht/src/peer-routing/index.ts
- packages/kad-dht/src/providers.ts
- packages/kad-dht/src/query/events.ts
- packages/kad-dht/src/query/manager.ts
- packages/kad-dht/src/query/query-path.ts
- packages/kad-dht/src/query/types.ts
- packages/kad-dht/src/rpc/handlers/get-providers.ts
- packages/kad-dht/src/utils.ts
- packages/kad-dht/test/content-routing.spec.ts
- packages/kad-dht/test/kad-dht.spec.ts
- packages/kad-dht/test/libp2p-routing.spec.ts
- packages/kad-dht/test/network.spec.ts
- packages/kad-dht/test/peer-routing.spec.ts
- packages/kad-dht/test/query-self.spec.ts
- packages/kad-dht/test/query.spec.ts
- packages/kad-dht/test/routing-table.spec.ts
- packages/kad-dht/test/rpc/handlers/get-providers.spec.ts
- packages/kad-dht/test/utils/test-dht.ts
- Increase alpha to 10
- Split starting peers into multiple disjoint buckets
- Report disjoint path info on events
- Abort slow subqueries at the network level instead of query and network
- Use a filter to separate disjoint paths
- Only add closer peers to our list of closer peers if they are actually closer
> fix: ensure greater spec compliance

- packages/metrics-devtools/package.json
- packages/metrics-devtools/src/index.ts
- packages/metrics-devtools/src/rpc/index.ts
To prevent the outgoing message queue growing when remote consumers are slow, add a timeout for the outgoing messages.
> fix: timeout sending rpc messages after a while

- packages/interface/src/event-target.ts
When using `safeDispatchEvent`, make the detail arg optional as it is not always required.
> fix: make event detail optional

- packages/transport-tcp/src/index.ts
- packages/transport-tcp/src/listener.ts
If the server is paused and resumed, the `listening` event handler is invoked again.
Move metric registration out of the handler so it is not repeated.
> fix: do not re-register metrics

- packages/libp2p/src/address-manager/dns-mappings.ts
- packages/libp2p/src/address-manager/index.ts
- packages/libp2p/src/address-manager/ip-mappings.ts
- packages/libp2p/src/address-manager/observed-addresses.ts
- packages/libp2p/src/address-manager/transport-addresses.ts
- packages/libp2p/src/registrar.ts
- packages/libp2p/src/transport-manager.ts
- packages/libp2p/src/upgrader.ts
- packages/protocol-autonat/src/autonat.ts
- packages/protocol-autonat/src/index.ts
Adds metrics tracking the size of long-lived maps to make debugging memory leaks easier.
> fix: add tracking for long-lived maps

- packages/peer-store/package.json
- packages/peer-store/src/index.ts
- packages/peer-store/src/store.ts
- packages/peer-store/src/utils/bytes-to-peer.ts
- packages/peer-store/src/utils/to-peer-pb.ts
- packages/peer-store/test/index.spec.ts
Instead of locking the whole peer store on a multi-read/single-write basis, make the lock more granular and use a per-peer-id lock.
> fix: use a per-peer lock

- packages/utils/src/adaptive-timeout.ts
- packages/utils/test/adaptive-timeout.spec.ts
Add a setting to allow constraining the timeout value to a maximum.
> fix: constrain maximum timeout value

- packages/libp2p/src/libp2p.ts
Allow the peerstore to record metrics
> fix: pass metrics to peerstore

- packages/kad-dht/src/routing-table/index.ts
- packages/kad-dht/src/routing-table/k-bucket.ts
- packages/kad-dht/test/routing-table.spec.ts
When the node is stopped, empty the routing table
> fix: empty routing table on stop

- packages/peer-store/package.json
- packages/peer-store/src/store.ts
Removes lock from storage after use
> fix: finalize peerstore lock after use

- .github/workflows/main.yml
nim-libp2p does not build at the moment so disable temporarily.
> chore: disable interop testing against nim-libp2p

- packages/utils/src/repeating-task.ts
- packages/utils/test/repeating-task.spec.ts
Adds a `.run` method to a repeating task that lets us interrupt the timeout to run immediately (debounced) before rescheduling the task to run again in the future.
> feat: allow interrupting repeating task

- packages/interface-compliance-tests/src/stream-muxer/base-test.ts
Instead of the weird double-sink of `[]`, use the `.close` method to explicitly close streams and muxers.
> fix: use `.close()` to close streams

- packages/interface/package.json
- packages/interface/src/index.ts
- packages/libp2p/src/config.ts
- packages/libp2p/src/connection-manager/constants.defaults.ts
- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/libp2p/src/connection-manager/index.ts
- packages/libp2p/src/connection-manager/resolvers/dnsaddr.ts
- packages/libp2p/src/connection-manager/resolvers/index.ts
- packages/libp2p/src/connection-manager/utils.ts
- packages/libp2p/src/errors.ts
- packages/libp2p/src/index.ts
- packages/libp2p/test/connection-manager/dial-queue.spec.ts
- packages/libp2p/test/connection-manager/resolvers.spec.ts
Use internal multiaddr resolvers so they can be removed from the Multiaddr class to make it more lightweight.
> fix: add multiaddr resolvers

- packages/kad-dht/src/content-routing/index.ts
- packages/kad-dht/src/query/query-path.ts
- packages/libp2p/src/connection-manager/dial-queue.ts
- packages/utils/src/queue/index.ts
- packages/utils/test/peer-job-queue.spec.ts
- packages/utils/test/queue.spec.ts
Ignore the error event as it causes `raceEvent` to throw. In future we should remove the error event from the queue as all we do with it is log the error, and if we want that, the `failure` event gives more context around the error so can make the logs more informative.
> fix: use failure event instead of error

- packages/kad-dht/src/routing-table/index.ts
Increase the maximum number of listeners for the routing table's shutdown controller signal.
> fix: silence max listeners warning for dht routing table

- packages/integration-tests/test/connection-gater.spec.ts
We have unit test for the connection gater, but add integration tests to ensure that any custom configured component is passed through correctly.
> test: add connection gater integration tests

- packages/kad-dht/README.md
Replaced the outdated API documentation link with the new, working URL (https://libp2p.github.io/js-libp2p-kad-dht/) in the README. This ensures users can access the latest auto-generated documentation for @libp2p/kad-dht.
> docs: update kad-dht api docs link

- packages/utils/src/stream-utils.ts
To prevent the hasBytes promise rejecting before it is awaited, defer creation until it's about to be used.
> fix: create hasBytes promise before await

- packages/transport-websockets/package.json
- packages/transport-websockets/src/index.ts
The global WebSocket instance is used in node.js now so remove unused options.
> fix: remove it-ws

- interop/BrowserDockerfile
- interop/README.md
- packages/interface-compliance-tests/src/transport/index.ts
- packages/protocol-identify/src/identify.ts
- packages/transport-webrtc/src/muxer.ts
- packages/transport-webrtc/src/private-to-private/initiate-connection.ts
- packages/transport-webrtc/src/private-to-private/transport.ts
- packages/transport-webrtc/src/private-to-public/listener.ts
- packages/transport-webrtc/src/private-to-public/transport.ts
- packages/transport-webrtc/src/private-to-public/utils/connect.ts
- packages/transport-webrtc/src/private-to-public/utils/get-rtcpeerconnection.browser.ts
- packages/transport-webrtc/src/private-to-public/utils/get-rtcpeerconnection.ts
- packages/transport-webrtc/src/rtcpeerconnection-to-conn.ts
- packages/transport-webrtc/src/stream.ts
- packages/transport-webrtc/test/maconn.spec.ts
Chrome can receive data before a datachannel is open, and receive datachannels before a peer connection is open so handle that.
> fix: capture early datachannels

- packages/pnet/src/index.ts
If the remote sends more data than just the pnet handshake it can be missed by the onwards boxed stream so unwrap the byte stream which will push the extra bytes back onto the connection.
> fix: unwrap connection for boxed stream

- packages/interface/src/message-stream.ts
- packages/utils/src/abstract-message-stream.ts
- packages/utils/test/stream-utils-test.spec.ts
Allow pushing data onto the front of any queued data, not just after
> fix: allow stream unshift

- .github/workflows/main.yml
Remove usage of self-hosted runners.
This PR removes usage of self-hosted runners from the test-interop job.
It is part of libp2p DX services offboarding initiative.
> [!WARNING]
> The interop tests are not failing on the default branch.
> ci: remove usage of self-hosted runners
