README.md
See https://github.com/ipfs/js-ipfs/pull/385 for details
=> docs(readme): add package listing

README.md
=> Remove word below

package.json
Added missing rep, required [here](https://github.com/libp2p/js-libp2p/blob/master/src/index.js#L7-L8).
=> fix: added missing dep async

README.md, examples/README.md, examples/peer-and-content-routing/1.js, examples/peer-and-content-routing/2.js, examples/peer-and-content-routing/README.md, examples/peer-routing/README.md, src/index.js
=> Tutorial: Peer and Content Routing (aka DHT)

examples/transports/1.js, examples/transports/README.md
change node.isOn() to node.isStarted()
=> Fix transport example

.gitignore, .travis.yml, README.md, package.json, test/browser-bundle/webrtc-star-only.js, test/nodejs-bundle/discovery.js, test/nodejs-bundle/tcp+websockets+webrtc-star.js
ref: https://github.com/ipfs/js-ipfs/issues/981
=> feat: p2p addrs situation

examples/libp2p-in-the-browser/1/src/browser-bundle.js
=> docs(examples): update browser /wss bootstrap list

package.json
=> chore: Upgrade wrtc to 0.0.63

pdd/README.md, pdd/package.json, pdd/pdd-the-ipfs-bundle--story-1--peer-b.js, pdd/pdd-transport--story-1--peer-a.js, pdd/pdd-transport--story-1--peer-b.js, pdd/pdd-transport--story-2--peer-a.js, pdd/pdd-transport--story-2--peer-b.js, pdd/pdd-transport--story-3--peer-a.js, pdd/pdd-transport--story-3--peer-b.js, src/index.js
=> PDD Compliance Tests

examples/chat/src/listener.js, examples/echo/src/listener.js
Fixes the current echo example
=> update echo and chat examples to use libp2p-switch

CONTRIBUTING.md, README.md, package.json
ref https://github.com/ipfs/community/pull/301
=> Lead maintainer

examples/libp2p-in-the-browser/README.md
=> docs: add install dependencies

RELEASE.md
In line with https://github.com/ipfs/js-ipfs/pull/1765, this adds discuss to the release checklist
=> chore: add discuss.ipfs.io to release checklist

README.md
Links to our shiny new [discussion forum](https://discuss.libp2p.io) and [docs site](https://docs.libp2p.io)
=> chore: update readme with links to docs & discuss

examples/chat/README.md, examples/delegated-routing/package.json, examples/delegated-routing/src/App.js, examples/delegated-routing/src/index.js, examples/delegated-routing/src/libp2p-bundle.js, examples/discovery-mechanisms/1.js, examples/discovery-mechanisms/2.js, examples/echo/README.md, examples/libp2p-in-the-browser/1/package.json, examples/libp2p-in-the-browser/1/src/browser-bundle.js, examples/libp2p-in-the-browser/1/src/index.js, examples/peer-and-content-routing/1.js, examples/peer-and-content-routing/2.js, examples/peer-and-content-routing/README.md, examples/pubsub/1.js, examples/pubsub/README.md
This fixes the existing examples for the 0.25 release.
=> docs: update examples for latest libp2p rc

CONTRIBUTING.md
=> docs: fix contributing readme

package.json, src/config.js, test/switch/browser.js
The same as #405 but for the 0.26.x line
=> fix: avoid using superstruct interface

README.md
PR for #399 
Simply remove the link, if there is a new link, just let me know, will update it.
=> Remove dead link from readme

README.md
=> docs: redirect to the npm docs for latest release

.travis.yml, package.json
This PR adds a CI job to run the interop tests 🎉
=> chore: interop tests job in ci

package.json
Per https://github.com/ipfs/aegir/pull/557 we need to update aegir
=> chore: update aegir

doc/API.md, doc/CONFIGURATION.md
This adds a specification for the properties of each libp2p component options
=> docs: libp2p components options specified

package.json, test/pubsub/operation.node.js
Validates https://github.com/libp2p/js-libp2p/issues/658 and #677 
Needs:
=> chore: add test for pubsub on reconnect

doc/API.md, src/peer-store/address-book.js, src/peer-store/book.js
Per https://github.com/libp2p/js-libp2p/pull/714#issuecomment-660953669
=> docs: update addressBook get and getMultiaddrsForPeer return values

src/peer-store/persistent/index.js
With the latest PRs merged in + previous aegir update, a linting issue was introduced
=> chore: lint issue fixed

src/circuit/auto-relay.js, src/circuit/circuit/hop.js, src/identify/index.js, src/record/utils.js, src/transport-manager.js
Fixes lint on 0.30 branch after rebasing master. I will need to rebase all open PRs targetting 0.30
=> chore: lint issue fixed 0.30

examples/transports/README.md
=> docs: fix typo in transports example README

README.md
This replaces travis badge per github action badge
=> chore: add github actions badge

.github/workflows/main.yml, examples/discovery-mechanisms/1.js, examples/discovery-mechanisms/bootstrapers.js, examples/discovery-mechanisms/test-1.js, examples/discovery-mechanisms/test-2.js, examples/discovery-mechanisms/test.js
This PR adds tests for the discovery examples, as well as a CI job
=> chore: add discovery example tests

src/connection-manager/index.js, test/connection-manager/index.node.js
fix close for ConnectionManager
=> chore: fix close for ConnectionManager

.github/workflows/main.yml, examples/pnet/test.js
This PR adds an example to the private network example
=> chore: pnet example test

.github/workflows/main.yml, examples/peer-and-content-routing/test-1.js, examples/peer-and-content-routing/test-2.js, examples/peer-and-content-routing/test.js
This PR adds tests for the peer and content routing example
=> chore: add peer and content routing example tests

.github/workflows/main.yml, examples/protocol-and-stream-muxing/test-1.js, examples/protocol-and-stream-muxing/test-2.js, examples/protocol-and-stream-muxing/test-3.js, examples/protocol-and-stream-muxing/test.js
This PR adds tests for the protocol and stream muxing example
=> chore: add protocol and stream muxing example tests

.github/workflows/main.yml, examples/pubsub/message-filtering/test.js, examples/pubsub/test-1.js, examples/pubsub/test.js
This PR adds tests for the pubsub examples
=> chore: add pubsub example tests

.aegir.js, .github/workflows/main.yml, examples/transports/test-1.js, examples/transports/test-2.js, examples/transports/test-3.js, examples/transports/test.js, test/dialing/direct.spec.js
This PR adds tests for the transports example
=> chore: add transports example

doc/CONFIGURATION.md
missing some commas on the properties to create the http client for the delegates
=> chore: delegates config md properties for client

RELEASE.md
We now have tests for the examples, so we do not need to make sure all the examples work manually 🎉
=> chore: update release template with examples already being tested

examples/libp2p-in-the-browser/README.md
=> Dependencies must be installed at the root first

package.json, src/index.js, src/keychain/index.js
=> fix: keychain optional pw and use interfaces for validators and selectors instead

package.json
Updates to new libp2p interop, with secio tests removed and new daemon
=> chore: update libp2p interop

.github/workflows/main.yml, examples/libp2p-in-the-browser/index.html, examples/libp2p-in-the-browser/package.json
This PR addresses two issues:
- Tests were not running as the previous yaml action format was erroring (silently) and it got unnoticed as CI was still running but just for examples 😱 
- Browser tests were failing due to parcel changes
=> fix: main action node setup and browser example CI

src/nat-manager.js
=> fix: private ip ts compile has no call signatures

examples/auto-relay/README.md
=> examples: fix the content error in auto-relay/README.md (#1014)

examples/discovery-mechanisms/README.md
Just some minor docs fixes so that the readme contains valid code and mirrors the example found in `2.js`
=> minor corrections to discovery-mechanisms readme

doc/CONFIGURATION.md
Changed LevelStore to LevelDatastore
=> docs: naming error in the documentation

README.md
see: https://github.com/libp2p/js-libp2p/blob/b425fa12304def2a007d43a0aa445c28b766ed02/package.json#L69
=> Update version badge according to package.json

src/dialer/index.js, src/index.js, src/metrics/stats.js
**Motivation**
+ I'd like to fix tsc compilation error when using v0.35.6 for lodestar
**Description**
Closes #1073
=> Fix type definition for v0.35.6

.github/workflows/main.yml
Adds release-please github action to create gated releases and a release issue that tracks all issues that will be in a release.
=> chore: add automated releases

examples/connection-encryption/test.js, examples/discovery-mechanisms/test-1.js, examples/peer-and-content-routing/test-1.js, examples/peer-and-content-routing/test-2.js, examples/pnet/test.js, examples/protocol-and-stream-muxing/test-1.js, examples/protocol-and-stream-muxing/test-2.js, examples/protocol-and-stream-muxing/test-3.js, examples/transports/test-1.js, examples/transports/test-2.js, examples/transports/test-3.js, examples/transports/test-4.js
Remove some of the redundancy in the example tests
=> chore: update example tests

.github/workflows/main.yml
Need to run the checkout and setup-node actions before publishing
an RC.
=> chore: checkout code and set up node for publishing rc

.github/workflows/main.yml
Run CI tests and check at the same time
=> chore: run test after build

src/identify/index.js
Sometimes identify can be started while we are shutting down (for
example) - we should just log these errors.
=> fix: catch errors during identify

examples/auto-relay/README.md
The docs code sample is not similar to the actual code which can lead to confusion.
=> Instruction and the code is mismatch

src/dialer/index.ts, src/index.ts, src/libp2p.ts, test/core/get-public-key.spec.ts
This is used externally by IPFS so expose the method
=> fix: expose getPublicKey

doc/CONFIGURATION.md
Looks like this was missed when updating docs
=> docs: update websockets import var

examples/pubsub/message-filtering/1.js, examples/pubsub/message-filtering/README.md, examples/pubsub/message-filtering/test.js
Updates the example to use the new pubsub `addEventListener`-style API along with the README.
Also updates the test to actually test that the relevant messages were received.
Fixes https://github.com/libp2p/js-libp2p/issues/1288
=> docs: update message filtering example

examples/delegated-routing/package.json, examples/libp2p-in-the-browser/package.json, examples/webrtc-direct/package.json, package.json, src/insecure/index.ts
Update API to make peer id optional.
=> fix: update insecure connection encrypter

src/connection-manager/index.ts
Temporary fix until #1398 is merged.
=> fix: stub new connection manager accept incoming connection method

doc/METRICS.md
Document how libp2p components can record metrics
=> docs: update metrics docs

src/connection-manager/dialer/index.ts, test/dialing/direct.node.ts
=> fix: dialling duplicated addresses

README.md
Closes https://github.com/libp2p/js-libp2p/issues/1408
=> docs: updated projects using libp2p in README

src/fetch/README.md, src/pnet/README.md, src/pnet/key-generator.ts
The docs in these modules are out of date
=> docs: update fetch and pnet docs

src/config.ts, src/connection-manager/index.ts, src/peer-routing.ts
Removes the extra defaults set as they are unnecessary.
=> fix: revert config changes from #1520

src/circuit/index.ts, src/circuit/transport.ts
=> feat: allow configuring circuit stream limits

examples/libp2p-in-the-browser/test.js, package.json, src/transport-manager.ts, test/dialing/direct.node.ts, test/upgrading/upgrader.spec.ts
remove dependency on `p-settle` and use native, spec'ed / builtin `Promise.allSettled` instead.
=> fix: remove p-settle dependency, use Promise.allSettled instead

src/content-routing/utils.ts
This error message of "not found" is completely unhelpful when developing. I imagine providing more context would save devs some time
=> fix(content-routing:utils): improve requirePeers error msg

src/connection-manager/auto-dial.ts
Log the chosen peer ratio at the end
=> fix: remove autodial log line

examples/delegated-routing/package.json, package.json, test/peer-routing/peer-routing.node.ts
=> chore: fix build

src/autonat/index.ts
Edits for consistency and ensure that multiaddrs are readable when logging in browser environments.
=> fix: update autonat logging

doc/CONFIGURATION.md
fixed broken link by updating file to contain the correct url
=> docs(transports): broken link

.aegir.js, test/circuit-relay/relay.node.ts, test/circuit-relay/relay.spec.ts
Adds some tests to ensure the expected events occur when circuit relay connections close.
=> test: add tests for circuit relay events

doc/CONFIGURATION.md
=> docs: add note about muxer ordering

test/autonat/index.spec.ts, test/identify/service.spec.ts
To see if this is still broken in ci.
=> chore: remove webkit fixes

src/identify/identify.ts, test/identify/index.spec.ts
Fixes a bug where we were ignoring identify data when the remote peer did not send a signed peer record.
Fixes #1789
=> fix: store unsigned identify data when signed peer record is missing

package.json, src/upnp-nat/index.ts
Required to [fix CI](https://github.com/libp2p/js-libp2p/actions/runs/5204165044/jobs/9388014986#step:5:13)
=> deps: update nat-port-mapper

examples/pubsub/README.md
enclose `pubsub: gossibsub(...` with `services: {}`
=> docs: Update README.md configure pubsub as a service module

doc/CONFIGURATION.md
- Reinstates muxer selection header
- Restores missing code fence above UPnP section.
=> docs: fix muxer selection doc and UPnP config

packages/transport-webrtc/examples/browser-to-browser/README.md
Update to `p2p-circuit/webrtc` in accordance with https://github.com/libp2p/specs/blob/master/webrtc/webrtc.md#connection-establishment
=> docs: update p2p-circuit/webrtc in README.md

.github/workflows/main.yml
This gives us access to more powerful machines and more disk space - related to https://github.com/libp2p/test-plans/issues/229#issuecomment-1648206260
=> chore: run multidim-interop on self-hosted runners

packages/transport-webrtc/package.json
Temporary fix for https://github.com/libp2p/js-libp2p/issues/1922
=> chore: add --exit to node webrtc tests

packages/transport-websockets/src/index.ts
The event listeners were set up to throw the first argument which is a WebSocket.ErrorEvent and not an error.
The actual event doesn't really give us any useful information so just throw a generic error.
=> fix(@libp2p/websockets): do not throw error event

packages/transport-webtransport/src/index.ts, packages/transport-webtransport/test/browser.ts
Refactors session closing to happen in one function and call that function when the session has closed or failed to init.
Doesn't quite solve the "Too many pending WebTransport Sessions" problem but does slow it down a little bit.
Refs: #1896
=> fix(@libp2p/webtransport): be more thorough about closing sessions

packages/peer-record/package.json, packages/peer-record/src/envelope/index.ts
The new version is much faster
=> deps: update uint8-varint

packages/kad-dht/package.json, packages/kad-dht/src/providers.ts, packages/libp2p/package.json, packages/multistream-select/package.json, packages/multistream-select/test/multistream.spec.ts, packages/peer-record/package.json, packages/peer-record/src/envelope/index.ts, packages/stream-multiplexer-mplex/package.json, packages/stream-multiplexer-mplex/src/encode.ts
It's faster and is used elsewhere saving us a dep.
=> deps: switch varint for uint8-varint

.github/workflows/main.yml
Related https://github.com/libp2p/js-libp2p/pull/1988#issuecomment-1692173857
=> chore: add refactor to release please tags

packages/protocol-perf/package.json, packages/protocol-perf/src/main.ts
=> fix(@libp2p/protocol-perf): use noise for encryption

doc/CONFIGURATION.md
fixes https://github.com/libp2p/js-libp2p/issues/1996
=> docs: fix broken @libp2p/mdns link

packages/libp2p/CHANGELOG.md
Closes https://github.com/libp2p/js-libp2p/issues/2039
=> docs: Update CHANGELOG.md

packages/transport-webrtc/src/private-to-private/transport.ts, packages/transport-webrtc/src/private-to-public/transport.ts, packages/transport-webtransport/src/index.ts
Use the documented libp2p metrics system to collect metrics for the webrtc and webtransport transports
=> feat: collect dial/listen metrics in webrtc and webtransport

packages/libp2p/src/circuit-relay/transport/index.ts, packages/libp2p/src/upgrader.ts
Updates a couple of log lines to include more information.
=> fix(libp2p): update circuit relay and upgrader logs

CONTRIBUTING.md, README.md
Remove/update outdated info.  
Drive contributing info to CONTRIBUTING.md
=> docs: refresh README.md and CONTRIBUTING.md

doc/GETTING_STARTED.md
docs: fix typo in Typescript example in README
There is a syntax error in the import statements of the TS example.
=> docs: fix syntax error in JS example in README

.github/workflows/main.yml
chore: update ci to use transport-interop action
Given the rename of `multidim-interop` to `transport-interop` which happened in https://github.com/libp2p/test-plans/pull/308 the composite action which is run on our PRs needs to be updated.
Closes https://github.com/libp2p/js-libp2p/issues/2128
=> chore: update ci to use transport-interop action

.github/workflows/main.yml
Specify where codecov should load files from
=> chore: update coverage file locations

interop/package.json
rename multidim interop test script 
Closes https://github.com/libp2p/js-libp2p/issues/2130 as we are now more specific in what we are testing
=> refactor: rename multidim interop test script 

packages/interface-compliance-tests/src/mocks/connection.ts
When using mock streams pairs, we use a simple duplex to pass the input of one to the output of the other.
The input can be a `Uint8Array` or a `Uint8ArrayList` but the output can only be `Uint8ArrayList` so ensure we output the correct type.
=> fix: ensure mock stream output is uint8arraylist

.release-please.json
Removes version config overrides so release-please will give us a v1 for libp2p.
=> chore!: update release config

.github/workflows/main.yml, run-client.ts, run-server.ts, run.ts
Updates to 3.1.4 which should run on a supported node version
=> chore: update codecov action version

.github/workflows/examples.yml
chore: re-enable examples test matrix within ci
Once https://github.com/libp2p/js-libp2p/pull/2240 is released we should re-enable the examples 
-  [x] I have performed a self-review of my own code
=> chore: re-enable examples ci

packages/libp2p/src/upgrader.ts
Ensure the log messages make sense
=> fix: update log messages

.gitignore
chore: remove duplicate entry in .gitignore
There were two `node_modules` entries in .gitignore
=> chore: remove duplicate entry in .gitignore

CONTRIBUTING.md, README.md
docs: updated README to include discussions info
This includes Open Maintainer call info + filing bugs & security reports.
=> docs: updated README to include Open Maintainer call schedule

.github/ISSUE_TEMPLATE/config.yml
Clarify where technical js-libp2p questions should go and where libp2p community discussions happen.
=> chore(cfg): Update config.yml to clarify new issues

.github/workflows/main.yml
https://github.com/libp2p/test-plans/issues/343 is fixed so revert #2374
=> chore: re-enable interop tests

README.md, packages/libp2p/README.md
Add Peerbit logo to "Used by" section
Add Peerbit logo to "Used by" section
From suggestion by @achingbrain. 
When adding the logo I realized that there are two READMEs that are very similiar and both have this "Used by" section, so I added it to both. But if it make sense to only add to one of them, please let me know. 
Also spent some time trying to align the Lodestar logo, but it Github will not allow me to really.
=> docs: add Peerbit logo

packages/transport-webtransport/README.md
=> docs: fix out of date webtransport example

packages/transport-webrtc/README.md, packages/transport-webrtc/package.json, packages/transport-webrtc/src/index.ts
Documents the difference between WebRTC and WebRTC Direct.
=> docs: update webrtc readme to show difference between transports

packages/transport-webrtc/README.md, packages/transport-webrtc/src/index.ts
Change listener to dialer in webrtc example
=> docs: change listener to dialler in webrtc example

packages/protocol-autonat/README.md, packages/protocol-autonat/src/index.ts
Document AutoNAT service - how it works and where results can be found.
=> docs(autonat): Add documentation on where to get results of service

packages/libp2p/src/components.ts
For use in services, add to internal components list.
=> fix: add randomwalk to components

.github/workflows/main.yml, interop/Dockerfile, interop/relay.js, interop/test/ping.spec.ts
Attempt to fix flaky interop tests.
=> chore: upgrade interop test node version, remove extended ping timeout

packages/peer-collections/src/filter.ts
Adds more explanation about peer filter params.
=> fix: update peer filter jsdoc comments

.github/workflows/main.yml
The release-please action has been renamed to googleapis/release-please-action
=> chore: update release-please action

packages/protocol-autonat/src/autonat.ts
Small refactor to reduce code complexity and make refactorting to web streams a little less disruptive.
=> fix: refactor autonat to handle messages in separate method

doc/SERVICES.md
Writes up the perceived wisdom on service implementation.
=> docs: add doc on configuring custom services

packages/transport-circuit-relay-v2/src/transport/reservation-store.ts, packages/utils/src/queue/job.ts, packages/utils/src/queue/recipient.ts
Remove code left in by accident.
=> chore: remove logging code

packages/protocol-fetch/README.md, packages/protocol-fetch/src/index.ts
=> docs: typo in protocol fetch

packages/kad-dht/src/rpc/index.ts
Adds a `libp2p_kad_dht_inbound_rpc_requests` counter group that has labels for success/error outcomes of each RPC call type.
=> feat: add inbound rpc request metrics

packages/connection-encrypter-tls/src/tls.ts
When we can't read the incoming certificate or a timeout occurs, ensure the underlying socket is destroyed.
=> fix: close tls socket on encryption failure

packages/kad-dht/src/kad-dht.ts, packages/kad-dht/src/network.ts, packages/kad-dht/src/query/query-path.ts, packages/kad-dht/src/routing-table/index.ts, packages/kad-dht/src/rpc/handlers/add-provider.ts, packages/kad-dht/src/rpc/index.ts, packages/kad-dht/test/kad-dht.spec.ts
Make some more verbose logging trace logging and switch metrics to use separate operation/error metrics.
Refs: https://promlabs.com/blog/2023/09/19/errors-successes-totals-which-metrics-should-i-expose-to-prometheus/
=> fix: reduce dht logging and update metrics

packages/multistream-select/src/handle.ts, packages/protocol-identify/package.json, packages/protocol-identify/src/identify-push.ts, packages/protocol-identify/src/identify.ts, packages/protocol-identify/src/utils.ts
Where logging is very verbose, switch informational logs to trace logging
=> fix: switch informational logging to trace logging

packages/metrics-prometheus/src/index.ts
Adds a `nodejs_fs_usage_bytes` metric that reports how much disk space is available.
=> feat: collect metrics on available storage

packages/libp2p/src/connection-manager/index.ts
This is similar to the dial queue size but is reported in a way that's analogous to inbound pending connections metric making it a bit easier to digest.
=> fix: record outbound pending connections metric

packages/kad-dht/src/network.ts, packages/kad-dht/src/query/manager.ts, packages/kad-dht/src/routing-table/index.ts
Using a metric for running queries misses most queryies because they complete within the scrape interval. Use a counter instead along with another for errors and record outgoing RPC messages in the same way as incoming ones.
=> fix: record query metrics properly

packages/utils/package.json, packages/utils/src/errors.ts, packages/utils/src/queue/index.ts, packages/utils/test/peer-job-queue.spec.ts, packages/utils/test/queue.spec.ts
Also restore accidentally deleted tests
=> feat: add maxSize to queues

.github/workflows/examples.yml
Adds all missing examples and re-enables testing main with them.
=> chore: re-enable testing examples

CONTRIBUTING.md
=> docs: update link to luma

packages/transport-webrtc/README.md, packages/transport-webrtc/src/index.ts
Updates example to incorporate changes from #2776
This is done in a separate PR because doing it in #2776 would cause a major of `@libp2p/webrtc` to be released.
=> docs: update webrtc example

doc/CONFIGURATION.md
- Update the docs with up-to-date information about delegated routing including the example.
- Fix some broken links and examples
=> docs: update delegated routing

.github/workflows/examples.yml
Updates example to use the latest circuit relay transport.
=> chore: re-enable examples

packages/utils/package.json, packages/utils/src/debounce.ts, packages/utils/src/repeating-task.ts, packages/utils/test/debounce.spec.ts, packages/utils/test/repeating-task.spec.ts, packages/utils/typedoc.json
This functionality is required in multiple places so add it to the utils module.
=> feat: add debounce and repeating task to utils

packages/interface/src/transport/index.ts
Will cause a release that includes changes added as part of a previous `chore:` commit.
=> fix: update transport listener options

packages/protocol-autonat/src/autonat.ts
Add the service capability to signal to other components that autonat can provide functionality
=> fix: add autonat capability

packages/libp2p/src/connection-manager/dial-queue.ts, packages/libp2p/test/connection-manager/dial-queue.spec.ts
Make sure we always respect the users' dial signal over the default dial timeout, even if it is longer than the default.
Previously the shortest timeout would win.
=> fix: ensure user dial signals are respected

packages/libp2p/scripts/update-version.js, packages/libp2p/src/version.ts
Prefix the agent version name with `js-`
=> fix: update agent version

packages/utils/package.json, packages/utils/src/link-local-ip.ts, packages/utils/test/link-local-ip.spec.ts
To detect when an IP address is link local, add a function.
=> feat: add isLinkLocalIp function

packages/upnp-nat/src/upnp-port-mapper.ts
Confirm the public ip, not the private one
=> fix: confirm external ip

packages/config/README.md, packages/config/src/index.ts
Corrects config options in readme.
=> docs: update config docs

doc/CONFIGURATION.md
This PR is small fix in the documentation that I noticed where the syntax was incorrect.
added curly braces to bootstrap
=> docs: fix bootstrap config 

packages/auto-tls/src/index.ts
=> docs: fix syntax of example in auto-tls module

.github/workflows/main.yml, interop/test/fixtures/get-libp2p.ts
Switch from ping test to transport interop test action
=> chore: update transport test action

packages/transport-webrtc/README.md, packages/transport-webrtc/src/index.ts
Updates the readme to reflect the current state of webrtc-direct
=> docs: update webrtc-direct docs

packages/interface-internal/README.md, packages/interface-internal/src/index.ts
Update the readme with the new package documentation block.
=> docs: update interface-internal readme

packages/transport-webrtc/src/private-to-public/listener.ts
Since one node creates a listener for each listening address, then gets that listener to listen on a multiaddr, we need to allow them each to access the mux registry.
Ensures that different nodes can't listen on the same mux address.
=> fix: make UDP mux registry global

packages/integration-tests/package.json, packages/integration-tests/test/identify.node.ts
Explicitly run integration tests on node.
=> chore: run node integration tests

packages/transport-circuit-relay-v2/src/transport/listener.ts
Be more specific about relay servers
=> chore: small logging improvement

packages/connection-encrypter-tls/src/index.ts, packages/connection-encrypter-tls/src/tls.ts
Adds metrics for events and errors
=> feat: add metrics to tls encrypter

packages/protocol-ping/src/index.ts, packages/protocol-ping/src/ping.ts, packages/protocol-ping/test/index.spec.ts
Inform other components that this module can provide ping services.
=> fix: export ping service capabilities

packages/transport-memory/README.md
This should not be in the readme.
=> docs: remove tcp header from memory transport

packages/config/README.md, packages/config/src/index.ts, packages/connection-encrypter-plaintext/README.md, packages/connection-encrypter-plaintext/src/index.ts, packages/crypto/src/ciphers/aes-gcm.browser.ts, packages/crypto/src/ciphers/aes-gcm.ts, packages/crypto/src/ciphers/interface.ts, packages/interface-compliance-tests/src/matchers.ts, packages/interface/src/content-routing.ts, packages/interface/src/errors.ts, packages/interface/src/event-target.ts, packages/interface/src/index.ts, packages/interface/src/metrics.ts, packages/interface/src/peer-discovery.ts, packages/interface/src/peer-routing.ts, packages/interface/src/pubsub.ts, packages/interface/src/record.ts, packages/interface/src/startable.ts, packages/interface/src/topology.ts, packages/interface/src/transport.ts, packages/libp2p/README.md, packages/peer-collections/src/filter.ts, packages/peer-record/src/envelope/index.ts, packages/protocol-identify/src/index.ts, packages/pubsub/package.json, packages/pubsub/typedoc.json
=> docs: update comments in interface module and elsewhere

packages/metrics-opentelemetry/package.json, packages/metrics-opentelemetry/src/index.ts, packages/metrics-opentelemetry/test/index.spec.ts, packages/metrics-prometheus/src/index.ts, packages/metrics-prometheus/test/index.spec.ts, packages/metrics-simple/src/index.ts, packages/metrics-simple/test/index.spec.ts
Otherwise the node can leak memory.
=> fix: clear references to metrics on stop
